// packages/react/src/components/code/ElmKatex.tsx
import React, { useEffect, useState } from "react";

import "@styles/global.css";
import styles from "./ElmKatex.module.css";

export interface ElmKatexProps {
  style?: React.CSSProperties;

  /**
   * The KaTeX expression to render.
   */
  expression: string;

  /**
   * Whether to render in block (display) mode.
   * Default is false (inline mode).
   */
  block?: boolean;
}

export const ElmKatex = ({
  expression,
  block = false,
  style,
}: ElmKatexProps) => {
  const [html, setHtml] = useState<string | undefined>();

  useEffect(() => {
    import("katex")
      .then(({ renderToString }) => {
        try {
          const result = renderToString(expression, {
            displayMode: block,
            output: "mathml",
          });
          setHtml(result);
        } catch (err) {
          console.error("KaTeX rendering error:", err);
        }
      })
      .catch(() => {
        // katex not available
      });
  }, [expression, block]);

  const className = `${styles.katex}`;

  if (block) {
    return (
      <div
        className={className}
        style={{ marginBlock: "3rem", ...style }}
        dangerouslySetInnerHTML={html ? { __html: html } : undefined}
      />
    );
  }

  return (
    <span
      className={className}
      style={style}
      dangerouslySetInnerHTML={html ? { __html: html } : undefined}
    />
  );
};

// packages/vue/src/components/code/ElmKatex.vue
<template>
  <div
    v-if="props.block"
    ref="targetRef"
    :class="[$style.katex, textStyle.text]"
    :style="{
      '--margin-block': props.block ? '3rem' : undefined,
    }"
  >
    <span v-if="html" v-html="html"></span>
  </div>

  <span
    v-else
    ref="targetRef"
    :class="[$style.katex, textStyle.text]"
    :style="{
      '--margin-block': props.block ? '3rem' : undefined,
    }"
  >
    <span v-if="html" v-html="html"></span
  ></span>
</template>

<script setup lang="ts">
import { onMounted, onServerPrefetch, onUpdated, ref } from "vue";

import textStyle from "../../styles/text.module.scss";

export interface ElmKatexProps {
  /**
   * The KaTex expression.
   */
  expression: string;

  /**
   * Whether to render the equation in block mode.
   * - If `true`, the equation will be rendered in block mode.
   * - If `false`, the equation will be rendered in inline mode.
   *
   * Default is `false`.
   */
  block?: boolean;
}

const props = withDefaults(defineProps<ElmKatexProps>(), {
  block: false,
});

const html = ref<string | undefined>();

let katexRenderToString:
  | ((
      expression: string,
      options: { displayMode: boolean; output: "mathml" },
    ) => string)
  | null = null;

const loadKatex = async () => {
  if (!katexRenderToString) {
    const { renderToString } = await import("katex");
    katexRenderToString = renderToString;
  }
};

const render = async () => {
  await loadKatex();

  if (html.value == null && katexRenderToString) {
    try {
      html.value = katexRenderToString(props.expression, {
        displayMode: props.block,
        output: "mathml",
      });
    } catch (err) {
      console.error("KaTeX rendering error:", err);
    }
  }
};

onMounted(render);
onUpdated(render);
onServerPrefetch(render);
</script>

<style module lang="scss">
.katex {
  margin-block: var(--margin-block);
}
</style>
