// packages/solid/src/components/form/elm-slider.tsx
import {
  createEffect,
  createMemo,
  createSignal,
  For,
  onCleanup,
  onMount,
  Show,
  splitProps,
  type Accessor,
  type JSX,
} from "solid-js";
import { clsx } from "clsx";

import { callEventHandler } from "../../primitives/call-event-handler";
import { createControllableSignal } from "../../primitives/create-controllable-signal";
import { mergeStyle } from "../../styles/merge-style";
import styles from "./elm-slider.module.css";

export type ElmSliderOrientation = "horizontal" | "vertical";

export interface ElmSliderProps extends Omit<
  JSX.HTMLAttributes<HTMLDivElement>,
  "defaultValue" | "onChange"
> {
  /** Lower bound of the track's full range. @defaultValue 0 */
  min?: number;
  /** Upper bound of the track's full range. @defaultValue 100 */
  max?: number;
  /** Increment used for pointer snapping and keyboard movement. @defaultValue 1 */
  step?: number;
  /** Lowest reachable value inside the full track range. @defaultValue min */
  innerMin?: number;
  /** Highest reachable value inside the full track range. @defaultValue max */
  innerMax?: number;
  /** Track direction. @defaultValue "horizontal" */
  orientation?: ElmSliderOrientation;
  /** Controlled value. When provided, the parent owns the value. */
  value?: number;
  /** Initial uncontrolled value. @defaultValue midpoint of the inner range */
  defaultValue?: number;
  /** Called with the next value whenever it changes. */
  onValueChange?: (value: number) => void;
  /** Disables pointer and keyboard interaction. */
  disabled?: boolean;
  /** Draws a tick mark at every rendered step. */
  markers?: boolean;
  /** Draws a label at every rendered step. */
  markerLabels?: boolean;
  /** Formats marker label content. @defaultValue String(value) */
  formatMarkerLabel?: (value: number) => JSX.Element;
}

interface Mark {
  value: number;
  ratio: number;
}

interface ResolvedMark extends Mark {
  label: Accessor<JSX.Element | undefined>;
}

const MAX_MARKERS = 500;

const clamp = (value: number, low: number, high: number) =>
  Math.min(high, Math.max(low, value));

const preciseRound = (value: number) =>
  Math.round(value * 1_000_000_000) / 1_000_000_000;

const primitiveTextLength = (value: unknown): number => {
  if (typeof value === "string" || typeof value === "number") {
    return String(value).length;
  }
  if (Array.isArray(value)) {
    return value.reduce(
      (length: number, item: unknown) => length + primitiveTextLength(item),
      0,
    );
  }
  return 0;
};

const buildMarks = (
  enabled: boolean,
  min: number,
  max: number,
  step: number,
): Mark[] => {
  if (!enabled || max === min) {
    return [];
  }

  const magnitude = Math.abs(step);
  if (magnitude === 0) {
    return [];
  }

  const signedStep = max > min ? magnitude : -magnitude;
  const realCount = Math.floor(preciseRound(Math.abs(max - min) / magnitude));
  const marks: Mark[] = [];

  if (realCount <= MAX_MARKERS) {
    for (let index = 0; index <= realCount; index++) {
      const value = preciseRound(min + index * signedStep);
      marks.push({
        value,
        ratio: max === min ? 0 : clamp((value - min) / (max - min), 0, 1),
      });
    }

    if (preciseRound(min + realCount * signedStep) !== preciseRound(max)) {
      marks.push({ value: max, ratio: 1 });
    }
  } else {
    const sampledStep = (max - min) / MAX_MARKERS;
    for (let index = 0; index <= MAX_MARKERS; index++) {
      const value =
        index === MAX_MARKERS ? max : preciseRound(min + index * sampledStep);
      marks.push({ value, ratio: index / MAX_MARKERS });
    }
  }

  return marks;
};

export const ElmSlider = (props: ElmSliderProps) => {
  const [local, rest] = splitProps(props, [
    "ref",
    "class",
    "style",
    "children",
    "onKeyDown",
    "onPointerDown",
    "onPointerMove",
    "onPointerUp",
    "onPointerCancel",
    "onLostPointerCapture",
    "min",
    "max",
    "step",
    "innerMin",
    "innerMax",
    "orientation",
    "value",
    "defaultValue",
    "onValueChange",
    "disabled",
    "markers",
    "markerLabels",
    "formatMarkerLabel",
  ]);
  const min = () => local.min ?? 0;
  const max = () => local.max ?? 100;
  const step = () => local.step ?? 1;
  const orientation = () => local.orientation ?? "horizontal";
  const rangeLow = createMemo(() => Math.min(min(), max()));
  const rangeHigh = createMemo(() => Math.max(min(), max()));
  const effectiveInnerMin = createMemo(() =>
    clamp(local.innerMin ?? rangeLow(), rangeLow(), rangeHigh()),
  );
  const effectiveInnerMax = createMemo(() =>
    clamp(local.innerMax ?? rangeHigh(), effectiveInnerMin(), rangeHigh()),
  );
  const clampValue = (value: number) =>
    clamp(preciseRound(value), effectiveInnerMin(), effectiveInnerMax());
  const snapValue = (value: number) => {
    const magnitude = Math.abs(step());
    const snapped =
      magnitude === 0
        ? value
        : min() + Math.round((value - min()) / magnitude) * magnitude;
    return clampValue(snapped);
  };
  const ratioOf = (value: number) =>
    max() === min() ? 0 : clamp((value - min()) / (max() - min()), 0, 1);

  const [currentValue, setCurrentValue] = createControllableSignal<number>({
    value: () => local.value,
    defaultValue: () =>
      clampValue(
        local.defaultValue ?? (effectiveInnerMin() + effectiveInnerMax()) / 2,
      ),
    onChange: (value) => local.onValueChange?.(value),
  });
  const displayValue = createMemo(() => clampValue(currentValue()));
  const valueRatio = createMemo(() => ratioOf(displayValue()));
  const numericInnerMinRatio = createMemo(() => ratioOf(effectiveInnerMin()));
  const numericInnerMaxRatio = createMemo(() => ratioOf(effectiveInnerMax()));
  const innerStartRatio = createMemo(() =>
    Math.min(numericInnerMinRatio(), numericInnerMaxRatio()),
  );
  const innerEndRatio = createMemo(() =>
    Math.max(numericInnerMinRatio(), numericInnerMaxRatio()),
  );
  const fillStartRatio = createMemo(() =>
    Math.min(valueRatio(), numericInnerMinRatio()),
  );
  const fillSizeRatio = createMemo(() =>
    Math.abs(valueRatio() - numericInnerMinRatio()),
  );

  const marksEnabled = createMemo(() =>
    Boolean(local.markers || local.markerLabels),
  );
  const marks = createMemo(() =>
    buildMarks(marksEnabled(), min(), max(), step()),
  );
  const resolvedMarks = createMemo<ResolvedMark[]>(() => {
    return marks().map((mark) => {
      const label = createMemo(() => {
        if (!local.markerLabels) {
          return undefined;
        }
        return local.formatMarkerLabel?.(mark.value) ?? mark.value;
      });
      return { ...mark, label };
    });
  });
  const maxMarkerLabelChars = createMemo(() =>
    resolvedMarks().reduce(
      (longest, mark) => Math.max(longest, primitiveTextLength(mark.label())),
      0,
    ),
  );

  const [maxMarkerLabelWidth, setMaxMarkerLabelWidth] = createSignal(0);
  const markerLabelElements = new Set<HTMLElement>();
  let labelObserver: ResizeObserver | undefined;
  let track: HTMLDivElement | undefined;
  let capturedPointerId: number | undefined;

  const measureMarkerLabels = () => {
    let width = 0;
    for (const element of markerLabelElements) {
      width = Math.max(width, element.getBoundingClientRect().width);
    }
    setMaxMarkerLabelWidth(Math.ceil(width));
  };

  const registerMarkerLabel = (element: HTMLElement) => {
    markerLabelElements.add(element);
    labelObserver?.observe(element);
    onCleanup(() => {
      markerLabelElements.delete(element);
      labelObserver?.unobserve(element);
      measureMarkerLabels();
    });
  };

  const releasePointer = (pointerId = capturedPointerId) => {
    if (pointerId === undefined || pointerId !== capturedPointerId) {
      return;
    }
    if (track?.hasPointerCapture(pointerId)) {
      track.releasePointerCapture(pointerId);
    }
    if (capturedPointerId === pointerId) {
      capturedPointerId = undefined;
    }
  };

  onMount(() => {
    labelObserver =
      typeof ResizeObserver === "undefined"
        ? undefined
        : new ResizeObserver(measureMarkerLabels);
    for (const element of markerLabelElements) {
      labelObserver?.observe(element);
    }
    measureMarkerLabels();

    onCleanup(() => {
      releasePointer();
      labelObserver?.disconnect();
      labelObserver = undefined;
      markerLabelElements.clear();
    });
  });

  createEffect(() => {
    if (local.disabled) {
      releasePointer();
    }
  });

  const valueFromPointer = (clientX: number, clientY: number) => {
    if (track == null) {
      return displayValue();
    }
    const rect = track.getBoundingClientRect();
    const ratio =
      orientation() === "vertical"
        ? rect.height === 0
          ? 0
          : clamp((rect.bottom - clientY) / rect.height, 0, 1)
        : rect.width === 0
          ? 0
          : clamp((clientX - rect.left) / rect.width, 0, 1);
    return snapValue(min() + ratio * (max() - min()));
  };

  const handlePointerDown: JSX.EventHandler<HTMLDivElement, PointerEvent> = (
    event,
  ) => {
    if (local.disabled) {
      return;
    }
    if (
      capturedPointerId !== undefined &&
      capturedPointerId !== event.pointerId
    ) {
      releasePointer();
    }
    event.currentTarget.setPointerCapture(event.pointerId);
    capturedPointerId = event.pointerId;
    setCurrentValue(valueFromPointer(event.clientX, event.clientY));
    callEventHandler(local.onPointerDown, event);
  };

  const handlePointerMove: JSX.EventHandler<HTMLDivElement, PointerEvent> = (
    event,
  ) => {
    if (local.disabled) {
      return;
    }
    if (
      capturedPointerId !== event.pointerId ||
      !event.currentTarget.hasPointerCapture(event.pointerId)
    ) {
      callEventHandler(local.onPointerMove, event);
      return;
    }
    setCurrentValue(valueFromPointer(event.clientX, event.clientY));
    callEventHandler(local.onPointerMove, event);
  };

  const handlePointerUp: JSX.EventHandler<HTMLDivElement, PointerEvent> = (
    event,
  ) => {
    if (local.disabled) {
      return;
    }
    releasePointer(event.pointerId);
    callEventHandler(local.onPointerUp, event);
  };

  const handlePointerCancel: JSX.EventHandler<HTMLDivElement, PointerEvent> = (
    event,
  ) => {
    if (local.disabled) {
      return;
    }
    releasePointer(event.pointerId);
    callEventHandler(local.onPointerCancel, event);
  };

  const handleLostPointerCapture: JSX.EventHandler<
    HTMLDivElement,
    PointerEvent
  > = (event) => {
    if (capturedPointerId === event.pointerId) {
      capturedPointerId = undefined;
    }
    if (!local.disabled) {
      callEventHandler(local.onLostPointerCapture, event);
    }
  };

  const handleKeyDown: JSX.EventHandler<HTMLDivElement, KeyboardEvent> = (
    event,
  ) => {
    if (local.disabled) {
      return;
    }
    const delta = Math.abs(step());

    switch (event.key) {
      case "ArrowRight":
      case "ArrowUp":
        event.preventDefault();
        setCurrentValue(clampValue(displayValue() + delta));
        break;
      case "ArrowLeft":
      case "ArrowDown":
        event.preventDefault();
        setCurrentValue(clampValue(displayValue() - delta));
        break;
      case "PageUp":
        event.preventDefault();
        setCurrentValue(clampValue(displayValue() + delta * 10));
        break;
      case "PageDown":
        event.preventDefault();
        setCurrentValue(clampValue(displayValue() - delta * 10));
        break;
      case "Home":
        event.preventDefault();
        setCurrentValue(effectiveInnerMin());
        break;
      case "End":
        event.preventDefault();
        setCurrentValue(effectiveInnerMax());
        break;
    }

    callEventHandler(local.onKeyDown, event);
  };

  return (
    <div
      class={clsx(
        styles["elm-slider"],
        orientation() === "vertical" && styles.vertical,
        local.disabled && styles.disabled,
        local.markers && styles["has-markers"],
        local.markerLabels && styles["has-marker-labels"],
        local.class,
      )}
      style={mergeStyle(local.style, {
        "--elmethis-scoped-value-ratio": valueRatio(),
        "--elmethis-scoped-inner-min-ratio": innerStartRatio(),
        "--elmethis-scoped-inner-max-ratio": innerEndRatio(),
        "--elmethis-scoped-fill-start-ratio": fillStartRatio(),
        "--elmethis-scoped-fill-size-ratio": fillSizeRatio(),
        "--elmethis-scoped-max-marker-label-chars": maxMarkerLabelChars(),
        "--elmethis-scoped-max-marker-label-width": `${maxMarkerLabelWidth()}px`,
      })}
    >
      <div
        tabIndex={local.disabled ? -1 : 0}
        {...rest}
        ref={(element) => {
          track = element;
          if (typeof local.ref === "function") {
            local.ref(element);
          }
        }}
        class={styles.track}
        role="slider"
        aria-orientation={orientation()}
        aria-valuemin={effectiveInnerMin()}
        aria-valuemax={effectiveInnerMax()}
        aria-valuenow={displayValue()}
        aria-disabled={local.disabled || undefined}
        onPointerDown={handlePointerDown}
        onPointerMove={handlePointerMove}
        onPointerUp={handlePointerUp}
        onPointerCancel={handlePointerCancel}
        onLostPointerCapture={handleLostPointerCapture}
        onKeyDown={handleKeyDown}
      >
        <div class={styles.rail} aria-hidden="true">
          <div class={styles["restricted-start"]} />
          <div class={styles.fill} />
          <div class={styles["restricted-end"]} />
        </div>

        <Show when={resolvedMarks().length > 0}>
          <div class={styles.marks} aria-hidden="true">
            <For each={resolvedMarks()}>
              {(mark, index) => (
                <span
                  class={clsx(
                    styles.mark,
                    index() === 0 && styles["mark-start"],
                    index() === resolvedMarks().length - 1 &&
                      styles["mark-end"],
                    (mark.value < effectiveInnerMin() ||
                      mark.value > effectiveInnerMax()) &&
                      styles["mark-restricted"],
                  )}
                  style={{ "--elmethis-scoped-marker-ratio": mark.ratio }}
                >
                  <Show when={local.markers}>
                    <i class={styles.tick} />
                  </Show>
                  <Show when={local.markerLabels}>
                    <span
                      ref={registerMarkerLabel}
                      class={styles["mark-label"]}
                    >
                      {mark.label()}
                    </span>
                  </Show>
                </span>
              )}
            </For>
          </div>
        </Show>

        <span class={styles.thumb} aria-hidden="true" />
      </div>
    </div>
  );
};

// packages/react/src/components/form/elm-slider.tsx
import {
  useCallback,
  useMemo,
  useRef,
  type ComponentPropsWithoutRef,
  type CSSProperties,
  type KeyboardEvent as ReactKeyboardEvent,
  type PointerEvent as ReactPointerEvent,
  type ReactNode,
} from "react";
import { clsx } from "clsx";

import { useBindableSignal } from "../../hooks/use-bindable-signal";
import styles from "./elm-slider.module.css";

export type ElmSliderOrientation = "horizontal" | "vertical";

export interface ElmSliderProps extends Omit<
  ComponentPropsWithoutRef<"div">,
  "onChange" | "defaultValue"
> {
  /**
   * Lower bound of the track's full range.
   *
   * @defaultValue 0
   */
  min?: number;

  /**
   * Upper bound of the track's full range.
   *
   * @defaultValue 100
   */
  max?: number;

  /**
   * Increment the value snaps to while dragging or using the keyboard.
   *
   * @defaultValue 1
   */
  step?: number;

  /**
   * Restricts the value to an interval inside the track's full length. Must
   * be `>= min`. The track still spans `[min, max]`, but the region below
   * `innerMin` is shown as unreachable.
   *
   * @defaultValue min
   */
  innerMin?: number;

  /**
   * Restricts the value to an interval inside the track's full length. Must
   * be `<= max`.
   *
   * @defaultValue max
   */
  innerMax?: number;

  /**
   * Track direction.
   *
   * @defaultValue "horizontal"
   */
  orientation?: ElmSliderOrientation;

  /**
   * Controlled value. When provided the parent owns the value.
   */
  value?: number;

  /**
   * Initial value when uncontrolled.
   *
   * @defaultValue the midpoint of `innerMin`/`innerMax`
   */
  defaultValue?: number;

  /**
   * Called with the next value whenever it changes.
   */
  onValueChange?: (value: number) => void;

  /**
   * Disables dragging, clicking, and keyboard control.
   */
  disabled?: boolean;

  /**
   * Draws a tick mark at every step along the track.
   */
  markers?: boolean;

  /**
   * Draws a text label under each tick mark.
   */
  markerLabels?: boolean;

  /**
   * Formats the text shown for a marker label.
   *
   * @defaultValue String(value)
   */
  formatMarkerLabel?: (value: number) => ReactNode;
}

const clamp = (n: number, lo: number, hi: number) =>
  Math.min(hi, Math.max(lo, n));

// Rounds away float dust (e.g. 0 + 3 * 0.1 -> 0.30000000000000004).
const preciseRound = (n: number) => Math.round(n * 1e9) / 1e9;

// Guards against generating an unbounded number of DOM nodes if a caller
// pairs a tiny `step` with a wide `[min, max]`.
const MAX_MARKERS = 500;

export const ElmSlider = ({
  className,
  style,
  min = 0,
  max = 100,
  step = 1,
  innerMin,
  innerMax,
  orientation = "horizontal",
  value,
  defaultValue,
  onValueChange,
  disabled,
  markers,
  markerLabels,
  formatMarkerLabel,
  ...rest
}: ElmSliderProps) => {
  const trackRef = useRef<HTMLDivElement>(null);
  const isVertical = orientation === "vertical";

  const effectiveInnerMin = clamp(innerMin ?? min, min, max);
  const effectiveInnerMax = clamp(innerMax ?? max, effectiveInnerMin, max);

  const snap = useCallback(
    (raw: number) => {
      const stepped =
        step > 0 ? min + Math.round((raw - min) / step) * step : raw;
      return clamp(preciseRound(stepped), effectiveInnerMin, effectiveInnerMax);
    },
    [min, step, effectiveInnerMin, effectiveInnerMax],
  );

  const [currentValue, setCurrentValue] = useBindableSignal<number>({
    value,
    defaultValue: snap(
      defaultValue ?? (effectiveInnerMin + effectiveInnerMax) / 2,
    ),
    onChange: onValueChange,
  });

  const ratioOf = useCallback(
    (v: number) => (max === min ? 0 : clamp((v - min) / (max - min), 0, 1)),
    [min, max],
  );

  const valueFromPointer = useCallback(
    (clientX: number, clientY: number): number => {
      const el = trackRef.current;
      if (!el) return currentValue;
      const rect = el.getBoundingClientRect();
      const ratio = isVertical
        ? rect.height === 0
          ? 0
          : clamp((rect.bottom - clientY) / rect.height, 0, 1)
        : rect.width === 0
          ? 0
          : clamp((clientX - rect.left) / rect.width, 0, 1);
      return snap(min + ratio * (max - min));
    },
    [currentValue, isVertical, max, min, snap],
  );

  const handlePointerDown = useCallback(
    (event: ReactPointerEvent<HTMLDivElement>) => {
      if (disabled) return;
      event.currentTarget.setPointerCapture(event.pointerId);
      setCurrentValue(valueFromPointer(event.clientX, event.clientY));
    },
    [disabled, setCurrentValue, valueFromPointer],
  );

  const handlePointerMove = useCallback(
    (event: ReactPointerEvent<HTMLDivElement>) => {
      if (disabled) return;
      if (!event.currentTarget.hasPointerCapture(event.pointerId)) return;
      setCurrentValue(valueFromPointer(event.clientX, event.clientY));
    },
    [disabled, setCurrentValue, valueFromPointer],
  );

  const handleKeyDown = useCallback(
    (event: ReactKeyboardEvent<HTMLDivElement>) => {
      if (disabled) return;
      // `step` is a granularity, not a direction — a caller-supplied negative
      // step must not reverse which arrow key increases the value.
      const delta = Math.abs(step);
      switch (event.key) {
        case "ArrowRight":
        case "ArrowUp":
          event.preventDefault();
          setCurrentValue((prev) => snap(prev + delta));
          break;
        case "ArrowLeft":
        case "ArrowDown":
          event.preventDefault();
          setCurrentValue((prev) => snap(prev - delta));
          break;
        case "PageUp":
          event.preventDefault();
          setCurrentValue((prev) => snap(prev + delta * 10));
          break;
        case "PageDown":
          event.preventDefault();
          setCurrentValue((prev) => snap(prev - delta * 10));
          break;
        case "Home":
          event.preventDefault();
          setCurrentValue(effectiveInnerMin);
          break;
        case "End":
          event.preventDefault();
          setCurrentValue(effectiveInnerMax);
          break;
      }
    },
    [
      disabled,
      effectiveInnerMin,
      effectiveInnerMax,
      setCurrentValue,
      snap,
      step,
    ],
  );

  const marks = useMemo(() => {
    if (!markers && !markerLabels) return [];
    if (step <= 0 || max <= min) return [];
    // `Math.round` (not `Math.floor`) absorbs float dust in (max-min)/step
    // (e.g. 0.3/0.1 -> 2.9999999999999996, which must count as 3).
    const realCount = Math.round((max - min) / step);
    // Past MAX_MARKERS, evenly resample across the full range instead of
    // rendering only the first MAX_MARKERS real step-ticks — otherwise a tiny
    // step over a wide range clusters every rendered tick near `min`.
    const count = Math.min(realCount, MAX_MARKERS);
    const tickStep = (max - min) / count;
    const out: { value: number; ratio: number }[] = [];
    for (let i = 0; i <= count; i++) {
      const v = i === count ? max : preciseRound(min + i * tickStep);
      out.push({ value: v, ratio: ratioOf(v) });
    }
    return out;
  }, [markers, markerLabels, step, min, max, ratioOf]);

  // A controlling parent owns `currentValue` and may pass one outside the
  // inner range (e.g. set before `innerMin`/`innerMax` were added) — clamp
  // only for display so `aria-valuenow` and the thumb never report/render
  // outside the declared bounds, without calling `onValueChange` ourselves.
  const displayValue = clamp(
    currentValue,
    effectiveInnerMin,
    effectiveInnerMax,
  );
  const valueRatio = ratioOf(displayValue);
  const innerMinRatio = ratioOf(effectiveInnerMin);
  const innerMaxRatio = ratioOf(effectiveInnerMax);

  return (
    <div
      className={clsx(
        styles["elm-slider"],
        isVertical && styles.vertical,
        disabled && styles.disabled,
        className,
      )}
      style={
        {
          "--elmethis-scoped-value-ratio": valueRatio,
          "--elmethis-scoped-inner-min-ratio": innerMinRatio,
          "--elmethis-scoped-inner-max-ratio": innerMaxRatio,
          ...style,
        } as CSSProperties
      }
    >
      <div
        // `rest` (aria-label, id, data-*, ...) belongs on the interactive
        // element itself, not this layout wrapper — this component IS a
        // slider, unlike e.g. ElmAudioPlayer where the root is a larger
        // widget and the `role="slider"` seek bar is just one control in it.
        {...rest}
        ref={trackRef}
        className={styles.track}
        role="slider"
        tabIndex={disabled ? -1 : 0}
        aria-orientation={orientation}
        aria-valuemin={effectiveInnerMin}
        aria-valuemax={effectiveInnerMax}
        aria-valuenow={displayValue}
        aria-disabled={disabled || undefined}
        onPointerDown={handlePointerDown}
        onPointerMove={handlePointerMove}
        onKeyDown={handleKeyDown}
      >
        <div className={styles.rail} aria-hidden="true">
          <div className={styles["restricted-start"]} />
          <div className={styles.fill} />
          <div className={styles["restricted-end"]} />
        </div>

        {marks.length > 0 && (
          <div className={styles.marks} aria-hidden="true">
            {marks.map((mark) => (
              <span
                key={mark.value}
                className={clsx(
                  styles.mark,
                  (mark.value < effectiveInnerMin ||
                    mark.value > effectiveInnerMax) &&
                    styles["mark-restricted"],
                )}
                style={
                  {
                    "--elmethis-scoped-marker-ratio": mark.ratio,
                  } as CSSProperties
                }
              >
                {markers && <i className={styles.tick} />}
                {markerLabels && (
                  <span className={styles["mark-label"]}>
                    {formatMarkerLabel?.(mark.value) ?? mark.value}
                  </span>
                )}
              </span>
            ))}
          </div>
        )}

        <span className={styles.thumb} aria-hidden="true" />
      </div>
    </div>
  );
};
