// packages/vue/src/components/form/elm-button.tsx
import {
  defineComponent,
  type CSSProperties,
  type HTMLAttributes,
  type StyleValue,
} from "vue";
import { clsx } from "clsx";

import { ElmDotLoadingIcon } from "../icon/elm-dot-loading-icon";
import styles from "./elm-button.module.css";

export interface ElmButtonProps extends HTMLAttributes {
  /**
   * Whether the button is in loading state.
   */
  isLoading?: boolean;

  /**
   * Whether the button is block.
   */
  block?: boolean;

  color?: string;

  /**
   * Whether the button is primary.
   */
  primary?: boolean;

  /**
   * Whether the button is disabled.
   */
  disabled?: boolean;
}

export const ElmButton = defineComponent({
  name: "ElmButton",
  // The consumer's `onClick` is intercepted for the loading/disabled guard,
  // so attrs are split manually instead of falling through.
  inheritAttrs: false,
  props: {
    isLoading: { type: Boolean, default: false },
    block: { type: Boolean, default: false },
    color: { type: String, default: undefined },
    primary: { type: Boolean, default: false },
    disabled: { type: Boolean, default: undefined },
  },
  setup(props, { attrs, slots }) {
    return () => {
      const {
        class: className,
        style,
        onClick,
        ...rest
      } = attrs as Record<string, unknown>;

      const handleClick = (event: MouseEvent): void => {
        if (!props.isLoading && !props.disabled) {
          if (typeof onClick === "function") {
            (onClick as (event: MouseEvent) => void)(event);
          }
        }
      };

      return (
        <button
          onClick={handleClick}
          disabled={props.disabled}
          class={clsx(
            styles["elm-button"],
            !props.isLoading && !props.disabled && styles.enable,
            props.color && styles.colored,
            !props.color && !props.primary && styles.normal,
            !props.color && props.primary && styles.primary,
            className as string | undefined,
          )}
          style={
            [
              {
                display: props.block ? "flex" : "inline-flex",
                width: props.block ? "100%" : "auto",
                cursor: props.disabled
                  ? "not-allowed"
                  : props.isLoading
                    ? "progress"
                    : "pointer",
                "--elmethis-scoped-opacity":
                  props.disabled || props.isLoading ? 0.6 : undefined,
                "--elmethis-scoped-color": props.color,
              } as CSSProperties,
              style as StyleValue,
            ] as StyleValue
          }
          {...rest}
        >
          {props.isLoading ? (
            <ElmDotLoadingIcon size="1.5rem" />
          ) : (
            <span class={styles.flex}>{slots.default?.()}</span>
          )}
        </button>
      );
    };
  },
});

// packages/react/src/components/form/elm-button.tsx
import type {
  ComponentPropsWithoutRef,
  CSSProperties,
  MouseEvent,
} from "react";
import { clsx } from "clsx";

import { ElmDotLoadingIcon } from "../icon/elm-dot-loading-icon";
import styles from "./elm-button.module.css";

export interface ElmButtonProps extends ComponentPropsWithoutRef<"button"> {
  /**
   * Whether the button is in loading state.
   */
  isLoading?: boolean;

  /**
   * Whether the button is block.
   */
  block?: boolean;

  color?: string;

  /**
   * Whether the button is primary.
   */
  primary?: boolean;
}

export const ElmButton = ({
  className,
  style,
  onClick,
  isLoading,
  block,
  color,
  primary,
  disabled,
  children,
  ...props
}: ElmButtonProps) => {
  const handleClick = (event: MouseEvent<HTMLButtonElement>) => {
    if (!isLoading && !disabled) {
      if (onClick) {
        onClick(event);
      }
    }
  };

  return (
    <button
      onClick={handleClick}
      disabled={disabled}
      className={clsx(
        styles["elm-button"],
        !isLoading && !disabled && styles.enable,
        color && styles.colored,
        !color && !primary && styles.normal,
        !color && primary && styles.primary,
        className,
      )}
      style={
        {
          display: block ? "flex" : "inline-flex",
          width: block ? "100%" : "auto",
          cursor: disabled ? "not-allowed" : isLoading ? "progress" : "pointer",
          "--elmethis-scoped-opacity": disabled || isLoading ? 0.6 : undefined,
          "--elmethis-scoped-color": color,
          ...style,
        } as CSSProperties
      }
      {...props}
    >
      {isLoading ? (
        <ElmDotLoadingIcon size="1.5rem" />
      ) : (
        <span className={styles.flex}>{children}</span>
      )}
    </button>
  );
};
