// packages/qwik/src/components/form/elm-switch.tsx
import {
  $,
  component$,
  useSignal,
  type CSSProperties,
  type Signal,
} from "@builder.io/qwik";

import styles from "./elm-switch.module.scss";

export interface ElmSwitchProps {
  class?: string;

  style?: CSSProperties;

  /**
   * The color of the switch when checked.
   */
  color?: string;

  /**
   * The size of the switch.
   */
  size?: string;

  /**
   * Whether the switch is disabled.
   */
  disabled?: boolean;

  /**
   * Checked state.
   */
  checked?: Signal<boolean>;
}

export const ElmSwitch = component$<ElmSwitchProps>((props) => {
  const color = props.color ?? "#bfa056";
  const size = props.size ?? "18px";

  const internalChecked = useSignal(false);
  const checked = props.checked ?? internalChecked;

  const handleClick = $(() => {
    if (!props.disabled) {
      checked.value = !checked.value;
    }
  });

  return (
    <div
      onClick$={handleClick}
      class={props.class}
      style={{
        "--color": color,
        "--padding": "2px",
        "--size": size,
        "--width": "calc(var(--size) * 2 + var(--padding) * 2)",
        ...props.style,
      }}
    >
      <input
        class={styles.switch}
        type="checkbox"
        checked={checked.value}
        disabled={props.disabled}
      />
      <div
        class={[
          styles.bar,
          checked.value && styles["bar--checked"],
          props.disabled && styles["bar--disabled"],
        ]}
      >
        <div
          class={[
            styles.circle,
            checked.value && styles["circle--checked"],
            props.disabled && styles["circle--disabled"],
          ]}
        ></div>
      </div>
    </div>
  );
});

// packages/react/src/components/form/ElmSwitch.tsx
import React, { useCallback } from "react";

import "@styles/global.css";
import styles from "./ElmSwitch.module.css";

export interface ElmSwitchCSSVariables {
  "--color"?: string;
  "--padding"?: string;
  "--size"?: string;
  "--width"?: string;
}

export interface ElmSwitchProps {
  style?: React.CSSProperties & ElmSwitchCSSVariables;

  /** The color of the switch when checked. */
  color?: string;

  /** The size of the switch. */
  size?: React.CSSProperties["width"];

  /** Whether the switch is checked. */
  checked?: boolean;

  /** Whether the switch is disabled. */
  disabled?: boolean;

  /** Called when the checked state changes. */
  onChange?: (checked: boolean) => void;
}

export const ElmSwitch = ({
  color = "#bfa056",
  size = "18px",
  disabled = false,
  checked = false,
  ...props
}: ElmSwitchProps) => {
  const { onChange } = props;

  const handleClick = useCallback(() => {
    if (!disabled && onChange) {
      onChange(!checked);
    }
  }, [disabled, checked, onChange]);

  const barClass = [
    styles.bar,
    checked ? styles["bar-checked"] : "",
    disabled ? styles["bar-disabled"] : "",
  ]
    .filter(Boolean)
    .join(" ");

  const circleClass = [
    styles.circle,
    checked ? styles["circle-checked"] : "",
    disabled ? styles["circle-disabled"] : "",
  ]
    .filter(Boolean)
    .join(" ");

  return (
    <div
      onClick={handleClick}
      style={
        {
          "--color": color,
          "--padding": "2px",
          "--size": size,
          "--width": `calc(${size} * 2 + 2px * 2)`,
          ...props.style,
        } as React.CSSProperties
      }
    >
      <input
        className={styles.switch}
        type="checkbox"
        checked={checked}
        disabled={disabled}
        readOnly
      />
      <div className={barClass}>
        <div className={circleClass}></div>
      </div>
    </div>
  );
};
