// packages/vue/src/components/media/elm-block-image.tsx
import { defineComponent, h, type HTMLAttributes, type PropType } from "vue";
import { clsx } from "clsx";
import { mdiMessageImageOutline } from "@mdi/js";

import styles from "./elm-block-image.module.css";
import { ElmInlineText } from "../typography/elm-inline-text";
import { ElmMdiIcon } from "../icon/elm-mdi-icon";
import { useModal } from "../../hooks/use-modal";

export interface ElmBlockImageProps extends HTMLAttributes {
  /**
   * Image source URL
   */
  src: string;

  srcSet?: string;

  sizes?: string;

  /**
   * Image alt text
   */
  alt?: string;

  enableModal?: boolean;

  caption?: string;

  width?: number | `${number}`;

  height?: number | `${number}`;
}

export const ElmBlockImage = defineComponent({
  name: "ElmBlockImage",
  props: {
    src: { type: String, required: true },
    srcSet: { type: String, default: undefined },
    sizes: { type: String, default: undefined },
    alt: { type: String, default: undefined },
    enableModal: { type: Boolean, default: undefined },
    caption: { type: String, default: undefined },
    width: {
      type: [Number, String] as PropType<number | `${number}`>,
      default: undefined,
    },
    height: {
      type: [Number, String] as PropType<number | `${number}`>,
      default: undefined,
    },
  },
  setup(props) {
    // The lightbox is a `useModal` instance: `isOpen` drives the zoom cursor,
    // `show`/`hide` open and close it, and `Modal` renders the native <dialog>.
    const {
      Modal: ImageModal,
      isOpen: isModalOpen,
      show: showModal,
      hide: hideModal,
    } = useModal();

    const handleOpenModal = (): void => {
      if (props.enableModal ?? true) {
        showModal();
      }
    };

    const modalEnabled = () => props.enableModal ?? true;

    const renderImage = (isModal: boolean) => (
      <img
        class={styles.image}
        src={props.src}
        alt={props.alt ?? props.caption ?? "Image"}
        srcset={isModal ? undefined : props.srcSet}
        sizes={isModal ? undefined : props.sizes}
        width={props.width}
        height={props.height}
        loading={isModal ? "lazy" : undefined}
        onClick={isModal ? () => hideModal() : undefined}
        style={{
          "--elmethis-scoped-cursor": modalEnabled()
            ? isModalOpen.value
              ? "zoom-out"
              : "zoom-in"
            : "default",
          "--elmethis-scoped-aspect-ratio":
            props.width && props.height
              ? `${props.width} / ${props.height}`
              : "auto",
        }}
        {...{ fetchpriority: isModal ? "low" : "auto" }}
      />
    );

    // inheritAttrs default: passthrough class/style merge onto the root figure.
    return () => (
      <figure class={clsx(styles["elm-block-image"])}>
        <div class={styles["image-container"]} onClick={handleOpenModal}>
          {renderImage(false)}
        </div>

        {props.caption && (
          <figcaption class={styles["caption-box"]}>
            <span class={styles["caption-icon"]}>
              <ElmMdiIcon path={mdiMessageImageOutline} size="1.25rem" />
            </span>
            <ElmInlineText size="1rem">{props.caption}</ElmInlineText>
          </figcaption>
        )}

        {/* Render the enlarged image only while open so it stays lazy. */}
        {h(ImageModal, null, {
          default: () => (isModalOpen.value ? renderImage(true) : null),
        })}
      </figure>
    );
  },
});

// packages/solid/src/components/media/elm-block-image.tsx
import { mergeProps, Show, splitProps, type JSX } from "solid-js";
import { clsx } from "clsx";
import { mdiMessageImageOutline } from "@mdi/js";

import { createModal } from "../../primitives/create-modal";
import { ElmMdiIcon } from "../icon/elm-mdi-icon";
import { ElmInlineText } from "../typography/elm-inline-text";
import styles from "./elm-block-image.module.css";

export interface ElmBlockImageProps extends JSX.HTMLAttributes<HTMLElement> {
  /** Image source URL. */
  src: string;
  srcSet?: string;
  sizes?: string;
  /** Image alt text. */
  alt?: string;
  enableModal?: boolean;
  caption?: string;
  width?: number | `${number}`;
  height?: number | `${number}`;
}

export const ElmBlockImage = (props: ElmBlockImageProps) => {
  const merged = mergeProps({ enableModal: true }, props);
  const [local, rest] = splitProps(merged, [
    "class",
    "children",
    "src",
    "srcSet",
    "sizes",
    "alt",
    "enableModal",
    "caption",
    "width",
    "height",
  ]);
  const { Modal: ImageModal, isOpen, show, hide } = createModal();

  const openModal = () => {
    if (local.enableModal) {
      show();
    }
  };

  const image = (isModal: boolean) => (
    <img
      class={styles.image}
      src={local.src}
      alt={local.alt ?? local.caption ?? "Image"}
      srcset={isModal ? undefined : local.srcSet}
      sizes={isModal ? undefined : local.sizes}
      width={local.width}
      height={local.height}
      loading={isModal ? "lazy" : undefined}
      fetchpriority={isModal ? "low" : "auto"}
      onClick={isModal ? hide : undefined}
      style={{
        "--elmethis-scoped-cursor": local.enableModal
          ? isOpen()
            ? "zoom-out"
            : "zoom-in"
          : "default",
        "--elmethis-scoped-aspect-ratio":
          local.width && local.height
            ? `${local.width} / ${local.height}`
            : "auto",
      }}
    />
  );

  return (
    <figure {...rest} class={clsx(styles["elm-block-image"], local.class)}>
      <div class={styles["image-container"]} onClick={openModal}>
        {image(false)}
      </div>

      <Show when={local.caption}>
        {(caption) => (
          <figcaption class={styles["caption-box"]}>
            <span class={styles["caption-icon"]}>
              <ElmMdiIcon path={mdiMessageImageOutline} size="1.25rem" />
            </span>
            <ElmInlineText size="1rem">{caption()}</ElmInlineText>
          </figcaption>
        )}
      </Show>

      <ImageModal>{isOpen() && image(true)}</ImageModal>
    </figure>
  );
};
