// packages/react/src/components/typography/ElmFragmentIdentifier.tsx
import React, { useCallback } from "react";

import "@styles/global.css";
import styles from "./ElmFragmentIdentifier.module.css";

export interface ElmFragmentIdentifierCSSVariables {}

export interface ElmFragmentIdentifierProps {
  style?: React.CSSProperties & ElmFragmentIdentifierCSSVariables;

  /**
   * ID of the heading element.
   */
  id: string;
}

export const ElmFragmentIdentifier = (props: ElmFragmentIdentifierProps) => {
  const handleHashClick = useCallback(
    (id: string) => {
      const url = new URL(window.location.href);
      url.hash = id;
      window.history.replaceState(null, "", url.toString());

      const target = document.getElementById(id);
      if (target != null) {
        target.scrollIntoView({ behavior: "smooth" });
      }
    },
    [],
  );

  return (
    <span
      className={styles.fragment}
      style={props.style}
      onClick={() => handleHashClick(props.id)}
    >
      #
    </span>
  );
};

// packages/qwik/src/components/typography/elm-fragment-identifier.tsx
import { $, component$, type CSSProperties } from "@builder.io/qwik";

import styles from "./elm-fragment-identifier.module.css";

export interface ElmFragmentIdentifierProps {
  class?: string;

  style?: CSSProperties;

  /**
   * ID of the heading element.
   */
  id: string;
}

export const ElmFragmentIdentifier = component$<ElmFragmentIdentifierProps>(
  ({ class: className, style, id }) => {
    const handleHashClick = $((id: string) => {
      const url = new URL(window.location.href);
      url.hash = id;
      window.history.replaceState(null, "", url.toString());

      const target = document.getElementById(id);
      if (target != null) {
        target.scrollIntoView({ behavior: "smooth" });
      }
    });

    return (
      <span
        class={[styles.fragment, className]}
        style={style}
        onClick$={() => handleHashClick(id)}
      >
        #
      </span>
    );
  },
);
