// packages/react/src/components/typography/elm-block-quote.tsx
import type { ComponentPropsWithoutRef } from "react";
import { clsx } from "clsx";
import { mdiFormatQuoteClose, mdiFormatQuoteOpen } from "@mdi/js";

import styles from "./elm-block-quote.module.css";
import textStyles from "../../styles/text.module.css";
import { ElmMdiIcon } from "../icon/elm-mdi-icon";

export interface ElmBlockQuoteProps extends ComponentPropsWithoutRef<"blockquote"> {}

export const ElmBlockQuote = ({
  className,
  children,
  ...props
}: ElmBlockQuoteProps) => {
  return (
    <blockquote
      className={clsx(styles["elm-block-quote"], textStyles.text, className)}
      {...props}
    >
      <div className={clsx(styles.icon, styles["icon-top-left"])}>
        <ElmMdiIcon path={mdiFormatQuoteOpen} />
      </div>

      <div className={styles.body}>{children}</div>

      <div className={clsx(styles.icon, styles["icon-bottom-right"])}>
        <ElmMdiIcon path={mdiFormatQuoteClose} />
      </div>
    </blockquote>
  );
};

// packages/qwik/src/components/typography/elm-block-quote.tsx
import { component$, PropsOf, Slot } from "@qwik.dev/core";

import styles from "./elm-block-quote.module.css";
import textStyles from "../../styles/text.module.css";
import { ElmMdiIcon } from "../icon/elm-mdi-icon";
import { mdiFormatQuoteClose, mdiFormatQuoteOpen } from "@mdi/js";

export type ElmBlockQuoteProps = PropsOf<"blockquote">;

export const ElmBlockQuote = component$<PropsOf<"blockquote">>(
  ({ class: className, ...props }) => {
    return (
      <blockquote
        class={[styles["elm-block-quote"], textStyles.text, className]}
        {...props}
      >
        <div class={[styles.icon, styles["icon-top-left"]]}>
          <ElmMdiIcon path={mdiFormatQuoteOpen} />
        </div>

        <div class={styles.body}>
          <Slot />
        </div>

        <div class={[styles.icon, styles["icon-bottom-right"]]}>
          <ElmMdiIcon path={mdiFormatQuoteClose} />
        </div>
      </blockquote>
    );
  },
);
