// packages/react/src/components/typography/elm-callout.tsx
import type { ComponentPropsWithoutRef } from "react";
import { clsx } from "clsx";

import styles from "./elm-callout.module.css";
import {
  mdiAlert,
  mdiAlertOctagram,
  mdiInformation,
  mdiLightbulbOn,
  mdiShieldAlert,
} from "@mdi/js";
import { ElmMdiIcon } from "../icon/elm-mdi-icon";

export type AlertType = "note" | "tip" | "important" | "warning" | "caution";

const ICON_MAP: Record<AlertType, string> = Object.freeze({
  note: mdiInformation,
  tip: mdiLightbulbOn,
  important: mdiShieldAlert,
  warning: mdiAlert,
  caution: mdiAlertOctagram,
} as const);

export interface ElmCalloutProps extends ComponentPropsWithoutRef<"aside"> {
  /**
   * Type of alert
   */
  type?: AlertType;
}

export const ElmCallout = ({
  className,
  type = "note",
  style,
  children,
  ...props
}: ElmCalloutProps) => {
  return (
    <aside
      className={clsx(styles["elm-callout"], styles[type], className)}
      style={style}
      {...props}
    >
      <div className={styles.header}>
        <ElmMdiIcon
          className={styles.icon}
          path={ICON_MAP[type]}
          size="1.25rem"
        />
        <span>{type}</span>
      </div>

      <div className={styles.content}>{children}</div>
    </aside>
  );
};

// packages/qwik/src/components/typography/elm-callout.tsx
import { component$, PropsOf, Slot } from "@qwik.dev/core";

import styles from "./elm-callout.module.css";
import {
  mdiAlert,
  mdiAlertOctagram,
  mdiInformation,
  mdiLightbulbOn,
  mdiShieldAlert,
} from "@mdi/js";
import { ElmMdiIcon } from "../icon/elm-mdi-icon";

export type AlertType = "note" | "tip" | "important" | "warning" | "caution";

const ICON_MAP: Record<AlertType, string> = Object.freeze({
  note: mdiInformation,
  tip: mdiLightbulbOn,
  important: mdiShieldAlert,
  warning: mdiAlert,
  caution: mdiAlertOctagram,
} as const);

export interface ElmCalloutProps extends PropsOf<"aside"> {
  /**
   * Type of alert
   */
  type?: AlertType;
}

export const ElmCallout = component$<ElmCalloutProps>(
  ({ class: className, type = "note", style, ...props }) => {
    return (
      <aside
        class={[styles["elm-callout"], styles[type], className]}
        style={style}
        {...props}
      >
        <div class={styles.header}>
          <ElmMdiIcon
            class={styles.icon}
            path={ICON_MAP[type]}
            size="1.25rem"
          />
          <span>{type}</span>
        </div>

        <div class={styles.content}>
          <Slot />
        </div>
      </aside>
    );
  },
);
