// packages/react/src/components/typography/elm-divider.tsx
import type { ComponentPropsWithoutRef } from "react";
import { clsx } from "clsx";

import styles from "./elm-divider.module.css";

export type ElmDividerProps = ComponentPropsWithoutRef<"hr">;

export const ElmDivider = ({ className, ...props }: ElmDividerProps) => {
  return <hr className={clsx(styles["elm-divider"], className)} {...props} />;
};

// packages/qwik/src/components/typography/elm-divider.tsx
import { component$, CSSProperties } from "@builder.io/qwik";

import styles from "./elm-divider.module.css";

export type ElmDividerProps = {
  class?: string;

  style?: CSSProperties;
};

export const ElmDivider = component$<ElmDividerProps>(
  ({ class: className, style }) => {
    return <hr class={[styles.hr, className]} style={style} />;
  },
);
