// packages/react/src/components/typography/elm-list.tsx
import type { ComponentPropsWithoutRef } from "react";
import { clsx } from "clsx";

import styles from "./elm-list.module.css";
import textStyles from "../../styles/text.module.css";

export interface ElmListProps extends Omit<
  ComponentPropsWithoutRef<"ul">,
  "type"
> {
  listStyle?: "unordered" | "ordered";
  type?: "a" | "i" | "1" | "A" | "I";
}

export const ElmList = ({
  className,
  listStyle = "unordered",
  children,
  ...props
}: ElmListProps) => {
  if (listStyle === "ordered") {
    return (
      <ol
        className={clsx(
          textStyles.text,
          styles["elm-list"],
          styles.numbered,
          className,
        )}
        {...props}
      >
        {children}
      </ol>
    );
  }

  return (
    <ul
      className={clsx(
        textStyles.text,
        styles["elm-list"],
        styles.bulleted,
        className,
      )}
      {...props}
    >
      {children}
    </ul>
  );
};

// packages/qwik/src/components/typography/elm-list.tsx
import { component$, CSSProperties, PropsOf, Slot } from "@qwik.dev/core";

import styles from "./elm-list.module.css";

import textStyle from "../../styles/text.module.css";

export interface ElmListProps extends Omit<PropsOf<"ul">, "type"> {
  class?: string;

  listStyle: "unordered" | "ordered";
  style?: CSSProperties;
  type?: "a" | "i" | "1" | "A" | "I";
}

export const ElmList = component$<ElmListProps>(
  ({ class: className, listStyle = "unordered", style, ...props }) => {
    if (listStyle === "ordered") {
      return (
        <ol
          class={[
            textStyle.text,
            styles["elm-list"],
            styles.numbered,
            className,
          ]}
          style={style}
          {...props}
        >
          <Slot />
        </ol>
      );
    } else {
      return (
        <ul
          class={[
            textStyle.text,
            styles["elm-list"],
            styles.bulleted,
            className,
          ]}
          style={style}
          {...props}
        >
          <Slot />
        </ul>
      );
    }
  },
);
