// packages/react/src/components/typography/ElmInlineText.tsx
import { type ComponentProps, type CSSProperties } from "react";

import textStyle from "../../styles/text.module.scss";
import style from "./ElmInlineText.module.scss";
import { clsx } from "clsx";

export interface ElmTextProps extends ComponentProps<"span"> {
  /**
   * The text to display.
   */
  text?: string;

  /**
   * Specifies the color of the text.
   *
   * e.g.) `'red'`, `'#ff0000'`, `'rgba(255, 0, 0, 0.5)'`
   */
  color?: CSSProperties["color"];

  /**
   * Specifies the font size of the text.
   */
  size?: CSSProperties["fontSize"];

  /**
   * Specifies whether the text should be bold.
   */
  bold?: boolean;

  /**
   * Specifies whether the text should be italic.
   */
  italic?: boolean;

  /**
   * Specifies whether the text should be underlined.
   */
  underline?: boolean;

  /**
   * Specifies whether the text should be strikethrough.
   */
  strikethrough?: boolean;

  /**
   * Specifies whether the text should be displayed as code.
   */
  code?: boolean;

  kbd?: boolean;

  /**
   * Specifies the background color of the text.
   */
  backgroundColor?: CSSProperties["backgroundColor"];

  /**
   * The ruby text to display.
   */
  ruby?: string;

  /**
   * The URL to navigate to.
   *
   * e.g. `https://example.com`
   */
  href?: string;

  favicon?: string;
}

const ElmInlineText = (props: ElmTextProps) => {
  const render = () => {
    if (props.href) {
      return <></>;
    } else {
      const classes = [];

      if (props.underline) classes.push(style.underline);

      let component = (
        <span
          className={clsx([textStyle.text].concat(classes))}
          style={{ "--color": props.color } as CSSProperties}
        >
          {props.text || props.children}
        </span>
      );

      if (props.bold) component = <strong>{component}</strong>;
      if (props.italic) component = <em>{component}</em>;
      if (props.strikethrough) component = <del>{component}</del>;
      if (props.code) component = <code>{component}</code>;

      return component;
    }
  };

  return render();
};

export default ElmInlineText;

// packages/qwik/src/components/typography/elm-inline-text.tsx
import { component$, Slot, type CSSProperties } from "@builder.io/qwik";

import styles from "./elm-inline-text.module.scss";
import textStyles from "../../styles/text.module.scss";

import { ElmInlineIcon } from "../icon/elm-inline-icon";

export interface ElmInlineTextProps {
  style?: CSSProperties;

  /**
   * The text to display.
   */
  text?: string;

  /**
   * Specifies the color of the text.
   *
   * e.g.) `'red'`, `'#ff0000'`, `'rgba(255, 0, 0, 0.5)'`
   */
  color?: CSSProperties["color"];

  /**
   * Specifies the font size of the text.
   */
  size?: CSSProperties["fontSize"];

  /**
   * Specifies whether the text should be bold.
   */
  bold?: boolean;

  /**
   * Specifies whether the text should be italic.
   */
  italic?: boolean;

  /**
   * Specifies whether the text should be underlined.
   */
  underline?: boolean;

  /**
   * Specifies whether the text should be strikethrough.
   */
  strikethrough?: boolean;

  /**
   * Specifies whether the text should be displayed as code.
   */
  code?: boolean;

  kbd?: boolean;

  /**
   * Specifies the background color of the text.
   */
  backgroundColor?: CSSProperties["backgroundColor"];

  /**
   * The ruby text to display.
   */
  ruby?: string;

  /**
   * The URL to navigate to.
   *
   * e.g. `https://example.com`
   */
  href?: string;

  favicon?: string;
}

export const ElmInlineText = component$<ElmInlineTextProps>((props) => {
  const {
    bold = false,
    italic = false,
    underline = false,
    strikethrough = false,
    code = false,
    size = "1em",
  } = props;

  let vnode = props.text ? <span>{props.text}</span> : <Slot />;

  if (props.kbd) {
    vnode = <kbd class={styles.kbd}>{vnode}</kbd>;
  }

  if (strikethrough) {
    vnode = <del>{vnode}</del>;
  }

  if (italic) {
    vnode = <em>{vnode}</em>;
  }

  if (underline) {
    vnode = <ins>{vnode}</ins>;
  }

  if (bold) {
    vnode = <strong>{vnode}</strong>;
  }

  if (code) {
    vnode = <code class={styles.code}>{vnode}</code>;
  }

  if (props.ruby) {
    vnode = (
      <ruby class={styles.text}>
        <span>{vnode}</span>
        <rt>{props.ruby}</rt>
      </ruby>
    );
  }

  const wrappedVnode = (
    <span
      class={[styles.text, textStyles.text]}
      style={{
        "--color": props.color,
        "--font-size": size,
        "--background-color": props.backgroundColor,
        ...props.style,
      }}
    >
      {vnode}
    </span>
  );

  if (props.href) {
    return (
      <a
        class={styles.link}
        href={props.href}
        style={{ "--font-size": size }}
        target="_blank"
        rel="noopener noreferrer"
      >
        {props.favicon && <ElmInlineIcon src={props.favicon} />}
        {wrappedVnode}
      </a>
    );
  }

  return wrappedVnode;
});
