// packages/react/src/components/typography/elm-paragraph.tsx
import type { ComponentPropsWithoutRef, CSSProperties } from "react";
import { clsx } from "clsx";

import styles from "./elm-paragraph.module.css";
import textStyles from "../../styles/text.module.css";

export interface ElmParagraphProps extends ComponentPropsWithoutRef<"p"> {
  color?: string;

  backgroundColor?: string;
}

export const ElmParagraph = ({
  className,
  style,
  color,
  backgroundColor,
  children,
  ...props
}: ElmParagraphProps) => {
  return (
    <p
      className={clsx(styles["elm-paragraph"], textStyles.text, className)}
      style={
        {
          ...style,
          "--elmethis-scoped-color": color,
          "--elmethis-scoped-background-color": backgroundColor,
        } as CSSProperties
      }
      {...props}
    >
      {children}
    </p>
  );
};

// packages/qwik/src/components/typography/elm-paragraph.tsx
import { type CSSProperties, component$, Slot } from "@builder.io/qwik";

import styles from "./elm-paragraph.module.css";
import textStyles from "../../styles/text.module.css";

export interface ElmParagraphProps {
  class?: string;

  style?: CSSProperties;

  color?: string;

  backgroundColor?: string;
}

export const ElmParagraph = component$<ElmParagraphProps>(
  ({ class: className, style, color, backgroundColor }) => {
    return (
      <p
        class={[styles.paragraph, textStyles.text, className]}
        style={{
          ...style,
          "--color": color,
          "--background-color": backgroundColor,
        }}
      >
        <Slot />
      </p>
    );
  },
);
