// packages/react/src/components/fallback/ElmSpinner.tsx
import React from "react";

import "@styles/global.css";
import styles from "./ElmSpinner.module.css";

export interface ElmSpinnerCSSVariables {}

export interface ElmSpinnerProps {
  style?: React.CSSProperties & ElmSpinnerCSSVariables;

  className?: string;

  /**
   * Specifies the radius of the spinner circle.
   */
  radius?: number;

  /**
   * Specifies the stroke width of the spinner circle.
   */
  weight?: number;
}

export const ElmSpinner = (props: ElmSpinnerProps) => {
  const { radius = 16, weight = 2, style } = props;

  return (
    <svg
      className={props.className}
      height={radius * 2}
      width={radius * 2}
      style={style}
    >
      <circle
        className={styles.circle}
        cx={radius}
        cy={radius}
        r={radius - weight}
        fill="transparent"
        strokeWidth={weight}
      />
    </svg>
  );
};

// packages/core/src/components/fallback/ElmSpinner.vue
<template>
  <svg :height="radius * 2" :width="radius * 2">
    <circle
      :class="$style.circle"
      :cx="radius"
      :cy="radius"
      :r="radius - weight"
      fill="transparent"
      :strokeWidth="weight"
    />
  </svg>
</template>

<script setup lang="ts">
export interface ElmSpinnerProps {
  radius?: number;
  weight?: number;
}

withDefaults(defineProps<ElmSpinnerProps>(), {
  radius: 16,
  weight: 2,
});
</script>

<style module lang="scss">
@keyframes draw-line {
  0% {
    stroke-dashoffset: 0%;
  }
  100% {
    stroke-dashoffset: 400%;
  }
}

@keyframes rotate {
  0% {
    transform: rotate(180deg);
  }
  100% {
    transform: rotate(-180deg);
  }
}

.circle {
  stroke-dasharray: 200%;
  animation:
    draw-line 1200ms infinite ease-in-out,
    rotate 1200ms infinite linear;
  transform-origin: center;

  stroke: #555b67;
  [data-theme="dark"] & {
    stroke: #b0b5be;
  }
}
</style>
