// packages/core/src/components/data/ElmProgress.vue
<template>
  <progress :class="$style.progress" />

  <div
    :class="$style.container"
    :style="{
      '--weight': weight,
      '--border-radius': round ? 'calc(var(--weight) / 2)' : undefined,
      '--color': color
    }"
  >
    <div
      :class="$style.value"
      :style="{
        '--scale-x': `scaleX(${value / max})`
      }"
    ></div>

    <div
      :class="$style.buffer"
      :style="{
        '--scale-x': `scaleX(${buffer != null ? buffer / max : value / max})`
      }"
    ></div>
  </div>
</template>

<script setup lang="ts">
import type { Property } from 'csstype'

export interface ElmProgressProps {
  /**
   * The current value of the progress.
   */
  value: number

  /**
   * The buffer value of the progress.
   */
  buffer?: number

  /**
   * The maximum value of the progress.
   */
  max?: number

  /**
   * The weight of the progress.
   */
  weight: Property.Height<string | number>

  /**
   * Whether the progress should be round.
   */
  round?: boolean

  /**
   * The color of the progress.
   */
  color?: string
}

withDefaults(defineProps<ElmProgressProps>(), {
  max: 100,
  weight: '4px',
  round: true
})
</script>

<style module lang="scss">
@mixin bar($transition-duration: 800ms) {
  position: absolute;
  content: '';
  width: 100%;
  height: 100%;
  transition: transform $transition-duration;
  transform: var(--scale-x, scaleX(0));
  transform-origin: left;
  background-color: var(--color, rgba(black, 0.8));
  [data-theme='dark'] & {
    background-color: var(--color, rgba(white, 0.8));
  }
}

.progress {
  display: none;
}

.container {
  width: 100%;
  height: var(--weight);
  position: relative;
  border-radius: var(--border-radius);
  overflow: hidden;

  background-color: rgba(black, 0.1);
  [data-theme='dark'] & {
    background-color: rgba(white, 0.1);
  }

  .value {
    @include bar;
  }

  .buffer {
    @include bar(400ms);
    opacity: 0.25;
  }
}
</style>

// packages/react/src/components/data/ElmProgress.tsx
import React from "react";
import type { Property } from "csstype";

import "@styles/global.css";
import styles from "./ElmProgress.module.css";

export interface ElmProgressCSSVariables {
  "--weight"?: Property.Height<string | number>;
  "--border-radius"?: string;
  "--color"?: string;
}

export interface ElmProgressProps {
  style?: React.CSSProperties & ElmProgressCSSVariables;

  /**
   * The current value of the progress.
   */
  value: number;

  /**
   * The buffer value of the progress.
   */
  buffer?: number;

  /**
   * The maximum value of the progress.
   */
  max?: number;

  /**
   * The weight of the progress.
   */
  weight?: Property.Height<string | number>;

  /**
   * Whether the progress should be round.
   */
  round?: boolean;

  /**
   * The color of the progress.
   */
  color?: string;

  /**
   * Whether the progress is loading.
   */
  loading?: boolean;
}

export const ElmProgress = ({
  value,
  buffer,
  max = 100,
  weight = "4px",
  round = true,
  color,
  loading = false,
  style,
}: ElmProgressProps) => {
  return (
    <>
      <progress className={styles.progress} value={value} max={max} />

      <div
        className={styles.container}
        style={{
          "--weight": weight,
          "--border-radius": round
            ? "calc(var(--weight) / 2)"
            : undefined,
          "--color": color,
          ...style,
        } as React.CSSProperties}
      >
        <div
          className={styles.value}
          style={{
            "--scale-x": `scaleX(${loading ? 0 : value / max})`,
          } as React.CSSProperties}
        />

        {loading && <div className={styles.loading} />}

        <div
          className={styles.buffer}
          style={{
            "--scale-x": `scaleX(${loading ? 0 : buffer != null ? buffer / max : value / max})`,
          } as React.CSSProperties}
        />
      </div>
    </>
  );
};
