// packages/solid/src/components/table/elm-table-body.tsx
import { splitProps, type JSX } from "solid-js";

import { TableSectionContext } from "./table-context";

export type ElmTableBodyProps = JSX.HTMLAttributes<HTMLTableSectionElement>;

export const ElmTableBody = (props: ElmTableBodyProps) => {
  const [local, rest] = splitProps(props, ["children"]);

  return (
    <TableSectionContext.Provider value={() => "body"}>
      <tbody {...rest}>{local.children}</tbody>
    </TableSectionContext.Provider>
  );
};

// packages/react/src/components/table/elm-table-body.tsx
import type { ComponentPropsWithoutRef } from "react";

import { TableSectionContext } from "./table-context";

export type ElmTableBodyProps = ComponentPropsWithoutRef<"tbody">;

export const ElmTableBody = ({ children, ...props }: ElmTableBodyProps) => {
  return (
    <TableSectionContext.Provider value="body">
      <tbody {...props}>{children}</tbody>
    </TableSectionContext.Provider>
  );
};
