// packages/vue/src/components/table/elm-table-header.tsx
import { defineComponent, provide, type HTMLAttributes } from "vue";
import { clsx } from "clsx";

import styles from "./elm-table-header.module.css";
import { TableSectionContext } from "./table-context";

export type ElmTableHeaderProps = HTMLAttributes;

export const ElmTableHeader = defineComponent({
  name: "ElmTableHeader",
  setup(_, { slots }) {
    provide(TableSectionContext, "head");
    // Fallthrough class merges with the binding below.
    return () => (
      <thead class={clsx(styles["elm-table-header"])}>
        {slots.default?.()}
      </thead>
    );
  },
});

// packages/react/src/components/table/elm-table-header.tsx
import type { ComponentPropsWithoutRef } from "react";
import { clsx } from "clsx";

import styles from "./elm-table-header.module.css";
import { TableSectionContext } from "./table-context";

export type ElmTableHeaderProps = ComponentPropsWithoutRef<"thead">;

export const ElmTableHeader = ({
  className,
  children,
  ...props
}: ElmTableHeaderProps) => {
  return (
    <TableSectionContext.Provider value="head">
      <thead className={clsx(styles["elm-table-header"], className)} {...props}>
        {children}
      </thead>
    </TableSectionContext.Provider>
  );
};
