// packages/vue/src/components/table/elm-table-body.tsx
import { defineComponent, provide, type HTMLAttributes } from "vue";

import { TableSectionContext } from "./table-context";

export type ElmTableBodyProps = HTMLAttributes;

export const ElmTableBody = defineComponent({
  name: "ElmTableBody",
  setup(_, { slots }) {
    provide(TableSectionContext, "body");
    return () => <tbody>{slots.default?.()}</tbody>;
  },
});

// packages/react/src/components/table/elm-table-body.tsx
import type { ComponentPropsWithoutRef } from "react";

import { TableSectionContext } from "./table-context";

export type ElmTableBodyProps = ComponentPropsWithoutRef<"tbody">;

export const ElmTableBody = ({ children, ...props }: ElmTableBodyProps) => {
  return (
    <TableSectionContext.Provider value="body">
      <tbody {...props}>{children}</tbody>
    </TableSectionContext.Provider>
  );
};
