// packages/qwik/src/components/table/elm-table-body.tsx
import {
  component$,
  Slot,
  useContextProvider,
  type CSSProperties,
} from "@builder.io/qwik";
import { HasHeaderContext } from "./elm-table-header";

export interface ElmTableBodyProps {
  class?: string;

  style?: CSSProperties;
}

export const ElmTableBody = component$<ElmTableBodyProps>(
  ({ class: className, style }) => {
    useContextProvider(HasHeaderContext, false);

    return (
      <tbody class={className} style={style}>
        <Slot />
      </tbody>
    );
  },
);

// packages/react/src/components/table/ElmTableBody.tsx
import React from "react";

import "@styles/global.css";

import { HasHeaderContext } from "./TableContext";

export interface ElmTableBodyProps extends React.PropsWithChildren {
  style?: React.CSSProperties;

  className?: string;
}

export const ElmTableBody = ({
  children,
  style,
  className,
}: ElmTableBodyProps) => {
  return (
    <HasHeaderContext.Provider value={false}>
      <tbody className={className} style={style}>
        {children}
      </tbody>
    </HasHeaderContext.Provider>
  );
};
