// packages/vue/src/components/table/ElmTable.vue
<template>
  <table
    :class="[$style.table, textStyle.text]"
    :style="{
      '--margin-block': margin,
    }"
  >
    <caption v-if="caption != null">
      <span :class="$style['caption']">
        <span :class="$style.spacing"></span>

        <span :class="$style['caption-inner']">
          <svg viewBox="0 0 24 24" width="1rem" height="1rem">
            <path :d="mdiTable" fill="#6987b8" />
          </svg>
          <ElmInlineText :text="caption" />
        </span>

        <span :class="$style.spacing"></span>
      </span>
    </caption>

    <slot v-if="slots.header != null" name="header" />
    <slot name="body" />
  </table>
</template>

<script setup lang="ts">
import ElmTableHeader from "./ElmTableHeader.vue";
import ElmTableBody from "./ElmTableBody.vue";

import type { Property } from "csstype";
import { computed, provide, ComputedRef } from "vue";
import ElmInlineText from "../typography/ElmInlineText.vue";

import { mdiTable } from "@mdi/js";

import textStyle from "../../styles/text.module.scss";

export interface ElmTableProps {
  /**
   * The margin of the table.
   */
  margin?: Property.MarginBlock;

  caption?: string;

  hasRowHeader?: boolean;
}

const props = withDefaults(defineProps<ElmTableProps>(), {
  hasRowHeader: false,
});

const hasRowHeader = computed(() => props.hasRowHeader);

provide<ComputedRef<boolean>, string>("hasRowHeader", hasRowHeader);

const slots = defineSlots<{
  /**
   * (Optional) The header slot of the table.
   */
  header?: InstanceType<typeof ElmTableHeader>;

  /**
   * The body slot of the table.
   */
  body: InstanceType<typeof ElmTableBody>;
}>();
</script>

<style module lang="scss">
.table {
  margin-block: var(--margin-block);
  border-collapse: collapse;
  border-spacing: 0;
  box-shadow: 0 0 0.125rem rgba(black, 0.2);
}

.caption {
  position: relative;
  width: 100%;
  display: inline-flex;
  justify-content: center;
  align-items: center;
  gap: 1rem;
  margin-block-end: 1rem;
}

.caption-inner {
  display: inline-flex;
  justify-content: center;
  align-items: center;
  gap: 0.25rem;
}

.spacing {
  flex-grow: 1;
  height: 1px;
  background-color: rgba(gray, 0.2);
}
</style>

// packages/react/src/components/table/ElmTable.tsx
import React from "react";
import type { Property } from "csstype";

import "@styles/global.css";
import styles from "./ElmTable.module.css";

import { mdiTable } from "@mdi/js";
import { HasRowHeaderContext } from "./TableContext";
import { ElmInlineText } from "@components/typography/ElmInlineText";

export interface ElmTableCSSVariables {
  "--margin-block"?: Property.MarginBlock;
}

export interface ElmTableProps {
  style?: React.CSSProperties & ElmTableCSSVariables;

  /**
   * The margin of the table.
   */
  margin?: Property.MarginBlock;

  /**
   * Optional caption for the table.
   */
  caption?: string;

  /**
   * Whether the first cell in each row is a row header.
   */
  hasRowHeader?: boolean;

  /**
   * The header section (use ElmTableHeader).
   */
  header?: React.ReactNode;

  /**
   * The body section (use ElmTableBody).
   */
  body?: React.ReactNode;
}

export const ElmTable = ({
  margin,
  caption,
  hasRowHeader = false,
  header,
  body,
  style,
}: ElmTableProps) => {
  return (
    <HasRowHeaderContext.Provider value={hasRowHeader}>
      <table
        className={styles.table}
        style={{ "--margin-block": margin, ...style } as React.CSSProperties}
      >
        {caption != null && (
          <caption>
            <span className={styles.caption}>
              <span className={styles.spacing} />
              <span className={styles["caption-inner"]}>
                <svg viewBox="0 0 24 24" width="1rem" height="1rem">
                  <path d={mdiTable} fill="#6987b8" />
                </svg>
                <ElmInlineText text={caption} />
              </span>
              <span className={styles.spacing} />
            </span>
          </caption>
        )}
        {header}
        {body}
      </table>
    </HasRowHeaderContext.Provider>
  );
};
