// packages/react/src/components/table/elm-table-row.tsx
import type { ComponentPropsWithoutRef } from "react";
import { clsx } from "clsx";

import styles from "./elm-table-row.module.css";

export type ElmTableRowProps = ComponentPropsWithoutRef<"tr">;

export const ElmTableRow = ({
  className,
  children,
  ...props
}: ElmTableRowProps) => {
  return (
    <tr className={clsx(styles["elm-table-row"], className)} {...props}>
      {children}
    </tr>
  );
};

// packages/solid/src/components/table/elm-table-row.tsx
import { splitProps, type JSX } from "solid-js";
import { clsx } from "clsx";

import styles from "./elm-table-row.module.css";

export type ElmTableRowProps = JSX.HTMLAttributes<HTMLTableRowElement>;

export const ElmTableRow = (props: ElmTableRowProps) => {
  const [local, rest] = splitProps(props, ["class", "children"]);

  return (
    <tr {...rest} class={clsx(styles["elm-table-row"], local.class)}>
      {local.children}
    </tr>
  );
};
