// packages/react/src/components/table/elm-table-header.tsx
import type { ComponentPropsWithoutRef } from "react";
import { clsx } from "clsx";

import styles from "./elm-table-header.module.css";
import { TableSectionContext } from "./table-context";

export type ElmTableHeaderProps = ComponentPropsWithoutRef<"thead">;

export const ElmTableHeader = ({
  className,
  children,
  ...props
}: ElmTableHeaderProps) => {
  return (
    <TableSectionContext.Provider value="head">
      <thead className={clsx(styles["elm-table-header"], className)} {...props}>
        {children}
      </thead>
    </TableSectionContext.Provider>
  );
};

// packages/solid/src/components/table/elm-table-header.tsx
import { splitProps, type JSX } from "solid-js";
import { clsx } from "clsx";

import styles from "./elm-table-header.module.css";
import { TableSectionContext } from "./table-context";

export type ElmTableHeaderProps = JSX.HTMLAttributes<HTMLTableSectionElement>;

export const ElmTableHeader = (props: ElmTableHeaderProps) => {
  const [local, rest] = splitProps(props, ["class", "children"]);

  return (
    <TableSectionContext.Provider value={() => "head"}>
      <thead {...rest} class={clsx(styles["elm-table-header"], local.class)}>
        {local.children}
      </thead>
    </TableSectionContext.Provider>
  );
};
