// packages/react/src/components/table/elm-table.tsx
import type { ComponentPropsWithoutRef } from "react";
import { useEffect, useMemo, useRef, useState } from "react";
import { clsx } from "clsx";

import styles from "./elm-table.module.css";
import textStyles from "../../styles/text.module.css";
import { ElmInlineText } from "../typography/elm-inline-text";
import { HasRowHeaderContext } from "./table-context";

export interface ElmTableProps extends ComponentPropsWithoutRef<"table"> {
  caption?: string;

  hasRowHeader?: boolean;
}

/**
 * Tracks horizontal overflow of the scroll container so the table can react to
 * it: expose a keyboard-focusable, labeled scroll region only while it actually
 * overflows, and reveal edge shadows that hint at columns past the viewport.
 *
 * Server render reports "no overflow" (the effect never runs), so the scroll
 * affordances are pure progressive enhancement and never reach the SSR markup.
 */
const useScrollOverflow = () => {
  const ref = useRef<HTMLDivElement>(null);
  const [edges, setEdges] = useState({
    canScroll: false,
    atStart: true,
    atEnd: true,
  });

  useEffect(() => {
    const el = ref.current;
    if (el == null) return;

    const measure = () => {
      const max = el.scrollWidth - el.clientWidth;
      const next = {
        canScroll: max > 1,
        atStart: el.scrollLeft <= 1,
        atEnd: el.scrollLeft >= max - 1,
      };
      setEdges((prev) =>
        prev.canScroll === next.canScroll &&
        prev.atStart === next.atStart &&
        prev.atEnd === next.atEnd
          ? prev
          : next,
      );
    };

    measure();
    el.addEventListener("scroll", measure, { passive: true });
    const observer = new ResizeObserver(measure);
    observer.observe(el);
    return () => {
      el.removeEventListener("scroll", measure);
      observer.disconnect();
    };
  }, []);

  return { ref, ...edges };
};

export const ElmTable = ({
  className,
  caption,
  hasRowHeader = false,
  children,
  ...rest
}: ElmTableProps) => {
  const hasRowHeaderValue = useMemo(
    () => ({ value: hasRowHeader }),
    [hasRowHeader],
  );

  const { ref, canScroll, atStart, atEnd } = useScrollOverflow();

  return (
    <HasRowHeaderContext.Provider value={hasRowHeaderValue}>
      <div
        className={styles["elm-table-frame"]}
        data-overflow-start={canScroll && !atStart ? "" : undefined}
        data-overflow-end={canScroll && !atEnd ? "" : undefined}
      >
        <div
          ref={ref}
          className={styles["elm-table-scroll"]}
          tabIndex={canScroll ? 0 : undefined}
          role={canScroll && caption != null ? "region" : undefined}
          aria-label={canScroll && caption != null ? caption : undefined}
        >
          <table
            className={clsx(
              styles["elm-table"],
              textStyles.text,
              hasRowHeader && styles["sticky-row-header"],
              className,
            )}
            {...rest}
          >
            {caption && (
              <caption>
                <span className={styles.caption}>
                  <span className={styles.spacing}></span>

                  <span className={styles["caption-inner"]}>
                    <ElmInlineText>{caption}</ElmInlineText>
                  </span>

                  <span className={styles.spacing}></span>
                </span>
              </caption>
            )}
            {children}
          </table>
        </div>
      </div>
    </HasRowHeaderContext.Provider>
  );
};

// packages/solid/src/components/table/elm-table.tsx
import {
  createMemo,
  createSignal,
  onCleanup,
  onMount,
  Show,
  splitProps,
  type JSX,
} from "solid-js";
import { clsx } from "clsx";

import styles from "./elm-table.module.css";
import textStyles from "../../styles/text.module.css";
import { ElmInlineText } from "../typography/elm-inline-text";
import { HasRowHeaderContext } from "./table-context";

export interface ElmTableProps extends JSX.HTMLAttributes<HTMLTableElement> {
  caption?: string;
  hasRowHeader?: boolean;
}

export const ElmTable = (props: ElmTableProps) => {
  const [local, rest] = splitProps(props, [
    "class",
    "caption",
    "hasRowHeader",
    "children",
  ]);
  const [canScroll, setCanScroll] = createSignal(false);
  const [atStart, setAtStart] = createSignal(true);
  const [atEnd, setAtEnd] = createSignal(true);
  const hasRowHeader = createMemo(() => local.hasRowHeader ?? false);
  let scrollElement: HTMLDivElement | undefined;

  onMount(() => {
    const element = scrollElement;
    if (element == null) return;

    const measure = () => {
      const max = element.scrollWidth - element.clientWidth;
      setCanScroll(max > 1);
      setAtStart(element.scrollLeft <= 1);
      setAtEnd(element.scrollLeft >= max - 1);
    };

    measure();
    element.addEventListener("scroll", measure, { passive: true });

    const observer =
      typeof ResizeObserver === "undefined"
        ? undefined
        : new ResizeObserver(measure);
    observer?.observe(element);

    onCleanup(() => {
      element.removeEventListener("scroll", measure);
      observer?.disconnect();
    });
  });

  return (
    <HasRowHeaderContext.Provider value={hasRowHeader}>
      <div
        class={styles["elm-table-frame"]}
        data-overflow-start={canScroll() && !atStart() ? "" : undefined}
        data-overflow-end={canScroll() && !atEnd() ? "" : undefined}
      >
        <div
          ref={(element) => {
            scrollElement = element;
          }}
          class={styles["elm-table-scroll"]}
          tabIndex={canScroll() ? 0 : undefined}
          role={canScroll() && local.caption != null ? "region" : undefined}
          aria-label={
            canScroll() && local.caption != null ? local.caption : undefined
          }
        >
          <table
            {...rest}
            class={clsx(
              styles["elm-table"],
              textStyles.text,
              local.hasRowHeader && styles["sticky-row-header"],
              local.class,
            )}
          >
            <Show when={local.caption}>
              {(caption) => (
                <caption>
                  <span class={styles.caption}>
                    <span class={styles.spacing} />
                    <span class={styles["caption-inner"]}>
                      <ElmInlineText>{caption()}</ElmInlineText>
                    </span>
                    <span class={styles.spacing} />
                  </span>
                </caption>
              )}
            </Show>
            {local.children}
          </table>
        </div>
      </div>
    </HasRowHeaderContext.Provider>
  );
};
