// packages/react/src/components/navigation/ElmTableOfContents.tsx
import React from "react";

import "@styles/global.css";
import styles from "./ElmTableOfContents.module.css";
import { ElmInlineText } from "@components/typography/ElmInlineText";
import { ElmMdiIcon } from "@components/icon/ElmMdiIcon";

import { mdiMenuDown } from "@mdi/js";

export interface ElmTableOfContentsCSSVariables {}

export interface ElmTableOfContentsProps {
  style?: React.CSSProperties & ElmTableOfContentsCSSVariables;

  /**
   * The headings to display.
   */
  headings: Array<{
    level: 1 | 2 | 3 | 4 | 5 | 6;
    text: string;
    id?: string;
  }>;
}

export const ElmTableOfContents = ({
  headings,
  style,
}: ElmTableOfContentsProps) => {
  return (
    <nav className={styles.toc} style={style}>
      {headings.map((heading, index) => (
        <a
          key={index}
          className={styles.link}
          href={`#${heading.id ?? heading.text}`}
          style={{
            "--padding-left": `${heading.level * 0.5}rem`,
          } as React.CSSProperties}
        >
          <sup>
            <ElmInlineText size="0.6rem" color="#6987b8">
              {`H${heading.level}`}
            </ElmInlineText>
          </sup>
          <ElmInlineText>{heading.text}</ElmInlineText>
          <ElmMdiIcon d={mdiMenuDown} size="1em" color="#6987b8" />
        </a>
      ))}
    </nav>
  );
};

// packages/core/src/components/navigation/ElmTableOfContents.vue
<template>
  <nav :class="$style.toc">
    <a
      :class="$style.link"
      v-for="heading in headings"
      :href="`#${heading.id ?? heading.text}`"
      :style="{ '--padding-left': `${heading.level * 0.5}rem` }"
    >
      <sup>
        <ElmInlineText
          :text="`H${heading.level}`"
          size="0.6rem"
          color="#6987b8"
        />
      </sup>
      <ElmInlineText :text="heading.text" />
      <ElmMdiIcon :d="mdiMenuDown" size="1em" color="#6987b8" />
    </a>
  </nav>
</template>

<script setup lang="ts">
import ElmInlineText from "../typography/ElmInlineText.vue";

import ElmMdiIcon from "../icon/ElmMdiIcon.vue";
import { mdiMenuDown } from "@mdi/js";

export interface ElmTableOfContentsProps {
  headings: Array<{
    level: 1 | 2 | 3 | 4 | 5 | 6;
    text: string;
    id?: string;
  }>;
}

withDefaults(defineProps<ElmTableOfContentsProps>(), {});
</script>

<style module lang="scss">
.toc {
  box-sizing: border-box;
  display: flex;
  flex-direction: column;
  padding-left: 0.5rem;
  border-left-style: solid;
  border-left-width: 0.25rem;
  border-left-color: rgba(black, 0.1);
  [data-theme="dark"] & {
    border-left-color: rgba(white, 0.15);
  }

  .link {
    all: unset;
    box-sizing: border-box;
    display: flex;
    justify-content: flex-start;
    gap: 0.5rem;
    border-radius: 0.25rem;
    padding: 0.25rem;
    padding-left: var(--padding-left, 0.25rem);
    transition: background-color 200ms;
    cursor: pointer;

    &:hover {
      background-color: rgba(#6987b8, 0.2);
    }
  }
}
</style>
