// packages/vue/src/components/containments/elm-tooltip.tsx
import {
  defineComponent,
  ref,
  type CSSProperties,
  type HTMLAttributes,
} from "vue";
import { clsx } from "clsx";

import styles from "./elm-tooltip.module.css";

export type ElmTooltipProps = HTMLAttributes;

export const ElmTooltip = defineComponent({
  name: "ElmTooltip",
  setup(_, { slots }) {
    const elRef = ref<HTMLSpanElement | null>(null);
    const isHover = ref(false);
    let isHideSchedule = false;
    let hideTimerId: ReturnType<typeof setTimeout> | undefined;
    const position = ref<CSSProperties>({});

    const handleMouseOver = () => {
      const el = elRef.value;
      if (!el) {
        return;
      }

      if (isHideSchedule) {
        window.clearTimeout(hideTimerId);
        isHideSchedule = false;
      }

      const rect = el.getBoundingClientRect();
      const windowWidth = window.innerWidth;

      if (rect.x > windowWidth / 2) {
        position.value = {
          top: `${rect.bottom}px`,
          right: `${windowWidth - rect.x - rect.width}px`,
        };
      } else {
        position.value = {
          top: `${rect.bottom}px`,
          left: `${rect.x}px`,
        };
      }

      isHover.value = true;
    };

    const handleMouseLeave = () => {
      if (isHideSchedule) {
        return;
      }
      isHideSchedule = true;

      hideTimerId = setTimeout(() => {
        isHideSchedule = false;
        isHover.value = false;
      }, 250);
    };

    // inheritAttrs default: a passthrough class merges with the root binding and
    // a passthrough onMouseover/onMouseleave is invoked alongside ours.
    return () => (
      <span
        ref={elRef}
        class={clsx(styles["elm-tooltip"])}
        onMouseover={handleMouseOver}
        onMouseleave={handleMouseLeave}
      >
        {slots.original?.()}

        <div
          class={clsx(styles.tooltip, isHover.value && styles.show)}
          style={position.value}
        >
          {slots.tooltip?.()}
        </div>
      </span>
    );
  },
});

// packages/qwik/src/components/containments/elm-tooltip.tsx
import {
  $,
  component$,
  Slot,
  useSignal,
  type CSSProperties,
} from "@builder.io/qwik";

import styles from "./elm-tooltip.module.css";

export interface ElmTooltipProps {
  class?: string;

  style?: CSSProperties;
}

export const ElmTooltip = component$<ElmTooltipProps>(
  ({ class: className, style }) => {
    const elRef = useSignal<HTMLSpanElement>();
    const isHover = useSignal(false);
    const isHideSchedule = useSignal(false);
    const hideTimerId = useSignal<number>();
    const position = useSignal<CSSProperties>({});

    const handleMouseOver = $(() => {
      const el = elRef.value;
      if (!el) return;

      if (isHideSchedule.value) {
        window.clearTimeout(hideTimerId.value);
        isHideSchedule.value = false;
      }

      const rect = el.getBoundingClientRect();
      const windowWidth = window.innerWidth;

      if (rect.x > windowWidth / 2) {
        position.value = {
          top: `${rect.bottom}px`,
          right: `${windowWidth - rect.x - rect.width}px`,
        };
      } else {
        position.value = {
          top: `${rect.bottom}px`,
          left: `${rect.x}px`,
        };
      }

      isHover.value = true;
    });

    const handleMouseLeave = $(() => {
      if (isHideSchedule.value) return;
      isHideSchedule.value = true;

      hideTimerId.value = window.setTimeout(() => {
        isHideSchedule.value = false;
        isHover.value = false;
      }, 250);
    });

    return (
      <span
        ref={elRef}
        class={[styles.original, className]}
        onMouseOver$={handleMouseOver}
        onMouseLeave$={handleMouseLeave}
        style={style}
      >
        <Slot name="original" />

        <div
          class={[
            styles.tooltip,
            {
              [styles.show]: isHover.value,
            },
          ]}
          style={position.value}
        >
          <Slot name="tooltip" />
        </div>
      </span>
    );
  },
);
