// packages/react/src/components/containments/elm-parallax.tsx
import {
  useEffect,
  useState,
  type ComponentPropsWithoutRef,
  type CSSProperties,
} from "react";

import styles from "./elm-parallax.module.css";

export interface ElmParallaxProps extends ComponentPropsWithoutRef<"div"> {
  images: string[];
}

export const ElmParallax = ({
  className,
  images,
  ...props
}: ElmParallaxProps) => {
  const [y, setY] = useState(0);

  useEffect(() => {
    const handleScroll = () => {
      setY(window.scrollY);
    };

    window.addEventListener("scroll", handleScroll);
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  return (
    <div className={className} {...props}>
      <div className={styles["parallax-watcher"]}></div>

      {images.map((image, index) => (
        <div
          key={index}
          className={styles.parallax}
          style={
            {
              backgroundImage: `url(${image})`,
              transform: `scale(1.2) translateY(${y / (1000 * (index + 1))}%)`,
              transformOrigin: "bottom",
            } as CSSProperties
          }
        ></div>
      ))}
    </div>
  );
};

// packages/qwik/src/components/containments/elm-parallax.tsx
import { component$, useSignal, type CSSProperties } from "@builder.io/qwik";

import styles from "./elm-parallax.module.css";

export interface ElmParallaxProps {
  class?: string;

  style?: CSSProperties;

  images: string[];
}

export const ElmParallax = component$<ElmParallaxProps>(
  ({ class: className, style, images }) => {
    const y = useSignal(0);

    return (
      <div class={className} style={style}>
        <div
          class={styles["parallax-watcher"]}
          window:onScroll$={() => {
            y.value = window.scrollY;
          }}
        ></div>

        {images.map((image, index) => (
          <div
            key={index}
            class={styles.parallax}
            style={{
              backgroundImage: `url(${image})`,
              transform: `scale(1.2) translateY(${y.value / (1000 * (index + 1))}%)`,
              transformOrigin: "bottom",
            }}
          ></div>
        ))}
      </div>
    );
  },
);
