// packages/react/src/components/form/elm-button.tsx
import {
  useEffect,
  useRef,
  useState,
  type ComponentPropsWithoutRef,
  type CSSProperties,
  type MouseEvent,
} from "react";
import { clsx } from "clsx";

import { ElmDotLoadingIcon } from "../icon/elm-dot-loading-icon";
import styles from "./elm-button.module.css";

export interface ElmButtonProps extends ComponentPropsWithoutRef<"button"> {
  /**
   * Whether the button is in loading state.
   */
  isLoading?: boolean;

  /**
   * Whether the button is block.
   */
  block?: boolean;

  color?: string;

  /**
   * Whether the button is primary.
   */
  primary?: boolean;
}

export const ElmButton = ({
  className,
  style,
  onClick,
  isLoading,
  block,
  color,
  primary,
  disabled,
  children,
  ...props
}: ElmButtonProps) => {
  const [clicked, setClicked] = useState(false);
  const timer = useRef<ReturnType<typeof setTimeout>>(undefined);

  useEffect(() => () => clearTimeout(timer.current), []);

  const handleClick = (event: MouseEvent<HTMLButtonElement>) => {
    if (!isLoading && !disabled) {
      if (onClick) {
        setClicked(true);
        clearTimeout(timer.current);
        timer.current = setTimeout(() => setClicked(false), 300);
        onClick(event);
      }
    }
  };

  return (
    <button
      onClick={handleClick}
      disabled={disabled}
      className={clsx(
        styles["elm-button"],
        !isLoading && !disabled && styles.enable,
        color && styles.colored,
        !color && !primary && styles.normal,
        !color && primary && styles.primary,
        className,
      )}
      style={
        {
          display: block ? "flex" : "inline-flex",
          width: block ? "100%" : "auto",
          cursor: disabled ? "not-allowed" : isLoading ? "progress" : "pointer",
          "--elmethis-scoped-opacity": disabled || isLoading ? 0.6 : undefined,
          "--elmethis-scoped-color": color,
          ...style,
        } as CSSProperties
      }
      {...props}
    >
      {clicked && <span className={styles.ripple}></span>}

      {isLoading ? (
        <ElmDotLoadingIcon size="1.5rem" />
      ) : (
        <span className={styles.flex}>{children}</span>
      )}
    </button>
  );
};

// packages/solid/src/components/form/elm-button.tsx
import { createSignal, onCleanup, Show, splitProps, type JSX } from "solid-js";
import { clsx } from "clsx";

import { callEventHandler } from "../../primitives/call-event-handler";
import { mergeStyle } from "../../styles/merge-style";
import { ElmDotLoadingIcon } from "../icon/elm-dot-loading-icon";
import styles from "./elm-button.module.css";

export interface ElmButtonProps extends JSX.ButtonHTMLAttributes<HTMLButtonElement> {
  /** Whether the button is in loading state. */
  isLoading?: boolean;

  /** Whether the button fills its container. */
  block?: boolean;

  color?: string;

  /** Whether the button uses the primary variant. */
  primary?: boolean;
}

export const ElmButton = (props: ElmButtonProps) => {
  const [local, rest] = splitProps(props, [
    "class",
    "style",
    "onClick",
    "isLoading",
    "block",
    "color",
    "primary",
    "disabled",
    "children",
  ]);
  const [clicked, setClicked] = createSignal(false);
  let timer: ReturnType<typeof setTimeout> | undefined;

  onCleanup(() => clearTimeout(timer));

  const handleClick: JSX.EventHandler<HTMLButtonElement, MouseEvent> = (
    event,
  ) => {
    if (local.isLoading || local.disabled || !local.onClick) return;

    setClicked(true);
    clearTimeout(timer);
    timer = setTimeout(() => setClicked(false), 300);
    callEventHandler(local.onClick, event);
  };

  return (
    <button
      {...rest}
      onClick={handleClick}
      disabled={local.disabled}
      class={clsx(
        styles["elm-button"],
        !local.isLoading && !local.disabled && styles.enable,
        local.color && styles.colored,
        !local.color && !local.primary && styles.normal,
        !local.color && local.primary && styles.primary,
        local.class,
      )}
      style={mergeStyle(local.style, {
        display: local.block ? "flex" : "inline-flex",
        width: local.block ? "100%" : "auto",
        cursor: local.disabled
          ? "not-allowed"
          : local.isLoading
            ? "progress"
            : "pointer",
        "--elmethis-scoped-opacity":
          local.disabled || local.isLoading ? 0.6 : undefined,
        "--elmethis-scoped-color": local.color,
      })}
    >
      <Show when={clicked()}>
        <span class={styles.ripple} />
      </Show>
      <Show
        when={!local.isLoading}
        fallback={<ElmDotLoadingIcon size="1.5rem" />}
      >
        <span class={styles.flex}>{local.children}</span>
      </Show>
    </button>
  );
};
