// packages/qwik/src/components/typography/elm-divider.tsx
import { component$, CSSProperties } from "@builder.io/qwik";

import styles from "./elm-divider.module.scss";

export type ElmDividerProps = {
  /**
   * The margin of the divider.
   */
  margin?: CSSProperties["margin-block"];
};

export const ElmDivider = component$<ElmDividerProps>(({ margin }) => {
  return <hr class={styles.hr} style={{ marginBlock: margin }} />;
});

// packages/react/src/components/typography/ElmDivider.tsx
import React from "react";

import "@styles/global.css";
import styles from "./ElmDivider.module.css";
import type { ElmethisCSSVariables } from "@styles/variables";

export type ElmDividerCSSVariables = Pick<
  ElmethisCSSVariables,
  | "--elmethis-margin-block"
  | "--elmethis-text-color-light"
  | "--elmethis-text-color-dark"
>;

export interface ElmDividerProps {
  style?: React.CSSProperties & ElmDividerCSSVariables;

  /**
   * The margin of the divider.
   */
  margin?: React.CSSProperties["marginBlock"];
}

export const ElmDivider = (props: ElmDividerProps) => {
  return (
    <hr
      className={styles.divider}
      style={
        {
          "--elmethis-margin-block": props.margin,
          ...props.style,
        } as React.CSSProperties
      }
    />
  );
};
