// packages/react/src/hooks/use-auto-animate.tsx
import { useAutoAnimate as useFormkitAutoAnimate } from "@formkit/auto-animate/react";
import autoAnimate from "@formkit/auto-animate";

export type UseAutoAnimateOptions = {
  /**
   * The configuration options for auto-animate.
   */
  config?: Parameters<typeof autoAnimate>[1];
};

/**
 * A hook that provides an easy way to add auto-animate to a component.
 *
 * @see {@link https://auto-animate.formkit.com/|Auto Animate} for more information.
 *
 * This hook returns the `[ref, setEnabled]` shape exposed by
 * `@formkit/auto-animate/react`, mapped onto a `{ ref, setEnabled }` object:
 * spread `ref` onto the container element, and call `setEnabled(boolean)` to
 * toggle the animation controller on or off.
 *
 * @example
 *   const Render = () => {
 *     const { ref } = useAutoAnimate();
 *     const [items, setItems] = useState([1, 2, 3, 4, 5]);
 *
 *     const handleShuffle = () => {
 *       setItems((prev) => [...prev].sort(() => Math.random() - 0.5));
 *     };
 *
 *     return (
 *       <div>
 *         <button onClick={handleShuffle}>Click me</button>
 *         <ul ref={ref}>
 *           {items.map((item) => (
 *             <li key={item}>Item {item}</li>
 *           ))}
 *         </ul>
 *       </div>
 *     );
 *   };
 */
export const useAutoAnimate = <T extends HTMLElement = HTMLElement>(
  options?: UseAutoAnimateOptions,
) => {
  const [ref, setEnabled] = useFormkitAutoAnimate<T>(options?.config);

  return { ref, setEnabled };
};

// packages/qwik/src/hooks/use-auto-animate.tsx
import {
  noSerialize,
  NoSerialize,
  useSignal,
  useVisibleTask$,
} from "@builder.io/qwik";
import autoAnimate from "@formkit/auto-animate";

export type UseAutoAnimateOptions = {
  /**
   * The configuration options for auto-animate.
   */
  config?: Parameters<typeof autoAnimate>[1];
};

/**
 * A hook that provides an easy way to add auto-animate to a component.
 * 
 * @see {@link https://auto-animate.formkit.com/|Auto Animate} for more information.
 * 
 * @example 
    const Render = component$(() => {
      const { ref } = useAutoAnimate(options);
  
      const store = useStore<{ items: number[] }>({
        items: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      });
  
      const handleSuffle = $(() => {
        store.items = store.items.sort(() => Math.random() - 0.5);
      });
  
      return (
        <div>
        <button onClick$={handleSuffle}>Click me</button>
        <ElmList listStyle="unordered" ref={ref}>
            {store.items.map((item) => (
            <li key={item}>Item {item}</li>
            ))}
        </ElmList>
        </div>
      );
    });
 */
export const useAutoAnimate = (options?: UseAutoAnimateOptions) => {
  const ref = useSignal<HTMLElement>();
  const animationController =
    useSignal<NoSerialize<ReturnType<typeof autoAnimate>>>();

  // eslint-disable-next-line qwik/no-use-visible-task
  useVisibleTask$(({ cleanup }) => {
    if (ref.value != null) {
      animationController.value = noSerialize(
        autoAnimate(ref.value, options?.config),
      );
    }
    cleanup(() => {
      if (
        animationController.value != null &&
        animationController.value.isEnabled()
      ) {
        animationController.value.disable();
      }
    });
  });

  return { ref, animationController };
};
