// packages/react/src/hooks/use-debounced-signal.ts
import { useEffect, useMemo, useRef, useState } from "react";
import { useDebounceValue } from "usehooks-ts";

/**
 * React shape returned by {@link useDebouncedSignal}.
 *
 * Exposed as a `useState`-style object: `value` + `setValue` hold the immediate
 * value, `debouncedValue` is read-only, and `isPending` is a plain boolean.
 */
export interface UseDebouncedSignalReturn<T> {
  /** The current value. Reflects every write to `setValue` immediately. */
  value: T;
  /** Writes a new value or applies an updater. */
  setValue: React.Dispatch<React.SetStateAction<T>>;
  /**
   * The debounced value. Reflects `value` only after `delay` ms have elapsed
   * since the last write. Rapid successive writes reset the timer so only the
   * final value propagates.
   */
  debouncedValue: T;
  /** `true` while a debounced update is queued but has not yet committed. */
  isPending: boolean;
}

/**
 * Returns a debounced value pair where writing through `setValue` drives a
 * debounced update to `debouncedValue`.
 *
 * `value` reflects every write immediately.
 * `debouncedValue` reflects the same value only after `delay` ms have elapsed
 * since the last write. Rapid successive writes reset the timer so only the
 * final value propagates to `debouncedValue`.
 *
 * When `delay` is 0 or negative, `debouncedValue` is updated synchronously.
 *
 * @param initialValue - The initial value for both `value` and `debouncedValue`.
 * @param delay - Debounce delay in milliseconds.
 */
export const useDebouncedSignal = <T>(
  initialValue: T | (() => T),
  delay: number,
): UseDebouncedSignalReturn<T> => {
  // Resolve a lazy initializer exactly once. Passing the raw `initialValue` to
  // both state initializers would invoke the factory twice, which is
  // surprising for callers and breaks any side-effectful initializer.
  const resolved = useState(initialValue)[0];

  const [value, setValue] = useState<T>(resolved);
  const [debouncedValue, setDebouncedValue] = useDebounceValue<T>(
    resolved,
    Math.max(delay, 0),
  );

  // Mirror immediate writes into the debounced setter. With `delay <= 0` the
  // update is applied synchronously; otherwise it is queued behind the timer.
  const isFirst = useRef(true);
  useEffect(() => {
    if (isFirst.current) {
      isFirst.current = false;
      return;
    }
    if (delay <= 0) {
      setDebouncedValue(value);
      // Flush the queued update synchronously so there is no pending timer.
      setDebouncedValue.flush();
      return;
    }
    setDebouncedValue(value);
  }, [value, delay, setDebouncedValue]);

  const isPending = useMemo(
    () => !Object.is(value, debouncedValue),
    [value, debouncedValue],
  );

  return { value, setValue, debouncedValue, isPending };
};

// packages/qwik/src/hooks/use-debounced-signal.ts
import { useSignal, useTask$ } from "@builder.io/qwik";

/**
 * Returns a reactive signal pair where writing to `signal` drives a debounced
 * update to `debouncedSignal`.
 *
 * `signal` reflects every write immediately.
 * `debouncedSignal` reflects the same value only after `delay` ms have
 * elapsed since the last write to `signal`. Rapid successive writes reset
 * the timer so only the final value propagates to `debouncedSignal`.
 *
 * When `delay` is 0 or negative, `debouncedSignal` is updated synchronously.
 *
 * SSR caveat: this hook arms a `setTimeout` inside a `useTask$`. On the
 * server the timer never fires before HTML serialization, so any write to
 * `signal` that happens *during* SSR (e.g. via a sibling `useTask$`) ships a
 * stuck `isPending: true` and a stale `debouncedSignal` to the client. Seed
 * the signal from `useSignal(initial)` / a `routeLoader$` value at
 * construction instead of writing it from a server task.
 *
 * @param initialValue - The initial value for both signals.
 * @param delay - Debounce delay in milliseconds.
 */
export const useDebouncedSignal = <T>(
  initialValue: Parameters<typeof useSignal<T>>[0],
  delay: number,
) => {
  // Resolve a lazy initializer once. Passing the raw `initialValue` to both
  // `useSignal` calls would invoke the factory twice (once per call), which
  // is surprising for callers and breaks any side-effectful initializer.
  const resolved = (
    typeof initialValue === "function"
      ? (initialValue as () => T)()
      : initialValue
  ) as T;
  const signal = useSignal<T>(resolved);
  const debouncedSignal = useSignal<T>(resolved);
  const isPending = useSignal(false);

  useTask$(({ track, cleanup }) => {
    const value = track(() => signal.value);

    if (delay <= 0) {
      debouncedSignal.value = value;
      isPending.value = false;
      return;
    }

    if (value === debouncedSignal.value) {
      isPending.value = false;
      return;
    }

    isPending.value = true;

    const id = setTimeout(() => {
      debouncedSignal.value = value;
      isPending.value = false;
    }, delay);

    cleanup(() => clearTimeout(id));
  });

  return { signal, debouncedSignal, isPending };
};
