// packages/react/src/components/navigation/elm-bookmark.tsx
import { useState } from "react";
import type { ComponentPropsWithoutRef, CSSProperties } from "react";
import { clsx } from "clsx";
import { mdiLinkVariant } from "@mdi/js";

import styles from "./elm-bookmark.module.css";
import { ElmInlineText } from "../typography/elm-inline-text";
import { ElmMdiIcon } from "../icon/elm-mdi-icon";
import { ElmInlineIcon } from "../icon/elm-inline-icon";

export interface ElmBookmarkProps extends ComponentPropsWithoutRef<"div"> {
  /**
   * The description of the bookmark.
   */
  description?: string;

  /**
   * The image to display.
   * This can be a URL or a base64-encoded image.
   */
  image?: string;

  /**
   * The URL to navigate to.
   */
  url?: string;

  /**
   * The URL of the favicon.
   */
  favicon?: string;
}

const hiddenStyle: CSSProperties = {
  visibility: "hidden",
  width: "0",
};

export const ElmBookmark = ({
  className,
  title,
  url,
  image,
  description,
  favicon,
  ...props
}: ElmBookmarkProps) => {
  const [isError, setIsError] = useState(false);

  return (
    <div className={clsx(styles["elm-bookmark"], className)} {...props}>
      <a
        className={styles.container}
        href={url}
        target="_blank"
        rel="noopener noreferrer"
      >
        <img
          className={styles.image}
          src={image}
          alt="OGP Image"
          onError={() => setIsError(true)}
          style={isError || image == null ? hiddenStyle : {}}
        />

        <div className={styles.content}>
          <div className={styles.title}>
            <ElmInlineText bold>{title}</ElmInlineText>
          </div>

          <div className={styles.description}>
            <ElmInlineText size="0.75rem">{description}</ElmInlineText>
          </div>

          <div className={styles.link}>
            {favicon ? (
              <ElmInlineIcon src={favicon} />
            ) : (
              <ElmMdiIcon
                path={mdiLinkVariant}
                color="var(--elmethis-color-accent-info)"
              />
            )}
            <ElmInlineText size="0.75rem">{url}</ElmInlineText>
          </div>
        </div>
      </a>
    </div>
  );
};

// packages/solid/src/components/navigation/elm-bookmark.tsx
import { createEffect, createSignal, on, splitProps, type JSX } from "solid-js";
import { clsx } from "clsx";
import { mdiLinkVariant } from "@mdi/js";

import styles from "./elm-bookmark.module.css";
import { ElmInlineText } from "../typography/elm-inline-text";
import { ElmMdiIcon } from "../icon/elm-mdi-icon";
import { ElmInlineIcon } from "../icon/elm-inline-icon";

export interface ElmBookmarkProps extends JSX.HTMLAttributes<HTMLDivElement> {
  /** The description of the bookmark. */
  description?: string;

  /** The image URL or base64-encoded image to display. */
  image?: string;

  /** The URL to navigate to. */
  url?: string;

  /** The URL of the favicon. */
  favicon?: string;
}

const HIDDEN_IMAGE_STYLE: JSX.CSSProperties = {
  visibility: "hidden",
  width: "0",
};

export const ElmBookmark = (props: ElmBookmarkProps) => {
  const [local, rest] = splitProps(props, [
    "class",
    "title",
    "url",
    "image",
    "description",
    "favicon",
  ]);
  const [imageError, setImageError] = createSignal(false);

  createEffect(
    on(
      () => local.image,
      () => setImageError(false),
      { defer: true },
    ),
  );

  return (
    <div class={clsx(styles["elm-bookmark"], local.class)} {...rest}>
      <a
        class={styles.container}
        href={local.url}
        target="_blank"
        rel="noopener noreferrer"
      >
        <img
          class={styles.image}
          src={local.image}
          alt="OGP Image"
          onError={() => setImageError(true)}
          style={
            imageError() || local.image == null ? HIDDEN_IMAGE_STYLE : undefined
          }
        />

        <div class={styles.content}>
          <div class={styles.title}>
            <ElmInlineText bold>{local.title}</ElmInlineText>
          </div>

          <div class={styles.description}>
            <ElmInlineText size="0.75rem">{local.description}</ElmInlineText>
          </div>

          <div class={styles.link}>
            {local.favicon ? (
              <ElmInlineIcon src={local.favicon} />
            ) : (
              <ElmMdiIcon
                path={mdiLinkVariant}
                color="var(--elmethis-color-accent-info)"
              />
            )}
            <ElmInlineText size="0.75rem">{local.url}</ElmInlineText>
          </div>
        </div>
      </a>
    </div>
  );
};
