// packages/react/src/components/typography/elm-block-quote.tsx
import type { ComponentPropsWithoutRef } from "react";
import { clsx } from "clsx";
import { mdiFormatQuoteClose, mdiFormatQuoteOpen } from "@mdi/js";

import styles from "./elm-block-quote.module.css";
import textStyles from "../../styles/text.module.css";
import { ElmMdiIcon } from "../icon/elm-mdi-icon";

export interface ElmBlockQuoteProps extends ComponentPropsWithoutRef<"blockquote"> {}

export const ElmBlockQuote = ({
  className,
  children,
  ...props
}: ElmBlockQuoteProps) => {
  return (
    <blockquote
      className={clsx(styles["elm-block-quote"], textStyles.text, className)}
      {...props}
    >
      <div className={clsx(styles.icon, styles["icon-top-left"])}>
        <ElmMdiIcon path={mdiFormatQuoteOpen} />
      </div>

      <div className={styles.body}>{children}</div>

      <div className={clsx(styles.icon, styles["icon-bottom-right"])}>
        <ElmMdiIcon path={mdiFormatQuoteClose} />
      </div>
    </blockquote>
  );
};

// packages/vue/src/components/typography/elm-block-quote.tsx
import { defineComponent, type HTMLAttributes } from "vue";
import { clsx } from "clsx";
import { mdiFormatQuoteClose, mdiFormatQuoteOpen } from "@mdi/js";

import styles from "./elm-block-quote.module.css";
import textStyles from "../../styles/text.module.css";
import { ElmMdiIcon } from "../icon/elm-mdi-icon";

export type ElmBlockQuoteProps = HTMLAttributes;

export const ElmBlockQuote = defineComponent({
  name: "ElmBlockQuote",
  setup(_, { slots }) {
    // inheritAttrs default: passthrough class/style merge onto the root.
    return () => (
      <blockquote class={clsx(styles["elm-block-quote"], textStyles.text)}>
        <div class={clsx(styles.icon, styles["icon-top-left"])}>
          <ElmMdiIcon path={mdiFormatQuoteOpen} />
        </div>

        <div class={styles.body}>{slots.default?.()}</div>

        <div class={clsx(styles.icon, styles["icon-bottom-right"])}>
          <ElmMdiIcon path={mdiFormatQuoteClose} />
        </div>
      </blockquote>
    );
  },
});
