// packages/react/src/components/typography/elm-callout.tsx
import type { ComponentPropsWithoutRef } from "react";
import { clsx } from "clsx";

import styles from "./elm-callout.module.css";
import {
  mdiAlert,
  mdiAlertOctagram,
  mdiInformation,
  mdiLightbulbOn,
  mdiShieldAlert,
} from "@mdi/js";
import { ElmMdiIcon } from "../icon/elm-mdi-icon";

export type AlertType = "note" | "tip" | "important" | "warning" | "caution";

const ICON_MAP: Record<AlertType, string> = Object.freeze({
  note: mdiInformation,
  tip: mdiLightbulbOn,
  important: mdiShieldAlert,
  warning: mdiAlert,
  caution: mdiAlertOctagram,
} as const);

export interface ElmCalloutProps extends ComponentPropsWithoutRef<"aside"> {
  /**
   * Type of alert
   */
  type?: AlertType;
}

export const ElmCallout = ({
  className,
  type = "note",
  style,
  children,
  ...props
}: ElmCalloutProps) => {
  return (
    <aside
      className={clsx(styles["elm-callout"], styles[type], className)}
      style={style}
      {...props}
    >
      <div className={styles.header}>
        <ElmMdiIcon
          className={styles.icon}
          path={ICON_MAP[type]}
          size="1.25rem"
        />
        <span>{type}</span>
      </div>

      <div className={styles.content}>{children}</div>
    </aside>
  );
};

// packages/vue/src/components/typography/elm-callout.tsx
import { defineComponent, type HTMLAttributes, type PropType } from "vue";
import { clsx } from "clsx";
import {
  mdiAlert,
  mdiAlertOctagram,
  mdiInformation,
  mdiLightbulbOn,
  mdiShieldAlert,
} from "@mdi/js";

import styles from "./elm-callout.module.css";
import { ElmMdiIcon } from "../icon/elm-mdi-icon";

export type AlertType = "note" | "tip" | "important" | "warning" | "caution";

const ICON_MAP: Record<AlertType, string> = Object.freeze({
  note: mdiInformation,
  tip: mdiLightbulbOn,
  important: mdiShieldAlert,
  warning: mdiAlert,
  caution: mdiAlertOctagram,
} as const);

export interface ElmCalloutProps extends HTMLAttributes {
  /**
   * Type of alert
   */
  type?: AlertType;
}

export const ElmCallout = defineComponent({
  name: "ElmCallout",
  props: {
    type: { type: String as PropType<AlertType>, default: "note" },
  },
  setup(props, { slots }) {
    // inheritAttrs default: passthrough class/style merge onto the root.
    return () => (
      <aside class={clsx(styles["elm-callout"], styles[props.type])}>
        <div class={styles.header}>
          <ElmMdiIcon
            class={styles.icon}
            path={ICON_MAP[props.type]}
            size="1.25rem"
          />
          <span>{props.type}</span>
        </div>

        <div class={styles.content}>{slots.default?.()}</div>
      </aside>
    );
  },
});
