// packages/qwik/src/components/ag-ui-client/elm-ag-ui-prompt-picker.tsx
import {
  $,
  component$,
  useStore,
  type CSSProperties,
  type QRL,
} from "@qwik.dev/core";

import styles from "./elm-ag-ui-prompt-picker.module.css";
import { useModal } from "../../hooks/use-modal";

/**
 * Descriptor shape consumed by `ElmAgUiPromptPicker`. Intentionally
 * kept independent from `McpPromptDescriptor` so the picker component
 * does not pull in MCP-specific types — anything mappable to this
 * shape can drive the UI.
 */
export interface ElmAgUiPromptDescriptor {
  /**
   * Stable identifier the parent uses to look this prompt up when the
   * user picks it. Forwarded to `onPick$` verbatim.
   */
  key: string;
  /** Display name shown in the picker list. */
  name: string;
  /** Optional descriptive blurb shown under the name. */
  description?: string;
  /**
   * Argument fields shown as a modal form when the user clicks the
   * prompt. Omit (or empty array) for prompts that take no arguments
   * — the picker will pick immediately on click.
   */
  arguments?: {
    name: string;
    description?: string;
    required?: boolean;
  }[];
}

export interface ElmAgUiPromptPickerProps {
  class?: string;
  style?: CSSProperties;
  prompts: ElmAgUiPromptDescriptor[];
  /**
   * Invoked when the user picks a prompt. For no-arg prompts, fires
   * immediately on click. For prompts with arguments, fires after the
   * user fills the modal form and clicks "Use prompt".
   */
  onPick$: QRL<
    (key: string, args: Record<string, string>) => Promise<void> | void
  >;
}

interface ActivePrompt {
  /** Currently-active descriptor, or `null` when the modal is idle. */
  descriptor: ElmAgUiPromptDescriptor | null;
  values: Record<string, string>;
  submitting: boolean;
  error: string | null;
}

export const ElmAgUiPromptPicker = component$<ElmAgUiPromptPickerProps>(
  ({ class: className, style, prompts, onPick$ }) => {
    const { Modal, show, hide } = useModal({});

    // Single in-flight form state. Reset every time a new prompt is
    // chosen so stale values from a previously-cancelled prompt don't
    // leak across rows. Keyed by descriptor identity rather than by
    // name so two servers with the same prompt name still get clean
    // form state per row.
    const active = useStore<ActivePrompt>({
      descriptor: null,
      values: {},
      submitting: false,
      error: null,
    });

    const onRowClick$ = $(async (descriptor: ElmAgUiPromptDescriptor) => {
      const args = descriptor.arguments ?? [];
      if (args.length === 0) {
        // No-arg prompts: dispatch immediately, no modal.
        await onPick$(descriptor.key, {});
        return;
      }
      const initial: Record<string, string> = {};
      for (const a of args) initial[a.name] = "";
      active.descriptor = descriptor;
      active.values = initial;
      active.submitting = false;
      active.error = null;
      show();
    });

    const onCancel$ = $(() => {
      hide();
      active.error = null;
    });

    const onSubmit$ = $(async () => {
      const descriptor = active.descriptor;
      if (!descriptor) return;
      const args = descriptor.arguments ?? [];
      // Surface a single missing-required error rather than per-field
      // validation; keeps the modal lightweight.
      for (const a of args) {
        if (a.required && !(active.values[a.name] ?? "").trim()) {
          active.error = `"${a.name}" is required.`;
          return;
        }
      }
      active.error = null;
      active.submitting = true;
      try {
        await onPick$(descriptor.key, { ...active.values });
        hide();
      } catch (err) {
        active.error = err instanceof Error ? err.message : String(err);
      } finally {
        active.submitting = false;
      }
    });

    return (
      <>
        <div class={[styles.panel, className]} style={style}>
          {prompts.length === 0 ? (
            <div class={styles.empty}>No prompts available.</div>
          ) : (
            prompts.map((p) => (
              <div
                key={p.key}
                class={styles["prompt-row"]}
                onClick$={() => onRowClick$(p)}
              >
                <div class={styles["prompt-head"]}>
                  <span class={styles["prompt-name"]}>{p.name}</span>
                </div>
                {p.description && (
                  <span class={styles["prompt-description"]}>
                    {p.description}
                  </span>
                )}
              </div>
            ))
          )}
        </div>

        <Modal>
          <div class={styles["modal-card"]}>
            {active.descriptor && (
              <>
                <div class={styles["modal-header"]}>
                  <span class={styles["modal-title"]}>
                    {active.descriptor.name}
                  </span>
                  {active.descriptor.description && (
                    <span class={styles["modal-description"]}>
                      {active.descriptor.description}
                    </span>
                  )}
                </div>

                <div class={styles.form}>
                  {(active.descriptor.arguments ?? []).map((a) => (
                    <label key={a.name} class={styles["field-label"]}>
                      <span class={styles["field-name"]}>
                        {a.name}
                        {a.required && (
                          <span class={styles["field-required"]}>*</span>
                        )}
                      </span>
                      <input
                        class={styles["field-input"]}
                        type="text"
                        placeholder={a.description}
                        value={active.values[a.name] ?? ""}
                        aria-required={a.required}
                        onInput$={(_, el: HTMLInputElement) => {
                          active.values[a.name] = el.value;
                        }}
                      />
                    </label>
                  ))}
                  {active.error && (
                    <div class={styles.error}>{active.error}</div>
                  )}
                </div>

                <div class={styles["form-actions"]}>
                  <button
                    type="button"
                    class={styles["cancel-button"]}
                    onClick$={onCancel$}
                  >
                    Cancel
                  </button>
                  <button
                    type="button"
                    class={styles["use-button"]}
                    disabled={active.submitting}
                    onClick$={onSubmit$}
                  >
                    {active.submitting ? "Resolving…" : "Use prompt"}
                  </button>
                </div>
              </>
            )}
          </div>
        </Modal>
      </>
    );
  },
);

// packages/solid/src/components/ag-ui-client/components/elm-ag-ui-prompt-picker.tsx
/* eslint-disable solid/reactivity -- createMutable is intentionally mutated in place. */
import {
  createEffect,
  For,
  onCleanup,
  Show,
  splitProps,
  type Accessor,
  type JSX,
} from "solid-js";
import { createMutable } from "solid-js/store";
import { clsx } from "clsx";

import { createModal } from "../../../primitives/create-modal";
import styles from "./elm-ag-ui-prompt-picker.module.css";

export interface ElmAgUiPromptDescriptor {
  key: string;
  name: string;
  description?: string;
  arguments?: ElmAgUiPromptArgument[];
}

export interface ElmAgUiPromptArgument {
  name: string;
  description?: string;
  required?: boolean;
  enum?: string[];
  pattern?: string;
  patternMessage?: string;
  default?: string;
}

export interface ElmAgUiPromptPickerProps extends JSX.HTMLAttributes<HTMLDivElement> {
  prompts: ElmAgUiPromptDescriptor[];
  onPick: (key: string, args: Record<string, string>) => Promise<void> | void;
  activeIndex?: number;
  triggerDescriptor?: Accessor<ElmAgUiPromptDescriptor | null>;
  clearTriggerDescriptor?: () => void;
}

interface ActivePrompt {
  descriptor: ElmAgUiPromptDescriptor | null;
  values: Record<string, string>;
  submitting: boolean;
  error: string | null;
}

export const ElmAgUiPromptPicker = (props: ElmAgUiPromptPickerProps) => {
  const [local, rest] = splitProps(props, [
    "class",
    "children",
    "prompts",
    "onPick",
    "activeIndex",
    "triggerDescriptor",
    "clearTriggerDescriptor",
  ]);
  const { Modal, show, hide } = createModal();
  const active = createMutable<ActivePrompt>({
    descriptor: null,
    values: {},
    submitting: false,
    error: null,
  });
  let firstField: HTMLInputElement | HTMLSelectElement | undefined;

  createEffect(() => {
    if (!active.descriptor) {
      return;
    }
    const frame = requestAnimationFrame(() => firstField?.focus());
    onCleanup(() => cancelAnimationFrame(frame));
  });

  const selectPrompt = async (descriptor: ElmAgUiPromptDescriptor) => {
    const args = descriptor.arguments ?? [];
    if (args.length === 0) {
      await local.onPick(descriptor.key, {});
      return;
    }
    active.values = Object.fromEntries(
      args.map((argument) => [
        argument.name,
        argument.default ?? argument.enum?.[0] ?? "",
      ]),
    );
    active.descriptor = descriptor;
    active.submitting = false;
    active.error = null;
    show();
  };

  createEffect(() => {
    const descriptor = local.triggerDescriptor?.();
    if (!descriptor) {
      return;
    }
    local.clearTriggerDescriptor?.();
    void selectPrompt(descriptor);
  });

  const cancel = () => {
    hide();
    active.error = null;
  };

  const submit = async () => {
    const descriptor = active.descriptor;
    if (!descriptor) {
      return;
    }
    const args = descriptor.arguments ?? [];
    for (const argument of args) {
      if (argument.required && !(active.values[argument.name] ?? "").trim()) {
        active.error = `"${argument.name}" is required.`;
        return;
      }
    }

    const payload: Record<string, string> = {};
    for (const argument of args) {
      const value = active.values[argument.name] ?? "";
      if (argument.required || value !== "") {
        payload[argument.name] = value;
      }
    }
    for (const argument of args) {
      if (!argument.pattern || payload[argument.name] === undefined) {
        continue;
      }
      const source = /^\^|\$$/.test(argument.pattern)
        ? argument.pattern
        : `^(?:${argument.pattern})$`;
      let expression: RegExp;
      try {
        expression = new RegExp(source);
      } catch {
        active.error = `"${argument.name}" has an invalid pattern definition.`;
        return;
      }
      if (!expression.test(payload[argument.name])) {
        active.error =
          argument.patternMessage ?? `"${argument.name}" is invalid.`;
        return;
      }
    }

    active.error = null;
    active.submitting = true;
    try {
      await local.onPick(descriptor.key, payload);
      hide();
    } catch (error) {
      active.error = error instanceof Error ? error.message : String(error);
    } finally {
      active.submitting = false;
    }
  };

  return (
    <>
      <div {...rest} class={clsx(styles.panel, local.class)}>
        <Show
          when={local.prompts.length > 0}
          fallback={<div class={styles.empty}>No prompts available.</div>}
        >
          <For each={local.prompts}>
            {(prompt, index) => (
              <button
                type="button"
                class={clsx(
                  styles["prompt-row"],
                  index() === local.activeIndex && styles["prompt-row-active"],
                )}
                onClick={() => void selectPrompt(prompt)}
              >
                <span class={styles["prompt-head"]}>
                  <span class={styles["prompt-name"]}>{prompt.name}</span>
                </span>
                <Show when={prompt.description} keyed>
                  {(description) => (
                    <span class={styles["prompt-description"]}>
                      {description}
                    </span>
                  )}
                </Show>
              </button>
            )}
          </For>
        </Show>
      </div>

      <Modal>
        <div class={styles["modal-card"]}>
          <Show when={active.descriptor} keyed>
            {(descriptor) => (
              <>
                <div class={styles["modal-header"]}>
                  <span class={styles["modal-title"]}>{descriptor.name}</span>
                  <Show when={descriptor.description} keyed>
                    {(description) => (
                      <span class={styles["modal-description"]}>
                        {description}
                      </span>
                    )}
                  </Show>
                </div>
                <div class={styles.form}>
                  <For each={descriptor.arguments ?? []}>
                    {(argument, index) => (
                      <label class={styles["field-label"]}>
                        <span class={styles["field-name"]}>
                          {argument.name}
                          <Show when={argument.required}>
                            <span class={styles["field-required"]}>*</span>
                          </Show>
                        </span>
                        <Show
                          when={argument.enum?.length}
                          fallback={
                            <input
                              ref={(element) => {
                                if (index() === 0) {
                                  firstField = element;
                                }
                              }}
                              class={styles["field-input"]}
                              type="text"
                              placeholder={argument.description}
                              value={active.values[argument.name] ?? ""}
                              aria-required={argument.required}
                              pattern={argument.pattern}
                              title={
                                argument.patternMessage ?? argument.description
                              }
                              onInput={(event) => {
                                active.values[argument.name] =
                                  event.currentTarget.value;
                              }}
                            />
                          }
                        >
                          <select
                            ref={(element) => {
                              if (index() === 0) {
                                firstField = element;
                              }
                            }}
                            class={styles["field-input"]}
                            value={active.values[argument.name] ?? ""}
                            aria-required={argument.required}
                            onChange={(event) => {
                              active.values[argument.name] =
                                event.currentTarget.value;
                            }}
                          >
                            <Show when={!argument.required}>
                              <option value="">(none)</option>
                            </Show>
                            <For each={argument.enum}>
                              {(value) => (
                                <option value={value}>{value}</option>
                              )}
                            </For>
                          </select>
                        </Show>
                        <Show when={argument.enum && argument.description}>
                          <span class={styles["field-hint"]}>
                            {argument.description}
                          </span>
                        </Show>
                      </label>
                    )}
                  </For>
                  <Show when={active.error} keyed>
                    {(error) => <div class={styles.error}>{error}</div>}
                  </Show>
                </div>
                <div class={styles["form-actions"]}>
                  <button
                    type="button"
                    class={styles["cancel-button"]}
                    onClick={cancel}
                  >
                    Cancel
                  </button>
                  <button
                    type="button"
                    class={styles["use-button"]}
                    disabled={active.submitting}
                    onClick={() => void submit()}
                  >
                    {active.submitting ? "Resolving..." : "Use prompt"}
                  </button>
                </div>
              </>
            )}
          </Show>
        </div>
      </Modal>
    </>
  );
};
