// packages/qwik/src/components/ag-ui-client/elm-ag-ui-message-renderer.tsx
import {
  component$,
  JSX,
  QRL,
  useSignal,
  useVisibleTask$,
  type CSSProperties,
} from "@qwik.dev/core";

import styles from "./elm-ag-ui-message-renderer.module.css";
import {
  ActivityMessage,
  Message,
  EventType,
  ToolCallResultEvent,
  ToolCall,
} from "@ag-ui/core";
import { ElmInlineText } from "../typography/elm-inline-text";
import { ElmMarkdown } from "../others/elm-markdown";
import { ElmMdiIcon } from "../icon/elm-mdi-icon";
import { mdiAccount, mdiCreation, mdiLightbulbOn, mdiRefresh } from "@mdi/js";
import { ElmAgUiToolExecution } from "./elm-ag-ui-tool-execution";
import { ElmCopyIcon } from "../icon/elm-copy-icon";
import { ElmToggle } from "../containments/elm-toggle";
import { ElmA2uiRenderer } from "../a2ui/elm-a2ui-renderer";
import { ElmAgUiInputContent } from "./input-content/elm-ag-ui-input-content";

export interface ElmAgUiMessageRendererProps {
  class?: string;

  style?: CSSProperties;

  handleRetry$: QRL<() => void>;

  isRunning: boolean;

  messages: Message[];
}

export const ElmAgUiMessageRenderer = component$<ElmAgUiMessageRendererProps>(
  ({ class: className, style, messages, isRunning, handleRetry$ }) => {
    const renderTool = (toolCall: ToolCall, messages: Message[]) => {
      let toolEventType = EventType.TOOL_CALL_START;

      if (toolCall.function.arguments != null)
        toolEventType = EventType.TOOL_CALL_ARGS;

      const toolCallResultEvent = messages.find(
        (message) =>
          message.role === "tool" &&
          message.toolCallId === toolCall.id &&
          message.content != null,
      ) as ToolCallResultEvent | undefined;

      if (toolCallResultEvent?.content != null)
        toolEventType = EventType.TOOL_CALL_RESULT;

      return (
        <ElmAgUiToolExecution
          toolName={toolCall.function.name}
          toolEventType={toolEventType}
          toolCallArgs={toolCall.function.arguments}
          toolCallResult={toolCallResultEvent?.content}
        />
      );
    };

    const render = (message: Message, index: number): JSX.Element | null => {
      switch (message.role) {
        case "activity": {
          const activity = message as ActivityMessage;
          if (activity.activityType === "a2ui-surface") {
            const ops = activity.content["a2ui_operations"] as object[];
            return <ElmA2uiRenderer messages={ops} />;
          }
          return null;
        }

        case "assistant": {
          if (message.content != null || message.toolCalls?.length) {
            return (
              <>
                {message.toolCalls?.map((toolCall) =>
                  renderTool(toolCall, messages),
                )}

                {message.content != null && (
                  <div class={styles["message-content-assistant-wrapper"]}>
                    <div class={styles["message-content-type"]}>
                      <ElmMdiIcon
                        class={styles["message-content-icon"]}
                        d={mdiCreation}
                      />
                      <ElmInlineText>Assistant</ElmInlineText>
                      <div
                        aria-hidden="true"
                        class={styles["message-content-spacer"]}
                      ></div>
                    </div>

                    <ElmMarkdown markdown={message.content} streaming={true} />

                    {!isRunning && (
                      <div class={styles["message-content-assistant-actions"]}>
                        <ElmCopyIcon content={message.content} />

                        <span
                          class={styles["clickable-icon"]}
                          onClick$={handleRetry$}
                        >
                          <ElmMdiIcon d={mdiRefresh} size="1.25rem" />
                        </span>
                      </div>
                    )}
                  </div>
                )}
              </>
            );
          }

          return null;
        }

        case "developer": {
          return null;
        }

        case "reasoning": {
          const Reasoning = component$(
            ({
              isReasoningRunning,
              markdown,
            }: {
              isReasoningRunning: boolean;
              markdown: string;
            }) => {
              const reasoningRef = useSignal<HTMLElement>();
              const lastScrollTime = useSignal(0);

              // eslint-disable-next-line qwik/no-use-visible-task
              useVisibleTask$(({ track }) => {
                track(() => markdown);
                const now = Date.now();
                if (now - lastScrollTime.value < 500) return;
                lastScrollTime.value = now;
                reasoningRef.value?.scrollTo({
                  behavior: "smooth",
                  top: reasoningRef.value.scrollHeight,
                });
              });

              const ReasoningMarkdown = component$(
                ({ markdown }: { markdown: string }) => {
                  const markdownRef = useSignal<HTMLElement>();

                  return (
                    <div ref={markdownRef}>
                      <ElmMarkdown
                        style={{ opacity: 0.5 }}
                        markdown={markdown}
                        streaming={true}
                      />
                    </div>
                  );
                },
              );

              return (
                <ElmToggle isOpen={isReasoningRunning} monochrome>
                  <div q:slot="summary" class={styles["message-content-type"]}>
                    <ElmMdiIcon
                      class={styles["message-content-icon"]}
                      d={mdiLightbulbOn}
                    />
                    <ElmInlineText>Reasoning</ElmInlineText>
                    <div
                      aria-hidden="true"
                      class={styles["message-content-spacer"]}
                    ></div>
                  </div>

                  <div
                    ref={reasoningRef}
                    class={[
                      {
                        [styles["reasoning-running"]]: isReasoningRunning,
                      },
                    ]}
                  >
                    <ReasoningMarkdown markdown={markdown} />
                  </div>
                </ElmToggle>
              );
            },
          );

          return (
            <Reasoning
              isReasoningRunning={messages.length - 1 === index}
              markdown={message.content}
            />
          );
        }

        case "system": {
          return null;
        }

        case "tool": {
          // Tool messages are rendered within the assistant message that triggered the tool call,
          // so we can skip rendering them here in the main message loop
          return null;
        }

        case "user": {
          const contentToText = () => {
            if (typeof message.content === "string") return message.content;

            if (Array.isArray(message.content)) {
              return message.content
                .map((item) =>
                  typeof item === "string"
                    ? item
                    : item.type === "text"
                      ? item.text
                      : "",
                )
                .join(" ");
            }

            return "";
          };

          return (
            <div class={styles["message-content-user-wrapper"]}>
              <div class={styles["message-content-user-inner"]}>
                <div class={styles["message-content-type"]}>
                  <ElmMdiIcon
                    class={styles["message-content-icon"]}
                    d={mdiAccount}
                  />
                  <ElmInlineText>User</ElmInlineText>
                  <div
                    aria-hidden="true"
                    class={styles["message-content-spacer"]}
                  ></div>
                </div>

                <ElmAgUiInputContent inputContent={message.content} />

                <div>
                  <ElmCopyIcon content={contentToText()} />
                </div>
              </div>
            </div>
          );
        }
      }
    };

    return (
      <div class={[styles["elm-my-something"], className]} style={style}>
        {messages.map((msg, i) => (
          <div key={msg.id ?? i}>{render(msg, i)}</div>
        ))}
      </div>
    );
  },
);

// packages/solid/src/components/ag-ui-client/components/elm-ag-ui-message-renderer.tsx
import {
  createEffect,
  createSignal,
  For,
  Show,
  splitProps,
  type JSX,
} from "solid-js";
import { clsx } from "clsx";
import { mdiAccount, mdiCreation, mdiLightbulbOn, mdiRefresh } from "@mdi/js";
import {
  EventType,
  type ActivityMessage,
  type Message,
  type ToolCall,
} from "@ag-ui/core";

import { ElmA2ui } from "../../a2ui/elm-a2ui";
import { ElmToggle } from "../../containments/elm-toggle";
import { ElmCopyIcon } from "../../icon/elm-copy-icon";
import { ElmMdiIcon } from "../../icon/elm-mdi-icon";
import { ElmMarkdown } from "../../others/elm-markdown";
import { ElmInlineText } from "../../typography/elm-inline-text";
import { ElmAgUiInputContent } from "./input-content/elm-ag-ui-input-content";
import { ElmAgUiToolExecution } from "./elm-ag-ui-tool-execution";
import styles from "./elm-ag-ui-message-renderer.module.css";

export interface ElmAgUiMessageRendererProps extends JSX.HTMLAttributes<HTMLDivElement> {
  handleRetry: () => void;
  isRunning: boolean;
  messages: Message[];
  enableToolCalls?: boolean;
  enableReasoning?: boolean;
}

interface ReasoningProps {
  isReasoningRunning: boolean;
  markdown: string;
}

const Reasoning = (props: ReasoningProps) => {
  const [isOpen, setIsOpen] = createSignal(false);
  let reasoningRef!: HTMLDivElement;
  let lastScrollTime = 0;

  createEffect(() => setIsOpen(props.isReasoningRunning));
  createEffect(() => {
    const markdown = props.markdown;
    if (!reasoningRef || markdown === "") return;
    const now = Date.now();
    if (now - lastScrollTime < 500) return;
    lastScrollTime = now;
    reasoningRef.scrollTo({
      behavior: "smooth",
      top: reasoningRef.scrollHeight,
    });
  });

  return (
    <ElmToggle
      isOpen={isOpen()}
      onOpenChange={setIsOpen}
      monochrome
      summary={
        <div class={styles["message-content-type"]}>
          <ElmMdiIcon
            class={styles["message-content-icon"]}
            d={mdiLightbulbOn}
          />
          <ElmInlineText>Reasoning</ElmInlineText>
          <div aria-hidden="true" class={styles["message-content-spacer"]} />
        </div>
      }
    >
      <div
        ref={(element) => {
          reasoningRef = element;
        }}
        class={clsx(props.isReasoningRunning && styles["reasoning-running"])}
      >
        <ElmMarkdown
          style={{ opacity: 0.5 }}
          markdown={props.markdown}
          isStreaming
        />
      </div>
    </ElmToggle>
  );
};

const contentToText = (message: Message): string => {
  if (typeof message.content === "string") return message.content;
  if (!Array.isArray(message.content)) return "";
  return message.content
    .map((item) =>
      typeof item === "string" ? item : item.type === "text" ? item.text : "",
    )
    .join(" ");
};

export const ElmAgUiMessageRenderer = (props: ElmAgUiMessageRendererProps) => {
  const [local, rest] = splitProps(props, [
    "class",
    "children",
    "handleRetry",
    "isRunning",
    "messages",
    "enableToolCalls",
    "enableReasoning",
  ]);

  const renderTool = (toolCall: ToolCall) => {
    const result = () =>
      local.messages.find(
        (message) =>
          message.role === "tool" &&
          message.toolCallId === toolCall.id &&
          message.content != null,
      );
    const eventType = () => {
      if (result()?.content != null) return EventType.TOOL_CALL_RESULT;
      if (toolCall.function.arguments != null) return EventType.TOOL_CALL_ARGS;
      return EventType.TOOL_CALL_START;
    };
    const resultContent = () => {
      const content = result()?.content;
      return typeof content === "string" ? content : undefined;
    };
    return (
      <ElmAgUiToolExecution
        toolName={toolCall.function.name}
        toolEventType={eventType()}
        toolCallArgs={toolCall.function.arguments}
        toolCallResult={resultContent()}
      />
    );
  };

  const renderMessage = (
    message: Message,
    index: () => number,
  ): JSX.Element => {
    switch (message.role) {
      case "activity": {
        const activity = message as ActivityMessage;
        return activity.activityType === "a2ui-surface" ? (
          <ElmA2ui messages={activity.content["a2ui_operations"] as object[]} />
        ) : undefined;
      }
      case "assistant":
        return (
          <>
            <Show when={local.enableToolCalls !== false}>
              <For each={message.toolCalls}>{renderTool}</For>
            </Show>
            <Show when={message.content} keyed>
              {(content) => (
                <div class={styles["message-content-assistant-wrapper"]}>
                  <div class={styles["message-content-type"]}>
                    <ElmMdiIcon
                      class={styles["message-content-icon"]}
                      d={mdiCreation}
                    />
                    <ElmInlineText>Assistant</ElmInlineText>
                    <div
                      aria-hidden="true"
                      class={styles["message-content-spacer"]}
                    />
                  </div>
                  <ElmMarkdown markdown={content} isStreaming />
                  <Show when={!local.isRunning}>
                    <div class={styles["message-content-assistant-actions"]}>
                      <ElmCopyIcon content={content} />
                      <button
                        type="button"
                        class={styles["clickable-icon"]}
                        onClick={local.handleRetry}
                        aria-label="Retry"
                      >
                        <ElmMdiIcon d={mdiRefresh} size="1.25rem" />
                      </button>
                    </div>
                  </Show>
                </div>
              )}
            </Show>
          </>
        );
      case "reasoning":
        return (
          <Show when={local.enableReasoning !== false}>
            <Reasoning
              isReasoningRunning={local.messages.length - 1 === index()}
              markdown={message.content}
            />
          </Show>
        );
      case "user":
        return (
          <div class={styles["message-content-user-wrapper"]}>
            <div class={styles["message-content-user-inner"]}>
              <div class={styles["message-content-type"]}>
                <ElmMdiIcon
                  class={styles["message-content-icon"]}
                  d={mdiAccount}
                />
                <ElmInlineText>User</ElmInlineText>
                <div
                  aria-hidden="true"
                  class={styles["message-content-spacer"]}
                />
              </div>
              <ElmAgUiInputContent inputContent={message.content} />
              <ElmCopyIcon content={contentToText(message)} />
            </div>
          </div>
        );
      case "developer":
      case "system":
      case "tool":
        return undefined;
    }
  };

  return (
    <div
      {...rest}
      class={clsx(styles["elm-ag-ui-message-renderer"], local.class)}
    >
      <For each={local.messages}>
        {(message, index) => <div>{renderMessage(message, index)}</div>}
      </For>
    </div>
  );
};
