// packages/react/src/components/navigation/elm-page-top.tsx
import {
  useEffect,
  useState,
  type ComponentPropsWithoutRef,
  type CSSProperties,
} from "react";
import { clsx } from "clsx";

import styles from "./elm-page-top.module.css";

export interface ElmPageTopProps extends ComponentPropsWithoutRef<"nav"> {
  /**
   * Specifies the position of the button.
   */
  position?: "left" | "right";
}

export const ElmPageTop = ({
  className,
  style,
  position = "right",
  ...props
}: ElmPageTopProps) => {
  const [isVisible, setIsVisible] = useState(false);

  // Initial check and scroll listener
  useEffect(() => {
    const checkScroll = () => {
      setIsVisible(window.scrollY > 100);
    };

    window.addEventListener("scroll", checkScroll, { passive: true });
    checkScroll(); // Check initial state

    return () => window.removeEventListener("scroll", checkScroll);
  }, []);

  const toTop = () => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  return (
    <nav
      className={clsx(
        styles["elm-page-top"],
        isVisible && styles.visible,
        className,
      )}
      style={
        {
          "--elmethis-scoped-size": `${64}px`,
          left: position === "left" ? "0" : "auto",
          right: position === "right" ? "0" : "auto",
          ...style,
        } as CSSProperties
      }
      onClick={toTop}
      {...props}
    >
      <div aria-hidden="true" className={styles.partial}></div>
      <div aria-hidden="true" className={styles.partial}></div>
      <div aria-hidden="true" className={styles.partial}></div>
      <span className={styles.text}>Back to Top</span>
    </nav>
  );
};

// packages/qwik/src/components/navigation/elm-page-top.tsx
import {
  component$,
  useSignal,
  useVisibleTask$,
  $,
  type CSSProperties,
} from "@builder.io/qwik";

import styles from "./elm-page-top.module.css";

export interface ElmPageTopProps {
  class?: string;

  style?: CSSProperties;

  /**
   * Specifies the position of the button.
   */
  position?: "left" | "right";
}

export const ElmPageTop = component$<ElmPageTopProps>(
  ({ class: className, style, position = "right" }) => {
    const isVisible = useSignal(false);

    // Initial check and scroll listener
    // eslint-disable-next-line qwik/no-use-visible-task
    useVisibleTask$(
      ({ cleanup }) => {
        const checkScroll = () => {
          isVisible.value = window.scrollY > 100;
        };

        window.addEventListener("scroll", checkScroll, { passive: true });
        checkScroll(); // Check initial state

        cleanup(() => window.removeEventListener("scroll", checkScroll));
      },
      { strategy: "document-idle" },
    );

    const toTop = $(() => {
      window.scrollTo({ top: 0, behavior: "smooth" });
    });

    return (
      <nav
        class={[
          styles.wrapper,
          { [styles["wrapper--visible"]]: isVisible.value },
          className,
        ]}
        style={{
          "--size": `${64}px`,
          left: position === "left" ? "0" : "auto",
          right: position === "right" ? "0" : "auto",
          ...style,
        }}
        onClick$={toTop}
      >
        <div aria-hidden="true" class={styles.partial}></div>
        <div aria-hidden="true" class={styles.partial}></div>
        <div aria-hidden="true" class={styles.partial}></div>
        <span class={styles.text}>Back to Top</span>
      </nav>
    );
  },
);
