// packages/vue/src/components/others/ElmMarkdown.vue
<template>
  <div>
    <component v-for="component in components" :is="component" />
  </div>
</template>

<script setup lang="ts">
import { marked, type Token, type Tokens } from "marked";
import { h, watch, ref, type VNode, computed } from "vue";
import ElmInlineText from "../typography/ElmInlineText.vue";
import ElmHeading from "../typography/ElmHeading.vue";
import ElmParagraph from "../typography/ElmParagraph.vue";
import ElmList from "../typography/ElmList.vue";
import ElmBlockQuote from "../typography/ElmBlockQuote.vue";
import ElmDivider from "../typography/ElmDivider.vue";
import ElmImage from "../media/ElmImage.vue";
import ElmCodeBlock from "../code/ElmCodeBlock.vue";
import ElmTable from "../table/ElmTable.vue";
import ElmTableHeader from "../table/ElmTableHeader.vue";
import ElmTableBody from "../table/ElmTableBody.vue";
import ElmTableRow from "../table/ElmTableRow.vue";
import ElmTableCell from "../table/ElmTableCell.vue";

export interface ElmMarkdownProps {
  markdown: string;
}

const props = withDefaults(defineProps<ElmMarkdownProps>(), {});

const renderByToken = ({ tokens }: { tokens: Token[] }): VNode[] => {
  const results: VNode[] = [];

  for (const token of tokens) {
    switch (token.type) {
      case "blockquote":
        if (token.tokens != null && token.tokens.length !== 0) {
          results.push(
            h(
              ElmBlockQuote,
              {},
              {
                default: () =>
                  renderByToken({ tokens: token.tokens as Token[] }),
              },
            ),
          );
        }
        break;
      case "br":
        results.push(h("br"));
        break;
      case "code":
        results.push(
          h(ElmCodeBlock, {
            code: token.text.trim(),
            language: token.lang,
          }),
        );
        break;
      case "codespan":
        results.push(h(ElmInlineText, { text: token.text, code: true }));
        break;
      case "def":
        h("span", "aaa");
        // Link reference definitions
        break;
      case "del":
        results.push(
          token.tokens != null && token.tokens.length !== 0
            ? h(
                ElmInlineText,
                { strikethrough: true },
                {
                  default: () =>
                    renderByToken({ tokens: token.tokens as Token[] }),
                },
              )
            : h(ElmInlineText, { text: token.text, strikethrough: true }),
        );
        break;
      case "em":
        results.push(
          token.tokens != null && token.tokens.length !== 0
            ? h(
                ElmInlineText,
                { italic: true },
                {
                  default: () =>
                    renderByToken({ tokens: token.tokens as Token[] }),
                },
              )
            : h(ElmInlineText, { text: token.text, italic: true }),
        );
        break;
      case "escape":
        // Escape token
        break;
      case "heading":
        if (token.tokens && token.tokens.length !== 0) {
          results.push(
            h(
              ElmHeading,
              { level: token.depth },
              {
                default: () =>
                  renderByToken({ tokens: token.tokens as Token[] }),
              },
            ),
          );
        } else {
          results.push(h(ElmHeading, { level: token.depth, text: token.text }));
        }
        break;
      case "hr":
        results.push(h(ElmDivider));
        break;
      case "html":
        // HTML token
        break;
      case "image":
        results.push(
          h(ElmImage, {
            block: true,
            enableModal: true,
            src: token.href,
            alt: token.text,
          }),
        );
        break;
      case "link":
        results.push(
          token.tokens != null && token.tokens.length !== 0
            ? h(ElmInlineText, {
                text: token.text,
                href: token.href,
              })
            : h(ElmInlineText, { text: token.text, href: token.href }),
        );
        break;
      case "list":
        const listItems = token.items.map((item: any) =>
          h("li", {}, renderByToken({ tokens: item.tokens })),
        );
        results.push(
          h(
            ElmList,
            {
              listStyle: token.ordered ? "ordered" : "unordered",
            },
            { default: () => listItems },
          ),
        );
        break;
      case "list_item":
        results.push(
          token.tokens != null && token.tokens.length !== 0
            ? h(
                "li",
                {},
                {
                  default: () =>
                    renderByToken({ tokens: token.tokens as Token[] }),
                },
              )
            : h("li", { text: token.text }),
        );
        break;
      case "paragraph":
        if (token.tokens && token.tokens.length !== 0) {
          results.push(
            h(
              ElmParagraph,
              {},
              {
                default: () =>
                  renderByToken({ tokens: token.tokens as Token[] }),
              },
            ),
          );
        }
        break;
      case "space":
        break;
      case "strong":
        results.push(
          token.tokens != null && token.tokens.length !== 0
            ? h(
                ElmInlineText,
                { bold: true },
                {
                  default: () =>
                    renderByToken({ tokens: token.tokens as Token[] }),
                },
              )
            : h(ElmInlineText, { text: token.text, bold: true }),
        );
        break;
      case "table":
        const renderTableCells = ({
          cells,
        }: {
          cells: Tokens.TableCell[];
        }): VNode[] =>
          cells.map((cell: Tokens.TableCell) =>
            h(
              ElmTableCell,
              {},
              { default: () => renderByToken({ tokens: cell.tokens }) },
            ),
          );

        const headerRow = h(
          ElmTableRow,
          {},
          { default: () => renderTableCells({ cells: token.header }) },
        );

        const bodyRows = token.rows.map((row: Tokens.TableCell[]) =>
          h(
            ElmTableRow,
            {},
            { default: () => renderTableCells({ cells: row }) },
          ),
        );

        const table = h(
          ElmTable,
          {},
          {
            header: () => h(ElmTableHeader, {}, { default: () => headerRow }),
            body: () => h(ElmTableBody, {}, { default: () => bodyRows }),
          },
        );

        results.push(table);

        break;
      case "text":
        results.push(
          token.tokens != null && token.tokens.length !== 0
            ? h(
                ElmInlineText,
                {},
                {
                  default: () =>
                    renderByToken({ tokens: token.tokens as Token[] }),
                },
              )
            : h(ElmInlineText, { text: token.text }),
        );
        break;
      default:
        // Generic or unknown token
        break;
    }
  }

  return results;
};

const renderMarkdown = ({ markdown }: { markdown: string }): VNode[] => {
  const tokens = marked.setOptions({ gfm: true }).lexer(markdown);
  return renderByToken({ tokens });
};

const renderResult = ref<VNode[]>(renderMarkdown({ markdown: props.markdown }));

const components = computed(() => ({
  render: () => renderResult.value,
}));

watch(
  () => props.markdown,
  (md) => {
    if (md != null) renderResult.value = renderMarkdown({ markdown: md });
  },
);
</script>

// packages/react/src/components/others/ElmMarkdown.tsx
import React from "react";
import { marked, type Token, type Tokens } from "marked";

import "@styles/global.css";
import styles from "./ElmMarkdown.module.css";

import { ElmInlineText } from "../typography/ElmInlineText";
import { ElmHeading } from "../typography/ElmHeading";
import { ElmParagraph } from "../typography/ElmParagraph";
import { ElmList } from "../typography/ElmList";
import { ElmBlockQuote } from "../typography/ElmBlockQuote";
import { ElmDivider } from "../typography/ElmDivider";
import { ElmImage } from "../media/ElmImage";
import { ElmCodeBlock } from "../code/ElmCodeBlock";
import { ElmTable } from "../table/ElmTable";
import { ElmTableHeader } from "../table/ElmTableHeader";
import { ElmTableBody } from "../table/ElmTableBody";
import { ElmTableRow } from "../table/ElmTableRow";
import { ElmTableCell } from "../table/ElmTableCell";

export interface ElmMarkdownProps {
  style?: React.CSSProperties;

  /**
   * The markdown string to render.
   */
  markdown: string;
}

const renderByToken = (tokens: Token[]): React.ReactNode[] => {
  const results: React.ReactNode[] = [];

  for (const token of tokens) {
    switch (token.type) {
      case "blockquote":
        if (token.tokens && token.tokens.length !== 0) {
          const innerTokens = (token.tokens as Token[]).flatMap((t) =>
            t.type === "paragraph" && (t as Tokens.Paragraph).tokens
              ? ((t as Tokens.Paragraph).tokens as Token[])
              : [t],
          );
          results.push(
            <ElmBlockQuote key={results.length}>
              {renderByToken(innerTokens)}
            </ElmBlockQuote>,
          );
        }
        break;
      case "br":
        results.push(<br key={results.length} />);
        break;
      case "code":
        results.push(
          <ElmCodeBlock
            key={results.length}
            code={token.text.trim()}
            language={token.lang}
          />,
        );
        break;
      case "codespan":
        results.push(
          <ElmInlineText key={results.length} code={true}>
            {token.text}
          </ElmInlineText>,
        );
        break;
      case "def":
        // Link reference definitions (not rendered directly)
        break;
      case "del":
        results.push(
          token.tokens && token.tokens.length !== 0 ? (
            <ElmInlineText key={results.length} strikethrough={true}>
              {renderByToken(token.tokens as Token[])}
            </ElmInlineText>
          ) : (
            <ElmInlineText key={results.length} strikethrough={true}>
              {token.text}
            </ElmInlineText>
          ),
        );
        break;
      case "em":
        results.push(
          token.tokens && token.tokens.length !== 0 ? (
            <ElmInlineText key={results.length} italic={true}>
              {renderByToken(token.tokens as Token[])}
            </ElmInlineText>
          ) : (
            <ElmInlineText key={results.length} italic={true}>
              {token.text}
            </ElmInlineText>
          ),
        );
        break;
      case "escape":
        // Escape token
        break;
      case "heading": {
        const level = token.depth as 1 | 2 | 3 | 4 | 5 | 6;
        if (token.tokens && token.tokens.length !== 0) {
          results.push(
            <ElmHeading key={results.length} level={level}>
              {renderByToken(token.tokens as Token[])}
            </ElmHeading>,
          );
        } else {
          results.push(
            <ElmHeading key={results.length} level={level} text={token.text} />,
          );
        }
        break;
      }
      case "hr":
        results.push(<ElmDivider key={results.length} />);
        break;
      case "html":
        // HTML token
        break;
      case "image":
        results.push(
          <ElmImage
            key={results.length}
            block={true}
            enableModal={true}
            src={token.href}
            alt={token.text}
          />,
        );
        break;
      case "link":
        results.push(
          token.tokens && token.tokens.length !== 0 ? (
            <ElmInlineText key={results.length} href={token.href}>
              {renderByToken(token.tokens as Token[])}
            </ElmInlineText>
          ) : (
            <ElmInlineText key={results.length} href={token.href}>
              {token.text}
            </ElmInlineText>
          ),
        );
        break;
      case "list": {
        const listItems = token.items.map(
          (item: Tokens.ListItem, index: number) => (
            <li key={index}>{renderByToken(item.tokens)}</li>
          ),
        );
        results.push(
          <ElmList
            key={results.length}
            listStyle={token.ordered ? "ordered" : "unordered"}
          >
            {listItems}
          </ElmList>,
        );
        break;
      }
      case "list_item":
        results.push(
          <li key={results.length}>
            {token.tokens && token.tokens.length !== 0
              ? renderByToken(token.tokens as Token[])
              : token.text}
          </li>,
        );
        break;
      case "paragraph":
        if (token.tokens && token.tokens.length !== 0) {
          results.push(
            <ElmParagraph key={results.length}>
              {renderByToken(token.tokens as Token[])}
            </ElmParagraph>,
          );
        }
        break;
      case "space":
        break;
      case "strong":
        results.push(
          token.tokens && token.tokens.length !== 0 ? (
            <ElmInlineText key={results.length} bold={true}>
              {renderByToken(token.tokens as Token[])}
            </ElmInlineText>
          ) : (
            <ElmInlineText key={results.length} bold={true}>
              {token.text}
            </ElmInlineText>
          ),
        );
        break;
      case "table": {
        const renderTableCells = (
          cells: Tokens.TableCell[],
        ): React.ReactNode[] =>
          cells.map((cell: Tokens.TableCell, index: number) => (
            <ElmTableCell key={index}>
              {renderByToken(cell.tokens)}
            </ElmTableCell>
          ));

        const headerRow = (
          <ElmTableRow>{renderTableCells(token.header)}</ElmTableRow>
        );

        const bodyRows = token.rows.map(
          (row: Tokens.TableCell[], index: number) => (
            <ElmTableRow key={index}>{renderTableCells(row)}</ElmTableRow>
          ),
        );

        results.push(
          <ElmTable
            key={results.length}
            header={<ElmTableHeader>{headerRow}</ElmTableHeader>}
            body={<ElmTableBody>{bodyRows}</ElmTableBody>}
          />,
        );
        break;
      }
      case "text":
        results.push(
          token.tokens && token.tokens.length !== 0 ? (
            <ElmInlineText key={results.length}>
              {renderByToken(token.tokens as Token[])}
            </ElmInlineText>
          ) : (
            <React.Fragment key={results.length}>{token.text}</React.Fragment>
          ),
        );
        break;
      default:
        // Generic or unknown token
        break;
    }
  }

  return results;
};

export const ElmMarkdown = ({ markdown, style }: ElmMarkdownProps) => {
  const tokens = marked.setOptions({ gfm: true }).lexer(markdown);
  const elements = renderByToken(tokens);

  return (
    <div className={styles["markdown-body"]} style={style}>
      {elements}
    </div>
  );
};
