// packages/qwik/src/components/a2ui/catalog/catalog-utils.ts
import { type CSSProperties } from "@qwik.dev/core";

/** Maps A2UI `justify` prop values to CSS `justify-content` values. */
export const justifyContentMap: Record<
  string,
  CSSProperties["justifyContent"]
> = {
  start: "flex-start",
  end: "flex-end",
  center: "center",
  spaceBetween: "space-between",
  spaceAround: "space-around",
  spaceEvenly: "space-evenly",
  stretch: "stretch",
};

/** Maps A2UI `align` prop values to CSS `align-items` values. */
export const alignItemsMap: Record<string, CSSProperties["alignItems"]> = {
  start: "flex-start",
  end: "flex-end",
  center: "center",
  stretch: "stretch",
};

/** Maps A2UI `fit` prop values to CSS `object-fit` values. */
export const objectFitMap: Record<string, CSSProperties["objectFit"]> = {
  contain: "contain",
  cover: "cover",
  fill: "fill",
  none: "none",
  scaleDown: "scale-down",
};

// packages/solid/src/components/a2ui/catalog/catalog-utils.ts
import type { JSX } from "solid-js";

export const justifyContentMap: Record<
  string,
  JSX.CSSProperties["justify-content"]
> = {
  start: "flex-start",
  end: "flex-end",
  center: "center",
  spaceBetween: "space-between",
  spaceAround: "space-around",
  spaceEvenly: "space-evenly",
  stretch: "stretch",
};

export const alignItemsMap: Record<string, JSX.CSSProperties["align-items"]> = {
  start: "flex-start",
  end: "flex-end",
  center: "center",
  stretch: "stretch",
};

export const objectFitMap: Record<string, JSX.CSSProperties["object-fit"]> = {
  contain: "contain",
  cover: "cover",
  fill: "fill",
  none: "none",
  scaleDown: "scale-down",
};
