// packages/qwik/src/components/a2ui/catalog/notion-block-catalog.tsx
/**
 * "Block" catalog — typography, media, code, math, table, tabs, and a callout
 * fallback. Composes on top of the basic catalog: most layout primitives
 * (Row, Image, etc.) come from `basicCatalog`; this catalog adds richer block
 * elements that wrap project-specific Elm* components.
 */
import { Fragment, type CSSProperties } from "@qwik.dev/core";

import { ElmKatex } from "../../code/elm-katex";
import { ElmCodeBlock } from "../../code/elm-code-block";
import { ElmHtmlViewer } from "../../code/elm-html-viewer";
import { ElmInlineIcon } from "../../icon/elm-inline-icon";
import { ElmAudioPlayer } from "../../media/elm-audio-player";
import { ElmBlockImage } from "../../media/elm-block-image";
import { ElmFile } from "../../media/elm-file";
import { ElmBookmark } from "../../navigation/elm-bookmark";
import {
  ElmTab,
  ElmTabList,
  ElmTabPanel,
  ElmTabs,
} from "../../containments/elm-tabs";
import { ElmToggle } from "../../containments/elm-toggle";
import { ElmBlockQuote } from "../../typography/elm-block-quote";
import { ElmCallout } from "../../typography/elm-callout";
import { ElmNotionCallout } from "../../notion/elm-notion-callout";
import { ElmDivider } from "../../typography/elm-divider";
import { ElmHeading } from "../../typography/elm-heading";
import { ElmInlineText } from "../../typography/elm-inline-text";
import { ElmList } from "../../typography/elm-list";
import { ElmParagraph } from "../../typography/elm-paragraph";
import {
  ElmTable,
  ElmTableBody,
  ElmTableCell,
  ElmTableHeader,
  ElmTableRow,
} from "../../table";
import { ElmUnsupportedBlock } from "../../fallback/elm-unsupported-block";

import { CatalogRenderer, defineRenderer } from "./catalog";
import { alignItemsMap, justifyContentMap } from "./catalog-utils";
import { basicCatalog } from "./basic-catalog";
import {
  AudioApi,
  BlockImageApi,
  BlockQuoteApi,
  BookmarkApi,
  CalloutApi,
  CodeBlockApi,
  ColumnApi,
  ColumnListApi,
  ContentTabApi,
  ContentTabsApi,
  DividerApi,
  FileApi,
  HeadingApi,
  HtmlApi,
  IconApi,
  KatexApi,
  LinkTextApi,
  ListApi,
  ListItemApi,
  MermaidApi,
  NotionCalloutApi,
  ParagraphApi,
  RichTextApi,
  TableApi,
  TableCellApi,
  TableRowApi,
  ToggleApi,
  UnsupportedApi,
  VideoApi,
} from "@elmethis/core";

/**
 * A `ChildList` is either a static array of component ids or a template
 * `{ componentId, path }`. The Tab renderer only renders the static form
 * today; bound templates resolve to no children until the data layer is
 * wired up. Returns the validated string ids.
 */
function extractChildIds(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  return value.filter((id): id is string => typeof id === "string");
}

// Multi-column layout for the ColumnList block.
const columnListStyle: CSSProperties = {
  boxSizing: "content-box",
  paddingBlock: "0.25rem",
  width: "100%",
  display: "flex",
  flexDirection: "row",
  gap: "0.25rem",
  justifyContent: "space-around",
  overflowX: "auto",
};

/**
 * The Notion block catalog stands on top of the basic catalog. Use it
 * directly (`notionBlockCatalog`) when you want both the basic primitives
 * and the typography block components.
 */
export const notionBlockCatalog: CatalogRenderer = basicCatalog.extend(
  // -------------------------------------------------------------------------
  // Inline components
  // -------------------------------------------------------------------------

  defineRenderer(RichTextApi, ({ props, resolve }) => {
    const text = resolve(props.text);
    const decoration = props.decoration ?? [];
    if (decoration.includes("katex"))
      return <ElmKatex expression={text} block={false} />;
    return (
      <ElmInlineText
        bold={decoration.includes("bold")}
        italic={decoration.includes("italic")}
        underline={decoration.includes("underline")}
        strikethrough={decoration.includes("strikethrough")}
        code={decoration.includes("code")}
        color={props.color}
        ruby={props.ruby}
      >
        {text}
      </ElmInlineText>
    );
  }),

  defineRenderer(LinkTextApi, ({ props, resolve }) => (
    <ElmInlineText href={props.href} favicon={props.favicon}>
      {resolve(props.text)}
    </ElmInlineText>
  )),

  defineRenderer(IconApi, ({ props, resolve }) => (
    <ElmInlineIcon src={resolve(props.src)} alt={props.alt} />
  )),

  // -------------------------------------------------------------------------
  // Layout (overrides Column from basicCatalog with widthRatio support)
  // -------------------------------------------------------------------------

  defineRenderer(ColumnApi, ({ props, childRefs, renderChild }) => (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        justifyContent: justifyContentMap[props.justify ?? "start"],
        alignItems: alignItemsMap[props.align ?? "stretch"],
        flex: props.widthRatio != null ? String(props.widthRatio) : undefined,
        boxSizing: "border-box",
        padding: "0.125rem",
        gap: "var(--elmethis-stack-gap)",
      }}
    >
      {childRefs(props.children).map(({ id, path }, i) => (
        <span key={`${id}:${i}`}>{renderChild(id, path, i)}</span>
      ))}
    </div>
  )),

  defineRenderer(ColumnListApi, ({ props, childRefs, renderChild }) => (
    <div style={columnListStyle}>
      {childRefs(props.children).map(({ id, path }, i) => (
        <Fragment key={`${id}:${i}`}>{renderChild(id, path, i)}</Fragment>
      ))}
    </div>
  )),

  // -------------------------------------------------------------------------
  // Block typography
  // -------------------------------------------------------------------------

  defineRenderer(HeadingApi, ({ props, childRefs, renderChild }) => (
    <ElmHeading level={props.level}>
      {childRefs(props.children).map(({ id, path }, i) => (
        <Fragment key={`${id}:${i}`}>{renderChild(id, path, i)}</Fragment>
      ))}
    </ElmHeading>
  )),

  defineRenderer(ParagraphApi, ({ props, childRefs, renderChild }) => (
    <ElmParagraph color={props.color} backgroundColor={props.backgroundColor}>
      {childRefs(props.children).map(({ id, path }, i) => (
        <span key={`${id}:${i}`}>{renderChild(id, path, i)}</span>
      ))}
    </ElmParagraph>
  )),

  defineRenderer(ListApi, ({ props, childRefs, renderChild }) => (
    <ElmList listStyle={props.style ?? "unordered"}>
      {childRefs(props.children).map(({ id, path }, i) => (
        <li key={`${id}:${i}`}>{renderChild(id, path, i)}</li>
      ))}
    </ElmList>
  )),

  defineRenderer(ListItemApi, ({ props, childRefs, renderChild }) => (
    <>
      {childRefs(props.children).map(({ id, path }, i) => (
        <Fragment key={`${id}:${i}`}>{renderChild(id, path, i)}</Fragment>
      ))}
    </>
  )),

  defineRenderer(BlockQuoteApi, ({ props, childRefs, renderChild }) => (
    <ElmBlockQuote cite={props.cite}>
      {childRefs(props.children).map(({ id, path }, i) => (
        <Fragment key={`${id}:${i}`}>{renderChild(id, path, i)}</Fragment>
      ))}
    </ElmBlockQuote>
  )),

  defineRenderer(CalloutApi, ({ props, childRefs, renderChild }) => (
    <ElmCallout type={props.type}>
      {childRefs(props.children).map(({ id, path }, i) => (
        <Fragment key={`${id}:${i}`}>{renderChild(id, path, i)}</Fragment>
      ))}
    </ElmCallout>
  )),

  defineRenderer(NotionCalloutApi, ({ props, childRefs, renderChild }) => (
    <ElmNotionCallout
      icon={props.icon}
      color={props.color}
      variant={props.variant}
    >
      {childRefs(props.children).map(({ id, path }, i) => (
        <Fragment key={`${id}:${i}`}>{renderChild(id, path, i)}</Fragment>
      ))}
    </ElmNotionCallout>
  )),

  defineRenderer(DividerApi, () => <ElmDivider />),

  defineRenderer(ToggleApi, ({ props, childRefs, renderChild }) => (
    <ElmToggle>
      <div q:slot="summary">
        {childRefs(props.summary).map(({ id, path }, i) => (
          <span key={`${id}:${i}`}>{renderChild(id, path, i)}</span>
        ))}
      </div>
      {childRefs(props.children).map(({ id, path }, i) => (
        <Fragment key={`${id}:${i}`}>{renderChild(id, path, i)}</Fragment>
      ))}
    </ElmToggle>
  )),

  // -------------------------------------------------------------------------
  // Media / embed
  // -------------------------------------------------------------------------

  defineRenderer(BookmarkApi, ({ props, resolve }) => (
    <ElmBookmark
      url={resolve(props.url)}
      title={props.title ? resolve(props.title) : undefined}
      description={props.description ? resolve(props.description) : undefined}
      image={props.image ? resolve(props.image) : undefined}
    />
  )),

  defineRenderer(FileApi, ({ props, resolve }) => (
    <ElmFile
      src={resolve(props.src)}
      name={props.name ? resolve(props.name) : undefined}
    />
  )),

  defineRenderer(AudioApi, ({ props, resolve }) => (
    <ElmAudioPlayer
      src={resolve(props.src)}
      title={props.title ? resolve(props.title) : undefined}
      artist={props.artist ? resolve(props.artist) : undefined}
      seekStep={props.seekStep}
      loop={props.loop}
      autoPlay={props.autoPlay}
    />
  )),

  defineRenderer(VideoApi, ({ props, resolve }) => {
    const caption = props.caption ? resolve(props.caption) : undefined;
    return (
      <figure style={{ margin: 0 }}>
        <video
          src={resolve(props.src)}
          poster={props.poster ? resolve(props.poster) : undefined}
          title={props.title ? resolve(props.title) : undefined}
          width={props.width}
          height={props.height}
          loop={props.loop}
          autoplay={props.autoPlay}
          muted={props.muted}
          controls
          style={{ maxWidth: "100%", height: "auto" }}
        />
        {caption ? <figcaption>{caption}</figcaption> : null}
      </figure>
    );
  }),

  defineRenderer(BlockImageApi, ({ props, resolve }) => (
    <ElmBlockImage
      src={resolve(props.src)}
      alt={props.alt ? resolve(props.alt) : undefined}
      width={props.width}
      height={props.height}
      srcset={props.srcset ? resolve(props.srcset) : undefined}
      sizes={props.sizes ? resolve(props.sizes) : undefined}
      caption={props.caption ? resolve(props.caption) : undefined}
      enableModal={true}
    />
  )),

  defineRenderer(HtmlApi, ({ props, resolve }) => (
    <ElmHtmlViewer
      html={props.html ? resolve(props.html) : undefined}
      src={props.src ? resolve(props.src) : undefined}
      autoHeight={props.autoHeight}
      allowScripts={props.allowScripts ?? true}
    />
  )),

  // -------------------------------------------------------------------------
  // Code / math / diagram
  // -------------------------------------------------------------------------

  defineRenderer(CodeBlockApi, ({ props, resolve }) => (
    <ElmCodeBlock
      code={resolve(props.code)}
      language={props.language ? resolve(props.language) : undefined}
      caption={props.caption ? resolve(props.caption) : undefined}
    />
  )),

  defineRenderer(KatexApi, ({ props, resolve }) => (
    <ElmKatex expression={resolve(props.expression)} block={true} />
  )),

  // Mermaid is rendered as a syntax-highlighted code block — no dedicated
  // Mermaid renderer in this package. The diagram source is preserved so a
  // host application can post-process if needed.
  defineRenderer(MermaidApi, ({ props, resolve }) => (
    <ElmCodeBlock code={resolve(props.code)} language="mermaid" />
  )),

  // -------------------------------------------------------------------------
  // Tabs — ContentTab is data-only (its parent ContentTabs walks the surface
  // model to read each tab's label and content ChildList directly).
  // -------------------------------------------------------------------------

  defineRenderer(ContentTabApi, () => null),

  defineRenderer(ContentTabsApi, ({ props, surface, renderChild }) => {
    const tabIds = Array.isArray(props.children) ? props.children : [];
    const tabs = tabIds.map((tabId) => {
      const tabModel = surface.componentsModel.get(tabId);
      return {
        tabId,
        labelIds: extractChildIds(tabModel?.properties.label),
        contentIds: extractChildIds(tabModel?.properties.content),
      };
    });
    return (
      <ElmTabs defaultValue="0">
        <ElmTabList>
          {tabs.map(({ tabId, labelIds }, idx) => (
            <ElmTab key={tabId} value={String(idx)}>
              {labelIds.map((lid, i) => (
                <Fragment key={`${lid}:${i}`}>
                  {renderChild(lid, "/", i)}
                </Fragment>
              ))}
            </ElmTab>
          ))}
        </ElmTabList>
        {tabs.map(({ tabId, contentIds }, idx) => (
          <ElmTabPanel key={tabId} value={String(idx)}>
            {contentIds.map((cid, i) => (
              <Fragment key={`${cid}:${i}`}>
                {renderChild(cid, "/", i)}
              </Fragment>
            ))}
          </ElmTabPanel>
        ))}
      </ElmTabs>
    );
  }),

  // -------------------------------------------------------------------------
  // Table
  // -------------------------------------------------------------------------

  defineRenderer(TableApi, ({ props, childRefs, renderChild }) => (
    <ElmTable
      caption={props.caption ? String(props.caption) : undefined}
      hasRowHeader={props.hasRowHeader}
    >
      {props.header && props.header.length > 0 && (
        <ElmTableHeader>
          {childRefs(props.header).map(({ id, path }, i) => (
            <Fragment key={`${id}:${i}`}>{renderChild(id, path, i)}</Fragment>
          ))}
        </ElmTableHeader>
      )}
      <ElmTableBody>
        {childRefs(props.body).map(({ id, path }, i) => (
          <Fragment key={`${id}:${i}`}>{renderChild(id, path, i)}</Fragment>
        ))}
      </ElmTableBody>
    </ElmTable>
  )),

  defineRenderer(TableRowApi, ({ props, childRefs, renderChild }) => (
    <ElmTableRow>
      {childRefs(props.children).map(({ id, path }, i) => (
        <Fragment key={`${id}:${i}`}>{renderChild(id, path, i)}</Fragment>
      ))}
    </ElmTableRow>
  )),

  // `index` is threaded through as `columnIndex` here — unrelated to margin
  // spacing, drives row-header (<th scope="row">) promotion for the first
  // column when `hasRowHeader` is set. See elm-table-cell.tsx.
  defineRenderer(TableCellApi, ({ props, index, childRefs, renderChild }) => (
    <ElmTableCell isHeader={props.isHeader} columnIndex={index}>
      {childRefs(props.children).map(({ id, path }, i) => (
        <span key={`${id}:${i}`}>{renderChild(id, path, i)}</span>
      ))}
    </ElmTableCell>
  )),

  // -------------------------------------------------------------------------
  // Fallback
  // -------------------------------------------------------------------------

  defineRenderer(UnsupportedApi, ({ props }) => (
    <ElmUnsupportedBlock
      details={
        props.details
          ? `Unsupported component type: ${String(props.details)}`
          : "Unsupported component type"
      }
    />
  )),
);

// packages/solid/src/components/a2ui/catalog/notion-block-catalog.tsx
import {
  createEffect,
  createSignal,
  For,
  onCleanup,
  Show,
  type JSX,
} from "solid-js";

import {
  ComponentContext,
  GenericBinder,
  type ComponentModel,
  type SurfaceModel,
} from "@a2ui/web_core/v0_9";
import {
  AudioApi,
  BlockImageApi,
  BlockQuoteApi,
  BookmarkApi,
  CalloutApi,
  CodeBlockApi,
  ColumnApi,
  ColumnListApi,
  ContentTabApi,
  ContentTabsApi,
  DividerApi,
  FileApi,
  HeadingApi,
  HtmlApi,
  IconApi,
  KatexApi,
  LinkTextApi,
  ListApi,
  ListItemApi,
  MermaidApi,
  NotionCalloutApi,
  ParagraphApi,
  RichTextApi,
  TableApi,
  TableCellApi,
  TableRowApi,
  ToggleApi,
  UnsupportedApi,
  VideoApi,
} from "@elmethis/core";

import { ElmCodeBlock } from "../../code/elm-code-block";
import { ElmHtmlViewer } from "../../code/elm-html-viewer";
import { ElmKatex } from "../../code/elm-katex";
import {
  ElmTab,
  ElmTabList,
  ElmTabPanel,
  ElmTabs,
} from "../../containments/elm-tabs";
import { ElmToggle } from "../../containments/elm-toggle";
import { ElmUnsupportedBlock } from "../../fallback/elm-unsupported-block";
import { ElmInlineIcon } from "../../icon/elm-inline-icon";
import { ElmAudioPlayer } from "../../media/elm-audio-player";
import { ElmBlockImage } from "../../media/elm-block-image";
import { ElmFile } from "../../media/elm-file";
import { ElmNotionCallout } from "../../notion/elm-notion-callout";
import { ElmBookmark } from "../../navigation/elm-bookmark";
import {
  ElmTable,
  ElmTableBody,
  ElmTableCell,
  ElmTableHeader,
  ElmTableRow,
} from "../../table";
import { ElmBlockQuote } from "../../typography/elm-block-quote";
import { ElmCallout } from "../../typography/elm-callout";
import { ElmDivider } from "../../typography/elm-divider";
import { ElmHeading } from "../../typography/elm-heading";
import { ElmInlineText } from "../../typography/elm-inline-text";
import { ElmList } from "../../typography/elm-list";
import { ElmParagraph } from "../../typography/elm-paragraph";
import { basicCatalog } from "./basic-catalog";
import {
  CatalogRenderer,
  defineRenderer,
  type ChildRef,
  type SolidRendererEntry,
} from "./catalog";
import { alignItemsMap, justifyContentMap } from "./catalog-utils";
import { RenderIndexedChild } from "./render-indexed-child";

const columnListStyle: JSX.CSSProperties = {
  "box-sizing": "content-box",
  "padding-block": "0.25rem",
  width: "100%",
  display: "flex",
  "flex-direction": "row",
  gap: "0.25rem",
  "justify-content": "space-around",
  "overflow-x": "auto",
};

interface BoundContentTabProps {
  id: string;
  basePath: string;
  surface: SurfaceModel<SolidRendererEntry>;
  renderChild: (id: string, basePath?: string, index?: number) => JSX.Element;
  slot: "label" | "content";
}

const childRefs = (value: unknown, basePath: string): ChildRef[] => {
  if (!Array.isArray(value)) return [];
  return value.flatMap((child) => {
    if (typeof child === "string") return [{ id: child, basePath }];
    if (
      child != null &&
      typeof child === "object" &&
      "id" in child &&
      "basePath" in child &&
      typeof child.id === "string" &&
      typeof child.basePath === "string"
    ) {
      return [{ id: child.id, basePath: child.basePath }];
    }
    return [];
  });
};

/** Binds data-only ContentTab models so template label/content lists stay live. */
const BoundContentTab = (props: BoundContentTabProps) => {
  const [model, setModel] = createSignal<ComponentModel>();
  const [bound, setBound] = createSignal<Record<string, unknown>>({});

  createEffect(() => {
    const surface = props.surface;
    const id = props.id;
    setModel(surface.componentsModel.get(id));
    const created = surface.componentsModel.onCreated.subscribe((next) => {
      if (next.id === id) setModel(next);
    });
    const deleted = surface.componentsModel.onDeleted.subscribe((deletedId) => {
      if (deletedId === id) setModel(undefined);
    });
    onCleanup(() => {
      created.unsubscribe();
      deleted.unsubscribe();
    });
  });

  createEffect(() => {
    if (model() == null) {
      setBound({});
      return;
    }
    const context = new ComponentContext(
      props.surface,
      props.id,
      props.basePath,
    );
    const binder = new GenericBinder<Record<string, unknown>>(
      context,
      ContentTabApi.schema,
    );
    setBound({ ...binder.snapshot });
    const subscription = binder.subscribe((next: Record<string, unknown>) =>
      setBound({ ...next }),
    );
    onCleanup(() => {
      subscription.unsubscribe();
      binder.dispose();
    });
  });

  return (
    <For each={childRefs(bound()[props.slot], props.basePath)}>
      {(child, index) => (
        <RenderIndexedChild
          child={child}
          index={index}
          renderChild={props.renderChild}
        />
      )}
    </For>
  );
};

const blockComponents = [
  defineRenderer(RichTextApi, (props) => (
    <Show
      when={!props.props.decoration?.includes("katex")}
      fallback={<ElmKatex expression={props.props.text} block={false} />}
    >
      <ElmInlineText
        bold={props.props.decoration?.includes("bold")}
        italic={props.props.decoration?.includes("italic")}
        underline={props.props.decoration?.includes("underline")}
        strikethrough={props.props.decoration?.includes("strikethrough")}
        code={props.props.decoration?.includes("code")}
        color={props.props.color}
        ruby={props.props.ruby}
      >
        {props.props.text}
      </ElmInlineText>
    </Show>
  )),
  defineRenderer(LinkTextApi, (props) => (
    <ElmInlineText href={props.props.href} favicon={props.props.favicon}>
      {props.props.text}
    </ElmInlineText>
  )),
  defineRenderer(IconApi, (props) => (
    <ElmInlineIcon src={props.props.src} alt={props.props.alt} />
  )),
  defineRenderer(ColumnApi, (props) => (
    <div
      style={{
        display: "flex",
        "flex-direction": "column",
        "justify-content": justifyContentMap[props.props.justify ?? "start"],
        "align-items": alignItemsMap[props.props.align ?? "stretch"],
        flex:
          props.props.widthRatio == null
            ? undefined
            : String(props.props.widthRatio),
        "box-sizing": "border-box",
        padding: "0.125rem",
        gap: "var(--elmethis-stack-gap)",
      }}
    >
      <For each={props.childRefs(props.props.children)}>
        {(child, index) => (
          <RenderIndexedChild
            child={child}
            index={index}
            renderChild={props.renderChild}
          />
        )}
      </For>
    </div>
  )),
  defineRenderer(ColumnListApi, (props) => (
    <div style={columnListStyle}>
      <For each={props.childRefs(props.props.children)}>
        {(child, index) => (
          <RenderIndexedChild
            child={child}
            index={index}
            renderChild={props.renderChild}
          />
        )}
      </For>
    </div>
  )),
  defineRenderer(HeadingApi, (props) => (
    <ElmHeading level={props.props.level}>
      <For each={props.childRefs(props.props.children)}>
        {(child, index) => (
          <RenderIndexedChild
            child={child}
            index={index}
            renderChild={props.renderChild}
          />
        )}
      </For>
    </ElmHeading>
  )),
  defineRenderer(ParagraphApi, (props) => (
    <ElmParagraph
      color={props.props.color}
      backgroundColor={props.props.backgroundColor}
    >
      <For each={props.childRefs(props.props.children)}>
        {(child, index) => (
          <RenderIndexedChild
            child={child}
            index={index}
            renderChild={props.renderChild}
          />
        )}
      </For>
    </ElmParagraph>
  )),
  defineRenderer(ListApi, (props) => (
    <ElmList listStyle={props.props.style ?? "unordered"}>
      <For each={props.childRefs(props.props.children)}>
        {(child, index) => (
          <li>
            <RenderIndexedChild
              child={child}
              index={index}
              renderChild={props.renderChild}
            />
          </li>
        )}
      </For>
    </ElmList>
  )),
  defineRenderer(ListItemApi, (props) => (
    <For each={props.childRefs(props.props.children)}>
      {(child, index) => (
        <RenderIndexedChild
          child={child}
          index={index}
          renderChild={props.renderChild}
        />
      )}
    </For>
  )),
  defineRenderer(BlockQuoteApi, (props) => (
    <ElmBlockQuote cite={props.props.cite}>
      <For each={props.childRefs(props.props.children)}>
        {(child, index) => (
          <RenderIndexedChild
            child={child}
            index={index}
            renderChild={props.renderChild}
          />
        )}
      </For>
    </ElmBlockQuote>
  )),
  defineRenderer(CalloutApi, (props) => (
    <ElmCallout type={props.props.type}>
      <For each={props.childRefs(props.props.children)}>
        {(child, index) => (
          <RenderIndexedChild
            child={child}
            index={index}
            renderChild={props.renderChild}
          />
        )}
      </For>
    </ElmCallout>
  )),
  defineRenderer(NotionCalloutApi, (props) => (
    <ElmNotionCallout
      icon={props.props.icon}
      color={props.props.color}
      variant={props.props.variant}
    >
      <For each={props.childRefs(props.props.children)}>
        {(child, index) => (
          <RenderIndexedChild
            child={child}
            index={index}
            renderChild={props.renderChild}
          />
        )}
      </For>
    </ElmNotionCallout>
  )),
  defineRenderer(DividerApi, () => <ElmDivider />),
  defineRenderer(ToggleApi, (props) => (
    <ElmToggle
      summary={
        <For each={props.childRefs(props.props.summary)}>
          {(child, index) => (
            <RenderIndexedChild
              child={child}
              index={index}
              renderChild={props.renderChild}
            />
          )}
        </For>
      }
    >
      <For each={props.childRefs(props.props.children)}>
        {(child, index) => (
          <RenderIndexedChild
            child={child}
            index={index}
            renderChild={props.renderChild}
          />
        )}
      </For>
    </ElmToggle>
  )),
  defineRenderer(BookmarkApi, (props) => (
    <ElmBookmark
      url={props.props.url}
      title={props.props.title}
      description={props.props.description}
      image={props.props.image}
    />
  )),
  defineRenderer(FileApi, (props) => (
    <ElmFile src={props.props.src} name={props.props.name} />
  )),
  defineRenderer(AudioApi, (props) => (
    <ElmAudioPlayer
      src={props.props.src}
      title={props.props.title}
      artist={props.props.artist}
      seekStep={props.props.seekStep}
      loop={props.props.loop}
      autoPlay={props.props.autoPlay}
    />
  )),
  defineRenderer(VideoApi, (props) => (
    <figure style={{ margin: 0 }}>
      <video
        src={props.props.src}
        poster={props.props.poster}
        title={props.props.title}
        width={props.props.width}
        height={props.props.height}
        loop={props.props.loop}
        autoplay={props.props.autoPlay}
        muted={props.props.muted}
        controls
        style={{ "max-width": "100%", height: "auto" }}
      />
      <Show when={props.props.caption}>
        {(caption) => <figcaption>{caption()}</figcaption>}
      </Show>
    </figure>
  )),
  defineRenderer(BlockImageApi, (props) => (
    <ElmBlockImage
      src={props.props.src}
      alt={props.props.alt}
      width={props.props.width}
      height={props.props.height}
      srcSet={props.props.srcset}
      sizes={props.props.sizes}
      caption={props.props.caption}
      enableModal
    />
  )),
  defineRenderer(HtmlApi, (props) => (
    <ElmHtmlViewer
      html={props.props.html}
      src={props.props.src}
      autoHeight={props.props.autoHeight}
      allowScripts={props.props.allowScripts ?? true}
      height={props.props.height ?? 400}
    />
  )),
  defineRenderer(CodeBlockApi, (props) => (
    <ElmCodeBlock
      code={props.props.code}
      language={props.props.language}
      caption={props.props.caption}
    />
  )),
  defineRenderer(KatexApi, (props) => (
    <ElmKatex expression={props.props.expression} block />
  )),
  defineRenderer(MermaidApi, (props) => (
    <ElmCodeBlock code={props.props.code} language="mermaid" />
  )),
  defineRenderer(ContentTabApi, () => null),
  defineRenderer(ContentTabsApi, (props) => {
    const tabs = () => props.childRefs(props.props.children);
    return (
      <ElmTabs defaultValue="0">
        <ElmTabList>
          <For each={tabs()}>
            {(tab, index) => (
              <ElmTab value={String(index())}>
                <BoundContentTab
                  id={tab.id}
                  basePath={tab.basePath}
                  surface={props.surface}
                  renderChild={props.renderChild}
                  slot="label"
                />
              </ElmTab>
            )}
          </For>
        </ElmTabList>
        <For each={tabs()}>
          {(tab, index) => (
            <ElmTabPanel value={String(index())}>
              <BoundContentTab
                id={tab.id}
                basePath={tab.basePath}
                surface={props.surface}
                renderChild={props.renderChild}
                slot="content"
              />
            </ElmTabPanel>
          )}
        </For>
      </ElmTabs>
    );
  }),
  defineRenderer(TableApi, (props) => (
    <ElmTable
      caption={
        props.props.caption == null ? undefined : String(props.props.caption)
      }
      hasRowHeader={props.props.hasColumnHeader}
    >
      <Show when={props.props.header?.length}>
        <ElmTableHeader>
          <For each={props.childRefs(props.props.header)}>
            {(child, index) => (
              <RenderIndexedChild
                child={child}
                index={index}
                renderChild={props.renderChild}
              />
            )}
          </For>
        </ElmTableHeader>
      </Show>
      <ElmTableBody>
        <For each={props.childRefs(props.props.body)}>
          {(child, index) => (
            <RenderIndexedChild
              child={child}
              index={index}
              renderChild={props.renderChild}
            />
          )}
        </For>
      </ElmTableBody>
    </ElmTable>
  )),
  defineRenderer(TableRowApi, (props) => (
    <ElmTableRow>
      <For each={props.childRefs(props.props.children)}>
        {(child, index) => (
          <RenderIndexedChild
            child={child}
            index={index}
            renderChild={props.renderChild}
          />
        )}
      </For>
    </ElmTableRow>
  )),
  defineRenderer(TableCellApi, (props) => (
    <ElmTableCell isHeader={props.props.isHeader} columnIndex={props.index}>
      <For each={props.childRefs(props.props.children)}>
        {(child, childIndex) => (
          <RenderIndexedChild
            child={child}
            index={childIndex}
            renderChild={props.renderChild}
          />
        )}
      </For>
    </ElmTableCell>
  )),
  defineRenderer(UnsupportedApi, (props) => (
    <ElmUnsupportedBlock
      details={
        props.props.details
          ? `Unsupported component type: ${String(props.props.details)}`
          : "Unsupported component type"
      }
    />
  )),
];

export const notionBlockCatalog: CatalogRenderer = basicCatalog.extend(
  ...blockComponents,
);
export const notionBlockComponents = [
  ...notionBlockCatalog.components.values(),
];
export const notionBlockFunctions = [...notionBlockCatalog.functions];
