// packages/solid/src/components/containments/elm-toggle.tsx
import { splitProps, type JSX } from "solid-js";
import { clsx } from "clsx";
import { mdiChevronRight, mdiPlus } from "@mdi/js";

import { createControllableSignal } from "../../primitives/create-controllable-signal";
import styles from "./elm-toggle.module.css";
import { ElmMdiIcon } from "../icon/elm-mdi-icon";
import { ElmInlineText } from "../typography/elm-inline-text";

export interface ElmToggleProps extends Omit<
  JSX.HTMLAttributes<HTMLDivElement>,
  "onToggle"
> {
  /**
   * The summary content of the toggle. A string is wrapped in ElmInlineText;
   * any other node is rendered as-is.
   */
  summary?: JSX.Element;

  /** Initial open state for uncontrolled usage. */
  defaultIsOpen?: boolean;

  /** Controlled open state. When provided, the parent owns the value. */
  isOpen?: boolean;

  /** Called with the next open value when the toggle is flipped. */
  onOpenChange?: (isOpen: boolean) => void;

  monochrome?: boolean;
}

export const ElmToggle = (props: ElmToggleProps) => {
  const [local, rest] = splitProps(props, [
    "class",
    "children",
    "summary",
    "defaultIsOpen",
    "isOpen",
    "onOpenChange",
    "monochrome",
  ]);
  const [isOpen, setIsOpen] = createControllableSignal<boolean>({
    value: () => local.isOpen,
    defaultValue: () => local.defaultIsOpen ?? false,
    onChange: (value) => local.onOpenChange?.(value),
  });
  const handleSummaryClick: JSX.EventHandler<HTMLDivElement, MouseEvent> = (
    event,
  ) => {
    event.preventDefault();
    setIsOpen((previous) => !previous);
  };

  return (
    <div
      {...rest}
      class={clsx(styles["elm-toggle"], isOpen() && styles.open, local.class)}
    >
      <div class={styles.summary} onClick={handleSummaryClick}>
        <div class={styles["summary-left"]}>
          <span class={clsx(styles.chevron, isOpen() && styles.open)}>
            <ElmMdiIcon
              path={mdiChevronRight}
              color={
                local.monochrome
                  ? "var(--elmethis-color-neutral-weak)"
                  : "var(--elmethis-color-primary)"
              }
              size="1rem"
            />
          </span>
          <div>
            {typeof local.summary === "string" ? (
              <ElmInlineText>{local.summary}</ElmInlineText>
            ) : (
              local.summary
            )}
          </div>
        </div>

        <hr class={styles.divider} />

        <span class={clsx(styles.cross, isOpen() && styles.open)}>
          <ElmMdiIcon
            path={mdiPlus}
            size="1rem"
            color={
              local.monochrome
                ? "var(--elmethis-color-neutral-weak)"
                : isOpen()
                  ? "var(--elmethis-color-accent-error)"
                  : "var(--elmethis-color-primary)"
            }
          />
        </span>
      </div>

      <div class={styles.border} />

      <div class={clsx(styles.content, isOpen() && styles.open)}>
        {local.children}
      </div>
    </div>
  );
};

// packages/react/src/components/containments/elm-toggle.tsx
import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { clsx } from "clsx";
import { mdiChevronRight, mdiPlus } from "@mdi/js";

import styles from "./elm-toggle.module.css";
import { ElmMdiIcon } from "../icon/elm-mdi-icon";
import { ElmInlineText } from "../typography/elm-inline-text";
import { useBindableSignal } from "../../hooks/use-bindable-signal";

export interface ElmToggleProps extends Omit<
  ComponentPropsWithoutRef<"div">,
  "onToggle"
> {
  /**
   * The summary content of the toggle. A `string` is wrapped in
   * `ElmInlineText`; any other node is rendered as-is.
   */
  summary?: ReactNode;

  /** Initial open state for uncontrolled usage. */
  defaultIsOpen?: boolean;

  /** Controlled open state. When provided the parent owns the value. */
  isOpen?: boolean;

  /** Called with the next open value when the toggle is flipped. */
  onOpenChange?: (isOpen: boolean) => void;

  monochrome?: boolean;
}

export const ElmToggle = ({
  className,
  summary,
  style,
  monochrome,
  isOpen: isOpenProp,
  defaultIsOpen,
  onOpenChange,
  children,
  ...rest
}: ElmToggleProps) => {
  const [isOpen, setIsOpen] = useBindableSignal<boolean>({
    value: isOpenProp,
    defaultValue: defaultIsOpen ?? false,
    onChange: onOpenChange,
  });

  return (
    <div
      className={clsx(styles["elm-toggle"], isOpen && styles.open, className)}
      style={style}
      {...rest}
    >
      <div
        className={styles.summary}
        onClick={(event) => {
          event.preventDefault();
          setIsOpen((prev) => !prev);
        }}
      >
        <div className={styles["summary-left"]}>
          <span className={clsx(styles.chevron, isOpen && styles.open)}>
            <ElmMdiIcon
              path={mdiChevronRight}
              color={
                monochrome
                  ? "var(--elmethis-color-neutral-weak)"
                  : "var(--elmethis-color-primary)"
              }
              size="1rem"
            />
          </span>
          <div>
            {typeof summary === "string" ? (
              <ElmInlineText>{summary}</ElmInlineText>
            ) : (
              summary
            )}
          </div>
        </div>

        <hr className={styles.divider} />

        <span className={clsx(styles.cross, isOpen && styles.open)}>
          <ElmMdiIcon
            path={mdiPlus}
            size="1rem"
            color={
              monochrome
                ? "var(--elmethis-color-neutral-weak)"
                : isOpen
                  ? "var(--elmethis-color-accent-error)"
                  : "var(--elmethis-color-primary)"
            }
          />
        </span>
      </div>

      <div className={styles.border} />

      <div className={clsx(styles.content, isOpen && styles.open)}>
        {children}
      </div>
    </div>
  );
};
