// packages/qwik/src/components/containments/elm-collapse.tsx
import { component$, CSSProperties, PropsOf, Slot } from "@builder.io/qwik";

import styles from "./elm-collapse.module.css";

export interface ElmCollapseProps extends PropsOf<"div"> {
  isOpen?: boolean;

  direction?: "row" | "column" | "both";

  transitionTimingFunction?: CSSProperties["transition-timing-function"];
}

export const ElmCollapse = component$<ElmCollapseProps>(
  ({
    class: className,
    isOpen,
    direction = "row",
    transitionTimingFunction = "ease-in-out",
    ...props
  }) => {
    return (
      <div
        class={[
          styles["elm-collapse"],
          {
            [styles["open"]]: isOpen,
            [styles["row"]]: direction === "row",
            [styles["column"]]: direction === "column",
            [styles["both"]]: direction === "both",
          },
          className,
        ]}
        style={{
          "--elmethis-scoped-transition-timing-function":
            transitionTimingFunction,
        }}
        {...props}
      >
        <div class={styles["inner"]}>
          <Slot />
        </div>
      </div>
    );
  },
);

// packages/react/src/components/containments/elm-collapse.tsx
import type { ComponentPropsWithoutRef, CSSProperties } from "react";
import { clsx } from "clsx";

import styles from "./elm-collapse.module.css";

export interface ElmCollapseProps extends ComponentPropsWithoutRef<"div"> {
  isOpen?: boolean;

  direction?: "row" | "column" | "both";

  transitionTimingFunction?: CSSProperties["transitionTimingFunction"];
}

export const ElmCollapse = ({
  className,
  style,
  isOpen,
  direction = "row",
  transitionTimingFunction = "ease-in-out",
  children,
  ...props
}: ElmCollapseProps) => {
  return (
    <div
      className={clsx(
        styles["elm-collapse"],
        isOpen && styles["open"],
        direction === "row" && styles["row"],
        direction === "column" && styles["column"],
        direction === "both" && styles["both"],
        className,
      )}
      style={
        {
          ...style,
          "--elmethis-scoped-transition-timing-function":
            transitionTimingFunction,
        } as CSSProperties
      }
      {...props}
    >
      <div className={styles["inner"]}>{children}</div>
    </div>
  );
};
