// packages/qwik/src/components/containments/elm-tabs.tsx
import { $, component$, useSignal, type CSSProperties } from "@builder.io/qwik";
import type { JSXOutput } from "@builder.io/qwik";

import styles from "./elm-tabs.module.css";

export interface ElmTabsProps {
  class?: string;

  style?: CSSProperties;

  tabLabels: JSXOutput[];
  tabContents: JSXOutput[];
}

export const ElmTabs = component$<ElmTabsProps>(
  ({ class: className, style, tabLabels, tabContents }) => {
    const selectedTabIndex = useSignal(0);

    const selectTab = $((index: number) => {
      selectedTabIndex.value = index;
    });

    return (
      <div class={[styles["elm-tabs"], className]} style={style}>
        <div class={styles["tab-container"]}>
          {tabLabels.map((tabLabel, index) => (
            <div
              key={index}
              class={[
                styles["tab"],
                {
                  [styles["active"]]: selectedTabIndex.value === index,
                },
              ]}
              onClick$={() => selectTab(index)}
            >
              {tabLabel}
            </div>
          ))}
        </div>

        <div class={styles["tab-content-container"]}>
          {tabContents.map((content, index) => (
            <div
              key={index}
              class={[
                styles["tab-content"],
                {
                  [styles["active"]]: selectedTabIndex.value === index,
                },
              ]}
            >
              <div class={styles["tab-content-inner"]}>{content}</div>
            </div>
          ))}
        </div>
      </div>
    );
  },
);

// packages/react/src/components/containments/ElmTabs.tsx
import React, { useState } from "react";

import "@styles/global.css";
import styles from "./ElmTabs.module.css";

export interface ElmTabsCSSVariables {}

export interface ElmTabsProps {
  style?: React.CSSProperties & ElmTabsCSSVariables;

  /** Array of tab label elements. */
  tabLabels: React.ReactNode[];

  /** Array of tab content elements corresponding to each label. */
  tabContents: React.ReactNode[];
}

export const ElmTabs = (props: ElmTabsProps) => {
  const [selectedTabIndex, setSelectedTabIndex] = useState(0);

  return (
    <div className={styles["elm-tabs"]} style={props.style}>
      <div className={styles["tab-container"]}>
        {props.tabLabels.map((tabLabel, index) => (
          <div
            key={index}
            className={`${styles.tab} ${selectedTabIndex === index ? styles.active : ""}`}
            onClick={() => setSelectedTabIndex(index)}
          >
            {tabLabel}
          </div>
        ))}
      </div>

      <div className={styles["tab-content-container"]}>
        {props.tabContents.map((content, index) => (
          <div
            key={index}
            className={`${styles["tab-content"]} ${selectedTabIndex === index ? styles.active : ""}`}
          >
            {content}
          </div>
        ))}
      </div>
    </div>
  );
};
