// packages/vue/src/components/fallback/elm-rectangle-wave.tsx
import { defineComponent, type HTMLAttributes } from "vue";
import { clsx } from "clsx";

import styles from "./elm-rectangle-wave.module.css";

export type ElmRectangleWaveProps = HTMLAttributes;

export const ElmRectangleWave = defineComponent({
  name: "ElmRectangleWave",
  setup() {
    // inheritAttrs default: passthrough class/style merge onto the root.
    return () => (
      <div aria-hidden="true" class={clsx(styles["elm-rectangle-wave"])}></div>
    );
  },
});

// packages/react/src/components/fallback/elm-rectangle-wave.tsx
import type { ComponentPropsWithoutRef } from "react";
import { clsx } from "clsx";

import styles from "./elm-rectangle-wave.module.css";

export type ElmRectangleWaveProps = ComponentPropsWithoutRef<"div">;

export const ElmRectangleWave = ({
  className,
  ...props
}: ElmRectangleWaveProps) => {
  return (
    <div
      aria-hidden="true"
      className={clsx(styles["elm-rectangle-wave"], className)}
      {...props}
    ></div>
  );
};
