// packages/qwik/src/components/fallback/elm-rectangle-wave.tsx
import { component$, PropsOf } from "@builder.io/qwik";

import styles from "./elm-rectangle-wave.module.css";

export type ElmRectangleWaveProps = PropsOf<"div">;

export const ElmRectangleWave = component$<PropsOf<"div">>(
  ({ class: className, ...props }) => {
    return (
      <div
        aria-hidden="true"
        class={[styles["rectangle-wave"], className]}
        {...props}
      ></div>
    );
  },
);

// packages/react/src/components/fallback/elm-rectangle-wave.tsx
import type { ComponentPropsWithoutRef } from "react";
import { clsx } from "clsx";

import styles from "./elm-rectangle-wave.module.css";

export type ElmRectangleWaveProps = ComponentPropsWithoutRef<"div">;

export const ElmRectangleWave = ({
  className,
  ...props
}: ElmRectangleWaveProps) => {
  return (
    <div
      aria-hidden="true"
      className={clsx(styles["elm-rectangle-wave"], className)}
      {...props}
    ></div>
  );
};
