// packages/qwik/src/components/fallback/elm-block-fallback.tsx
import { component$, PropsOf, type CSSProperties } from "@qwik.dev/core";

import styles from "./elm-block-fallback.module.css";
import { ElmDotLoadingIcon } from "../icon/elm-dot-loading-icon";
import { ElmRectangleWave } from "./elm-rectangle-wave";

export interface ElmBlockFallbackProps extends PropsOf<"div"> {
  height?: CSSProperties["height"];
}

export const ElmBlockFallback = component$<ElmBlockFallbackProps>(
  ({ class: className, style, height = "16rem", ...props }) => {
    return (
      <div
        class={[styles["block-fallback"], className]}
        style={
          { "--height": height, ...(style as CSSProperties) } as CSSProperties
        }
        {...props}
      >
        <ElmDotLoadingIcon />
        <ElmRectangleWave />
      </div>
    );
  },
);

// packages/react/src/components/fallback/ElmBlockFallback.tsx
import React from "react";

import "@styles/global.css";
import styles from "./ElmBlockFallback.module.css";

import { ElmDotLoadingIcon } from "@components/icon/ElmDotLoadingIcon";
import { ElmRectangleWave } from "./ElmRectangleWave";

export interface ElmBlockFallbackCSSVariables {
  "--height"?: React.CSSProperties["height"];
}

export interface ElmBlockFallbackProps {
  style?: React.CSSProperties & ElmBlockFallbackCSSVariables;

  /**
   * Specifies the height of the fallback container.
   */
  height?: React.CSSProperties["height"];
}

export const ElmBlockFallback = (props: ElmBlockFallbackProps) => {
  const { height = "16rem", style } = props;

  return (
    <div
      className={styles["block-fallback"]}
      style={{ "--height": height, ...style } as React.CSSProperties}
    >
      <ElmDotLoadingIcon />
      <ElmRectangleWave />
    </div>
  );
};
