// packages/qwik/src/components/fallback/elm-rectangle-wave.tsx
import { component$, type CSSProperties } from "@builder.io/qwik";

import styles from "./elm-rectangle-wave.module.css";

export interface ElmRectangleWaveProps {
  class?: string;

  style?: CSSProperties;

  placeholder?: string;
}

export const ElmRectangleWave = component$<ElmRectangleWaveProps>(
  ({ class: className, style }) => {
    return (
      <div
        aria-hidden="true"
        class={[styles["rectangle-wave"], className]}
        style={style}
      ></div>
    );
  },
);

// packages/react/src/components/fallback/ElmRectangleWave.tsx
import React from "react";

import "@styles/global.css";
import styles from "./ElmRectangleWave.module.css";

export interface ElmRectangleWaveCSSVariables {}

export interface ElmRectangleWaveProps {
  style?: React.CSSProperties & ElmRectangleWaveCSSVariables;
}

export const ElmRectangleWave = (props: ElmRectangleWaveProps) => {
  return (
    <div aria-hidden className={styles["rectangle-wave"]} style={props.style} />
  );
};
