// packages/vue/src/components/a2ui/elm-a2ui.tsx
/**
 * Public A2UI v0.9 renderer.
 *
 * Two input modes:
 *   - `url` — fetch a JSONL stream and process each line as a v0.9 message.
 *   - `messages` — render a pre-collected message list (useful for tests).
 *
 * Ported from the qwik lead. Vue has no QRL serialization boundary, so surface
 * state lives in plain (non-reactive) closures and a `tick` ref drives
 * re-render: the SDK's `SurfaceModel`s carry runtime-only references
 * (subscriptions, Maps) that never need to be reactive themselves. Per-component
 * write-back and action dispatch are wired by `ComponentHost`.
 */
import {
  defineComponent,
  onMounted,
  onUnmounted,
  provide,
  ref,
  watch,
  type PropType,
} from "vue";

import {
  Catalog,
  MessageProcessor,
  type ComponentApi,
  type SurfaceModel,
} from "@a2ui/web_core/v0_9";
import {
  BASIC_COMPONENTS,
  BASIC_FUNCTIONS,
} from "@a2ui/web_core/v0_9/basic_catalog";

import { basicCatalog } from "./catalog/basic-catalog";
import { type CatalogRenderer } from "./catalog/catalog";
import {
  A2uiAncestorContext,
  A2uiCatalogContext,
  A2uiSurfaceContext,
  ComponentHost,
  ROOT_COMPONENT_ID,
} from "./component-host";
import { streamJsonLines } from "./stream-json-lines";
import styles from "./elm-a2ui.module.css";

const BASIC_CATALOG_ID =
  "https://a2ui.org/specification/v0_9/basic_catalog.json";

export interface ElmA2uiProps {
  /** A JSONL stream URL. Mutually exclusive with `messages`. */
  url?: string;
  /** Optional headers for the stream `fetch`. */
  headers?: Record<string, string>;
  /** Pre-collected message list (e.g. for tests / Storybook). Mutually exclusive with `url`. */
  messages?: object[];
  /**
   * Catalog id used by `createSurface.catalogId`. Pre-registered so streams
   * may begin emitting `updateComponents` before the first `createSurface`
   * arrives.
   */
  catalogId?: string;
  /**
   * Renderer catalog. Defaults to `basicCatalog`. Extend with
   * `basicCatalog.extend(defineRenderer(...))` to override individual types.
   */
  catalog?: CatalogRenderer;
}

// ---------------------------------------------------------------------------
// SurfaceView — internal: renders one surface. The catalog is provided one
// level up (by ElmA2ui / A2uiSurface) so every surface shares it.
// ---------------------------------------------------------------------------

const SurfaceView = defineComponent({
  name: "A2uiSurfaceView",
  props: {
    surface: {
      type: Object as PropType<SurfaceModel<ComponentApi>>,
      required: true,
    },
  },
  setup(props) {
    provide(A2uiSurfaceContext, props.surface);
    provide(A2uiAncestorContext, []);

    return () => (
      <div
        class={styles.surface}
        style={{ "--elmethis-margin-block-start": "2rem" }}
      >
        <ComponentHost id={ROOT_COMPONENT_ID} basePath="/" />
      </div>
    );
  },
});

// ---------------------------------------------------------------------------
// A2uiSurface — official-style standalone entry point.
//
// External integrations that own their own `MessageProcessor` (the React /
// Angular pattern) can mount this directly with a `SurfaceModel`. `ElmA2ui`
// below wraps it for the `messages` / `url` / `catalogId` convenience API.
// ---------------------------------------------------------------------------

export interface A2uiSurfaceProps {
  /** The `SurfaceModel` to render. */
  surface: SurfaceModel<ComponentApi>;
  /**
   * Active renderer catalog. Provided via `provide`/`inject` so descendant
   * `ComponentHost`s can resolve renderers. Defaults to `basicCatalog`.
   */
  catalog?: CatalogRenderer;
}

export const A2uiSurface = defineComponent({
  name: "A2uiSurface",
  props: {
    surface: {
      type: Object as PropType<SurfaceModel<ComponentApi>>,
      required: true,
    },
    catalog: { type: Object as PropType<CatalogRenderer>, default: undefined },
  },
  setup(props) {
    provide(A2uiCatalogContext, props.catalog ?? basicCatalog);
    provide(A2uiSurfaceContext, props.surface);
    provide(A2uiAncestorContext, []);

    return () => (
      <div
        class={styles.surface}
        style={{ "--elmethis-margin-block-start": "2rem" }}
      >
        <ComponentHost id={ROOT_COMPONENT_ID} basePath="/" />
      </div>
    );
  },
});

// ---------------------------------------------------------------------------
// ElmA2ui — public component.
// ---------------------------------------------------------------------------

interface ProcessorInternal {
  processor: MessageProcessor<ComponentApi>;
  subs: Array<{ unsubscribe(): void }>;
  processed: number;
  // Snapshot of the messages used to build the processor — lets the next run
  // detect prefix-extension vs fresh-stream swap.
  messages: object[];
  catalogId: string | undefined;
}

export const ElmA2ui = defineComponent({
  name: "ElmA2ui",
  props: {
    url: { type: String, default: undefined },
    headers: {
      type: Object as PropType<Record<string, string>>,
      default: undefined,
    },
    messages: { type: Array as PropType<object[]>, default: undefined },
    catalogId: { type: String, default: undefined },
    catalog: { type: Object as PropType<CatalogRenderer>, default: undefined },
  },
  setup(props) {
    // Publish the catalog so child SurfaceViews can resolve renderers.
    provide(A2uiCatalogContext, props.catalog ?? basicCatalog);

    // Messages produced by the URL-driven JSONL reader; the controlled
    // `props.messages` path bypasses it.
    const streamList = ref<object[]>([]);
    // Reactivity driver: bumped by surface create/delete and message
    // processing so the render re-reads the (non-reactive) surface map.
    const tick = ref(0);

    // Non-reactive surface state — `SurfaceModel`s hold runtime refs that don't
    // belong in Vue's reactivity graph; `tick` is what tells Vue to re-render.
    let surfaceMap = new Map<string, SurfaceModel<ComponentApi>>();
    let internal: ProcessorInternal | null = null;

    // Mirrors the qwik lead's unified setup+sync task: diff the effective
    // message list against the last-built state — extension (same prefix, more
    // items, same catalogId) processes only the tail; swap (different prefix or
    // catalogId) tears down and rebuilds, pre-registering every catalogId seen
    // in the new messages so the SDK's constructor-only catalog list stays in
    // sync.
    const syncProcessor = async (): Promise<void> => {
      const propsCatalogId = props.catalogId;
      const effective: object[] = props.messages
        ? [...props.messages]
        : [...streamList.value];

      const existing = internal;
      const isExtension =
        existing !== null &&
        existing.catalogId === propsCatalogId &&
        effective.length >= existing.messages.length &&
        existing.messages.every((m, i) => m === effective[i]);

      if (isExtension && existing) {
        // Append-only path: process whatever's new since the last run.
        const fresh = effective.slice(existing.processed);
        if (!fresh.length) return;
        for (const msg of fresh) {
          try {
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            existing.processor.processMessages([msg] as any[]);
          } catch (err) {
            console.warn("[ElmA2ui] skipped invalid A2UI message:", msg, err);
          }
        }
        // The SDK's `EventEmitter.emit` awaits each listener (microtask per
        // iteration). Yield twice so any `onSurfaceCreated` / `onSurfaceDeleted`
        // listeners scheduled by `processMessages` have run before we settle.
        await Promise.resolve();
        await Promise.resolve();
        existing.processed = effective.length;
        existing.messages = effective;
        tick.value++;
        return;
      }

      // Rebuild path: stream swap or catalogId change. Release our own
      // subscriptions, then dispose the previous processor's SurfaceGroupModel
      // so its surfaces release their dataModel / componentsModel / per-surface
      // emitters.
      if (existing) {
        for (const s of existing.subs) s.unsubscribe();
        existing.processor.model.dispose();
      }

      const ids = new Set<string>([BASIC_CATALOG_ID]);
      if (propsCatalogId) ids.add(propsCatalogId);
      for (const m of effective) {
        if (m && typeof m === "object" && "createSurface" in m) {
          const id = (m as { createSurface?: { catalogId?: string } })
            .createSurface?.catalogId;
          if (typeof id === "string") ids.add(id);
        }
      }
      const catalogs = Array.from(ids).map(
        (id) =>
          new Catalog(id, BASIC_COMPONENTS as ComponentApi[], BASIC_FUNCTIONS),
      );
      const processor = new MessageProcessor<ComponentApi>(catalogs);
      const newMap = new Map<string, SurfaceModel<ComponentApi>>();
      const subs: Array<{ unsubscribe(): void }> = [];
      subs.push(
        processor.model.onSurfaceCreated.subscribe((surface) => {
          newMap.set(surface.id, surface);
          tick.value++;
        }),
      );
      subs.push(
        processor.model.onSurfaceDeleted.subscribe((id) => {
          newMap.delete(id);
          tick.value++;
        }),
      );
      surfaceMap = newMap;

      for (const msg of effective) {
        try {
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          processor.processMessages([msg] as any[]);
        } catch (err) {
          console.warn("[ElmA2ui] skipped invalid A2UI message:", msg, err);
        }
      }

      internal = {
        processor,
        subs,
        processed: effective.length,
        messages: effective,
        catalogId: propsCatalogId,
      };
      tick.value++;
    };

    // Identity-based: in-place mutation of the same `props.messages` array
    // won't re-fire — callers must produce a new array reference per tick,
    // matching the React / Angular reference implementations.
    watch(
      [
        () => props.messages,
        () => props.catalogId,
        () => streamList.value.length,
      ],
      () => {
        void syncProcessor();
      },
      { immediate: true },
    );

    // ---- JSONL streaming (only when url is provided) ----
    let ctrl: AbortController | null = null;
    onMounted(() => {
      if (!props.url) return;
      ctrl = new AbortController();
      const signal = ctrl.signal;
      fetch(props.url, { headers: props.headers, signal })
        .then(async (res) => {
          if (!res.body) return;
          await streamJsonLines(res.body, {
            signal,
            onMessage: (m) => {
              if (m && typeof m === "object")
                streamList.value.push(m as object);
            },
            onError: (err, line) => {
              console.warn("[ElmA2ui] skipped invalid JSON line:", line, err);
            },
          });
        })
        .catch((err: unknown) => {
          if (err instanceof Error && err.name !== "AbortError") {
            console.error("[ElmA2ui] stream error:", err);
          }
        });
    });

    onUnmounted(() => {
      ctrl?.abort();
      if (!internal) return;
      for (const s of internal.subs) s.unsubscribe();
      // Dispose the SurfaceGroupModel — cascades into per-surface dispose, so
      // the entire processor graph is released on unmount.
      internal.processor.model.dispose();
    });

    return () => {
      // tick establishes the reactive dep on surface-map mutations.
      void tick.value;
      return (
        <div class={styles["elm-a2ui"]}>
          {Array.from(surfaceMap.values()).map((surface) => (
            <SurfaceView key={surface.id} surface={surface} />
          ))}
        </div>
      );
    };
  },
});

// packages/react/src/components/a2ui/elm-a2ui.tsx
/**
 * Public A2UI v0.9 renderer (React).
 *
 * Built on the **official** `@a2ui/react` package: the recursive host
 * (`A2uiSurface` / `DeferredChild`) and the generic binder are the library's,
 * so this component only owns the convenience API around them —
 *
 *   - `messages` — render a pre-collected v0.9 message list (tests / Storybook).
 *   - `url` — fetch a JSONL stream and process each line as a v0.9 message.
 *
 * The component drives a `@a2ui/web_core` `MessageProcessor`, tracks the
 * surfaces it creates, and renders each through `A2uiSurface`. The active
 * catalog is the Elm {@link blockComponents} (official basic catalog + the
 * Elm block renderers); pass `components` to override it.
 */
import {
  useEffect,
  useRef,
  useState,
  type ComponentPropsWithoutRef,
  type CSSProperties,
} from "react";
import clsx from "clsx";

import {
  A2uiSurface,
  type ReactComponentImplementation,
} from "@a2ui/react/v0_9";
import {
  Catalog,
  MessageProcessor,
  type SurfaceModel,
} from "@a2ui/web_core/v0_9";

import { blockComponents, blockFunctions } from "./catalog/block-catalog";
import { streamJsonLines } from "./stream-json-lines";
import styles from "./elm-a2ui.module.css";

const BASIC_CATALOG_ID =
  "https://a2ui.org/specification/v0_9/basic_catalog.json";

const surfaceStyle = {
  "--elmethis-margin-block-start": "2rem",
} as CSSProperties;

export interface ElmA2uiProps extends Omit<
  ComponentPropsWithoutRef<"div">,
  "children"
> {
  /** A JSONL stream URL. Mutually exclusive with `messages`. */
  url?: string;
  /** Optional headers for the stream `fetch`. */
  headers?: Record<string, string>;
  /** Pre-collected message list. Mutually exclusive with `url`. */
  messages?: object[];
  /**
   * Catalog id pre-registered alongside the ids referenced by `createSurface`
   * messages, so a stream may emit `updateComponents` before its first
   * `createSurface` arrives.
   */
  catalogId?: string;
  /**
   * Component implementations registered under every referenced catalog id.
   * Defaults to {@link blockComponents}. Pass a stable (memoized) array.
   */
  components?: ReactComponentImplementation[];
}

interface ProcessorState {
  processor: MessageProcessor<ReactComponentImplementation>;
  subs: Array<{ unsubscribe(): void }>;
  processed: number;
  messages: object[];
  catalogId: string | undefined;
}

export const ElmA2ui = ({
  className,
  style,
  url,
  headers,
  messages,
  catalogId,
  components = blockComponents,
  ...rest
}: ElmA2uiProps) => {
  // Messages produced by the URL-driven JSONL reader, kept in state so each
  // appended line re-renders and re-runs the processing effect. The
  // controlled-mode `messages` prop bypasses this.
  const [streamMessages, setStreamMessages] = useState<object[]>([]);
  // The live surfaces, in state so create/delete events drive re-renders.
  // (Data/component updates re-render through the official binder, not here.)
  const [surfaces, setSurfaces] = useState<
    SurfaceModel<ReactComponentImplementation>[]
  >([]);
  const processorRef = useRef<ProcessorState | null>(null);
  const surfaceMapRef = useRef<
    Map<string, SurfaceModel<ReactComponentImplementation>>
  >(new Map());

  // ---- JSONL streaming (only when `url` is provided) ----
  useEffect(() => {
    if (!url) return;
    const ctrl = new AbortController();
    // Clear the previous source's buffered lines when the stream url changes —
    // synchronizing the local buffer with the external stream it mirrors.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setStreamMessages([]);
    fetch(url, { headers, signal: ctrl.signal })
      .then(async (res) => {
        if (!res.body) return;
        await streamJsonLines(res.body, {
          signal: ctrl.signal,
          onMessage: (m) => {
            if (m && typeof m === "object") {
              setStreamMessages((prev) => [...prev, m as object]);
            }
          },
          onError: (err, line) => {
            console.warn("[ElmA2ui] skipped invalid JSON line:", line, err);
          },
        });
      })
      .catch((err: unknown) => {
        if (err instanceof Error && err.name !== "AbortError") {
          console.error("[ElmA2ui] stream error:", err);
        }
      });
    return () => ctrl.abort();
  }, [url, headers]);

  // ---- unified setup + sync + processing ----
  // Diffs the effective message list against the last-built state:
  //   - extension (same prefix, more items, same catalogId) → process the tail
  //   - swap (different prefix, or catalogId changed)        → rebuild
  // Surface creation/deletion is observed via subscriptions that push the live
  // surfaces into state, so asynchronously-emitted surfaces still render.
  const effective: object[] = messages ? messages : streamMessages;
  useEffect(() => {
    const syncSurfaces = () =>
      setSurfaces(Array.from(surfaceMapRef.current.values()));

    const existing = processorRef.current;
    const isExtension =
      existing !== null &&
      existing.catalogId === catalogId &&
      effective.length >= existing.messages.length &&
      existing.messages.every((m, i) => m === effective[i]);

    if (isExtension && existing) {
      const fresh = effective.slice(existing.processed);
      if (!fresh.length) return;
      for (const msg of fresh) {
        try {
          existing.processor.processMessages([msg] as never);
        } catch (err) {
          console.warn("[ElmA2ui] skipped invalid A2UI message:", msg, err);
        }
      }
      existing.processed = effective.length;
      existing.messages = effective;
      return;
    }

    // Rebuild path: stream swap or catalogId change.
    if (existing) {
      for (const s of existing.subs) s.unsubscribe();
      existing.processor.model.dispose();
    }

    const ids = new Set<string>([BASIC_CATALOG_ID]);
    if (catalogId) ids.add(catalogId);
    for (const m of effective) {
      if (m && typeof m === "object" && "createSurface" in m) {
        const id = (m as { createSurface?: { catalogId?: string } })
          .createSurface?.catalogId;
        if (typeof id === "string") ids.add(id);
      }
    }
    const catalogs = Array.from(ids).map(
      (id) => new Catalog(id, components, blockFunctions),
    );
    const processor = new MessageProcessor<ReactComponentImplementation>(
      catalogs,
    );
    const surfaceMap = surfaceMapRef.current;
    surfaceMap.clear();
    const subs: Array<{ unsubscribe(): void }> = [];
    subs.push(
      processor.model.onSurfaceCreated.subscribe((surface) => {
        surfaceMap.set(surface.id, surface);
        syncSurfaces();
      }),
    );
    subs.push(
      processor.model.onSurfaceDeleted.subscribe((id) => {
        surfaceMap.delete(id);
        syncSurfaces();
      }),
    );

    for (const msg of effective) {
      try {
        processor.processMessages([msg] as never);
      } catch (err) {
        console.warn("[ElmA2ui] skipped invalid A2UI message:", msg, err);
      }
    }

    processorRef.current = {
      processor,
      subs,
      processed: effective.length,
      messages: effective,
      catalogId,
    };
    syncSurfaces();
  }, [effective, catalogId, components]);

  // Dispose the processor graph on unmount.
  useEffect(() => {
    return () => {
      const internal = processorRef.current;
      if (!internal) return;
      for (const s of internal.subs) s.unsubscribe();
      internal.processor.model.dispose();
      processorRef.current = null;
    };
  }, []);

  return (
    <div
      className={clsx(styles["elm-a2ui"], className)}
      style={style}
      {...rest}
    >
      {surfaces.map((surface) => (
        <div key={surface.id} className={styles.surface} style={surfaceStyle}>
          <A2uiSurface surface={surface} />
        </div>
      ))}
    </div>
  );
};
