// packages/react/src/components/containments/elm-tabs.tsx
import {
  createContext,
  useContext,
  type ComponentPropsWithoutRef,
  type CSSProperties,
} from "react";
import { clsx } from "clsx";

import styles from "./elm-tabs.module.css";
import { ElmCollapse } from "./elm-collapse";
import { useBindableSignal } from "../../hooks/use-bindable-signal";

interface ElmTabsContextValue {
  selectedValue: string;
  setSelectedValue: (value: string) => void;
  transitionTimingFunction: CSSProperties["transitionTimingFunction"];
}

const ElmTabsContext = createContext<ElmTabsContextValue | null>(null);

const useElmTabsContext = () => {
  const ctx = useContext(ElmTabsContext);
  if (ctx == null) {
    throw new Error("ElmTabs subcomponents must be used within <ElmTabs>");
  }
  return ctx;
};

export interface ElmTabsProps extends ComponentPropsWithoutRef<"div"> {
  /**
   * Controlled selected tab value. When provided, the parent owns the value.
   */
  value?: string;

  /**
   * Initial selected tab value when uncontrolled.
   */
  defaultValue?: string;

  /**
   * Called when the selected tab value changes.
   */
  onValueChange?: (value: string) => void;

  transitionTimingFunction?: CSSProperties["transitionTimingFunction"];
}

export const ElmTabs = ({
  className,
  value,
  defaultValue,
  onValueChange,
  transitionTimingFunction = "linear",
  children,
  ...rest
}: ElmTabsProps) => {
  const [selectedValue, setSelectedValue] = useBindableSignal<string>({
    value,
    defaultValue: defaultValue ?? "",
    onChange: onValueChange,
  });

  return (
    <ElmTabsContext.Provider
      value={{ selectedValue, setSelectedValue, transitionTimingFunction }}
    >
      <div className={clsx(styles["elm-tabs"], className)} {...rest}>
        {children}
      </div>
    </ElmTabsContext.Provider>
  );
};

export type ElmTabListProps = ComponentPropsWithoutRef<"div">;

export const ElmTabList = ({
  className,
  children,
  ...rest
}: ElmTabListProps) => (
  <div className={clsx(styles["tab-container"], className)} {...rest}>
    {children}
  </div>
);

export interface ElmTabProps extends ComponentPropsWithoutRef<"div"> {
  /** Identifier matching the corresponding ElmTabPanel `value`. */
  value: string;
}

export const ElmTab = ({
  value,
  className,
  children,
  onClick,
  ...rest
}: ElmTabProps) => {
  const ctx = useElmTabsContext();
  return (
    <div
      className={clsx(
        styles["tab"],
        ctx.selectedValue === value && styles["active"],
        className,
      )}
      onClick={(event) => {
        ctx.setSelectedValue(value);
        onClick?.(event);
      }}
      {...rest}
    >
      {children}
    </div>
  );
};

export interface ElmTabPanelProps extends ComponentPropsWithoutRef<"div"> {
  /** Identifier matching the corresponding ElmTab `value`. */
  value: string;
}

export const ElmTabPanel = ({
  value,
  className,
  children,
  ...rest
}: ElmTabPanelProps) => {
  const ctx = useElmTabsContext();
  return (
    <div className={clsx(styles["tab-content"], className)} {...rest}>
      <ElmCollapse
        direction="row"
        isOpen={ctx.selectedValue === value}
        transitionTimingFunction={ctx.transitionTimingFunction}
      >
        <div className={styles["tab-content-inner"]}>{children}</div>
      </ElmCollapse>
    </div>
  );
};

// packages/vue/src/components/containments/elm-tabs.tsx
import {
  defineComponent,
  inject,
  provide,
  type CSSProperties,
  type HTMLAttributes,
} from "vue";
import { clsx } from "clsx";

import styles from "./elm-tabs.module.css";
import { ElmCollapse } from "./elm-collapse";
import { useBindableSignal } from "../../hooks/use-bindable-signal";
import {
  ElmTabsContext,
  useElmTabsContext,
  type ElmTabsContextValue,
} from "./tabs-context";

export interface ElmTabsProps extends HTMLAttributes {
  /**
   * Controlled selected tab value. Bind with `v-model:value`; when provided the
   * parent owns the value (prop `value` + `update:value` event).
   */
  value?: string;

  /**
   * Initial selected tab value when uncontrolled.
   */
  defaultValue?: string;

  transitionTimingFunction?: CSSProperties["transitionTimingFunction"];
}

export const ElmTabs = defineComponent({
  name: "ElmTabs",
  props: {
    value: { type: String, default: undefined },
    defaultValue: { type: String, default: "" },
    transitionTimingFunction: { type: String, default: "linear" },
  },
  emits: ["update:value"],
  setup(props, { emit, slots }) {
    const selectedValue = useBindableSignal({
      props,
      key: "value",
      emit,
      defaultValue: props.defaultValue ?? "",
    });

    const context: ElmTabsContextValue = {
      // `defaultValue` ("") guarantees a string at runtime; the model ref's type
      // widens to `string | undefined`, so narrow it back here.
      selectedValue: selectedValue,
      setSelectedValue: (value: string) => {
        selectedValue.value = value;
      },
      // Getter so a reactive `transitionTimingFunction` prop stays live.
      get transitionTimingFunction() {
        return props.transitionTimingFunction;
      },
    };
    provide(ElmTabsContext, context);

    // inheritAttrs default: passthrough class/style merge onto the root.
    return () => (
      <div class={clsx(styles["elm-tabs"])}>{slots.default?.()}</div>
    );
  },
});

export type ElmTabListProps = HTMLAttributes;

export const ElmTabList = defineComponent({
  name: "ElmTabList",
  setup(_, { slots }) {
    return () => (
      <div class={clsx(styles["tab-container"])}>{slots.default?.()}</div>
    );
  },
});

export interface ElmTabProps extends HTMLAttributes {
  /** Identifier matching the corresponding ElmTabPanel `value`. */
  value: string;
}

export const ElmTab = defineComponent({
  name: "ElmTab",
  props: {
    value: { type: String, required: true },
  },
  setup(props, { slots }) {
    const ctx = useElmTabsContext(inject(ElmTabsContext));
    // inheritAttrs default: a passthrough `onClick` fires alongside ours.
    return () => (
      <div
        class={clsx(
          styles["tab"],
          ctx.selectedValue.value === props.value && styles["active"],
        )}
        onClick={() => ctx.setSelectedValue(props.value)}
      >
        {slots.default?.()}
      </div>
    );
  },
});

export interface ElmTabPanelProps extends HTMLAttributes {
  /** Identifier matching the corresponding ElmTab `value`. */
  value: string;
}

export const ElmTabPanel = defineComponent({
  name: "ElmTabPanel",
  props: {
    value: { type: String, required: true },
  },
  setup(props, { slots }) {
    const ctx = useElmTabsContext(inject(ElmTabsContext));
    return () => (
      <div class={clsx(styles["tab-content"])}>
        <ElmCollapse
          direction="row"
          isOpen={ctx.selectedValue.value === props.value}
          transitionTimingFunction={ctx.transitionTimingFunction}
        >
          <div class={styles["tab-content-inner"]}>{slots.default?.()}</div>
        </ElmCollapse>
      </div>
    );
  },
});
