// packages/solid/src/components/containments/elm-modal.tsx
import {
  createEffect,
  createSignal,
  mergeProps,
  onCleanup,
  splitProps,
  type JSX,
} from "solid-js";
import { clsx } from "clsx";

import { callEventHandler } from "../../primitives/call-event-handler";
import { mergeStyle } from "../../styles/merge-style";
import styles from "./elm-modal.module.css";

export interface ElmModalProps extends Omit<
  JSX.DialogHtmlAttributes<HTMLDialogElement>,
  "onClose"
> {
  isOpen?: boolean;

  /** Delay in milliseconds of the open/close fade animation. */
  delay?: number;

  onClose?: (event: Event, element: HTMLDialogElement) => void;
}

export const ElmModal = (props: ElmModalProps) => {
  const merged = mergeProps({ delay: 200, closedby: "none" as const }, props);
  const [local, rest] = splitProps(merged, [
    "class",
    "style",
    "ref",
    "children",
    "isOpen",
    "delay",
    "onClick",
    "onCancel",
    "onClose",
  ]);
  const [isShown, setIsShown] = createSignal(false);
  let dialog: HTMLDialogElement | undefined;
  let closeTimer: ReturnType<typeof setTimeout> | undefined;

  const clearCloseTimer = () => {
    if (closeTimer === undefined) return;
    clearTimeout(closeTimer);
    closeTimer = undefined;
  };

  createEffect(() => {
    const open = Boolean(local.isOpen);
    const delay = local.delay;
    const element = dialog;

    clearCloseTimer();
    if (!element) return;

    if (open) {
      if (element.open) {
        setIsShown(true);
        return;
      }

      if (!element.isConnected || typeof element.showModal !== "function") {
        return;
      }

      try {
        element.showModal();
        setIsShown(element.open);
      } catch {
        // A forwarded native `open` state or detached dialog can reject
        // showModal(). The next prop change will retry against the live shell.
      }
      return;
    }

    if (!isShown() && !element.open) return;
    setIsShown(false);
    if (!element.open) return;

    closeTimer = setTimeout(
      () => {
        closeTimer = undefined;
        if (!local.isOpen && element.open) element.close();
      },
      Math.max(0, delay),
    );
  });

  onCleanup(clearCloseTimer);

  const handleClick: JSX.EventHandler<HTMLDialogElement, MouseEvent> = (
    event,
  ) => {
    callEventHandler(local.onClick, event);
    if (event.defaultPrevented || event.target !== event.currentTarget) return;
    local.onClose?.(event, event.currentTarget);
  };

  const handleCancel: JSX.EventHandler<HTMLDialogElement, Event> = (event) => {
    callEventHandler(local.onCancel, event);
    if (event.defaultPrevented) return;

    // Keep the dialog in the top layer while the controlled fade-out runs.
    event.preventDefault();
    local.onClose?.(event, event.currentTarget);
  };

  const handleNativeClose: JSX.EventHandler<HTMLDialogElement, Event> = (
    event,
  ) => {
    clearCloseTimer();
    setIsShown(false);

    // A form method="dialog" or imperative close can bypass controlled state.
    if (local.isOpen) local.onClose?.(event, event.currentTarget);
  };

  return (
    <dialog
      {...rest}
      ref={(element) => {
        dialog = element;
        if (typeof local.ref === "function") local.ref(element);
      }}
      class={clsx(styles["elm-modal"], isShown() && styles.shown, local.class)}
      style={mergeStyle(local.style, {
        "--elmethis-scoped-modal-delay": `${local.delay}ms`,
      })}
      onClick={handleClick}
      onCancel={handleCancel}
      onClose={handleNativeClose}
    >
      <div onClick={(event) => event.stopPropagation()}>{local.children}</div>
    </dialog>
  );
};

// packages/vue/src/components/containments/elm-modal.tsx
import {
  defineComponent,
  onBeforeUnmount,
  onMounted,
  ref,
  watch,
  type DialogHTMLAttributes,
  type PropType,
  type StyleValue,
} from "vue";
import { clsx } from "clsx";

import styles from "./elm-modal.module.css";

// Display/form dual-use component: intentionally does NOT adopt a
// controlled/uncontrolled split (e.g. `useBindableSignal`). Modals are driven
// by parent state in nearly all callsites — including display-only
// confirmations and externally-triggered dialogs — so a plain controlled
// `isOpen` prop is preferred.
export interface ElmModalProps extends Omit<DialogHTMLAttributes, "onClose"> {
  isOpen?: boolean;

  /**
   * Delay in **milliseconds** of the open/close fade. Emitted as the
   * `--elmethis-scoped-modal-delay` custom property so the stylesheet
   * transition stays in sync with the JS close timer. Defaults to `200`.
   */
  delay?: number;

  onClose?: (event: Event, element: HTMLDialogElement) => void;
}

export const ElmModal = defineComponent({
  name: "ElmModal",
  inheritAttrs: false,
  props: {
    isOpen: { type: Boolean, default: undefined },
    delay: { type: Number, default: 200 },
    onClose: {
      type: Function as PropType<
        (event: Event, element: HTMLDialogElement) => void
      >,
      default: undefined,
    },
  },
  setup(props, { attrs, slots }) {
    const dialogRef = ref<HTMLDialogElement | null>(null);
    const isShown = ref(false);
    let closeTimer: ReturnType<typeof setTimeout> | undefined;

    // Synchronizes the native <dialog> with the controlled `isOpen` prop. The
    // `shown` fade class can only flip *after* the imperative `showModal()` /
    // close-timer runs against the real DOM ref, as in React's mount effect.
    const sync = (open: boolean | undefined, delay: number): void => {
      const dialog = dialogRef.value;
      if (!dialog) {
        return;
      }
      // Clear any pending close before re-evaluating (covers rapid toggles).
      if (closeTimer !== undefined) {
        clearTimeout(closeTimer);
        closeTimer = undefined;
      }
      if (open) {
        dialog.showModal();
        isShown.value = true;
      } else {
        // Nothing to close if it was never opened — without this guard an
        // initially-closed modal would close() a dialog never showModal()'d.
        if (!isShown.value) {
          return;
        }
        isShown.value = false;
        closeTimer = setTimeout(() => {
          dialogRef.value?.close();
        }, delay);
      }
    };

    onMounted(() => sync(props.isOpen, props.delay));
    watch([() => props.isOpen, () => props.delay], ([open, delay]) =>
      sync(open, delay),
    );
    onBeforeUnmount(() => {
      if (closeTimer !== undefined) {
        clearTimeout(closeTimer);
      }
    });

    const handleClose = (event: Event): void => {
      if (dialogRef.value) {
        props.onClose?.(event, dialogRef.value);
      }
    };

    return () => {
      const {
        class: className,
        style,
        ...rest
      } = attrs as Record<string, unknown>;

      return (
        <dialog
          ref={dialogRef}
          class={clsx(
            styles["elm-modal"],
            isShown.value && styles["shown"],
            className as string | undefined,
          )}
          onClick={handleClose}
          style={
            [
              {
                "--elmethis-scoped-modal-delay": `${props.delay}ms`,
              },
              style as StyleValue,
            ] as StyleValue
          }
          {...({ closedby: "none" } as Record<string, string>)}
          {...rest}
        >
          <div onClick={(e: Event) => e.stopPropagation()}>
            {slots.default?.()}
          </div>
        </dialog>
      );
    };
  },
});
