// packages/react/src/components/others/ElmColorTable.tsx
import React from "react";

import "@styles/global.css";
import styles from "./ElmColorTable.module.css";

import { darken } from "polished";
import { ElmColorSample } from "./ElmColorSample";

export interface ElmColorTableProps {
  style?: React.CSSProperties;

  /**
   * The colors to display.
   */
  colors: { name: string; code: string }[];
}

const DARKNESS_LEVELS = [
  -3, -0.25, -0.2, -0.15, -0.1, -0.05, 0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3,
] as const;

export const ElmColorTable = ({ colors, style }: ElmColorTableProps) => {
  return (
    <div className={styles.container} style={style}>
      {colors.map((color) => (
        <div key={color.name} className={styles["row-container"]}>
          <div
            className={styles["color-name"]}
            style={{ "--color": color.code } as React.CSSProperties}
          >
            {color.name}
          </div>
          {DARKNESS_LEVELS.map((darkness) => (
            <ElmColorSample
              key={darkness}
              color={darken(darkness, color.code)}
            />
          ))}
        </div>
      ))}
    </div>
  );
};

// packages/qwik/src/components/others/elm-color-table.tsx
import { component$ } from "@builder.io/qwik";
import { darken } from "polished";

import styles from "./elm-color-table.module.css";

export interface ElmColorTableProps {
  /**
   * The colors to display.
   */
  colors: { name: string; code: string }[];
}

const DARKNESS_VALUES = [
  -3, -0.25, -0.2, -0.15, -0.1, -0.05, 0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3,
];

export const ElmColorTable = component$<ElmColorTableProps>(({ colors }) => {
  return (
    <div class={styles.container}>
      {colors.map((color) => (
        <div key={color.name} class={styles["row-container"]}>
          <div
            class={styles["color-name"]}
            style={{ "--color": color.code } as Record<string, string>}
          >
            {color.name}
          </div>
          {DARKNESS_VALUES.map((darkness) => {
            const sampledColor = darken(Math.max(0, darkness), color.code);
            return (
              <div
                key={darkness}
                class={styles["color-sample"]}
                style={
                  { "--color-sample-bg": sampledColor } as Record<
                    string,
                    string
                  >
                }
              />
            );
          })}
        </div>
      ))}
    </div>
  );
});
