// packages/react/src/components/others/ElmJarkup.tsx
import React, { lazy, Suspense } from "react";
import type { Component, InlineComponent } from "jarkup-ts";
import { kebabCase } from "lodash-es";

import "@styles/global.css";
import styles from "./ElmJarkup.module.css";

import { ElmInlineText } from "@components/typography/ElmInlineText";
import { ElmKatex } from "@components/code/ElmKatex";
import { ElmInlineIcon } from "@components/icon/ElmInlineIcon";
import { ElmHeading } from "@components/typography/ElmHeading";
import { ElmParagraph } from "@components/typography/ElmParagraph";
import { ElmList } from "@components/typography/ElmList";
import { ElmBlockQuote } from "@components/typography/ElmBlockQuote";
import { ElmCallout } from "@components/typography/ElmCallout";
import { ElmDivider } from "@components/typography/ElmDivider";
import { ElmToggle } from "@components/containments/ElmToggle";
import { ElmTabs } from "@components/containments/ElmTabs";
import { ElmBookmark } from "@components/navigation/ElmBookmark";
import { ElmFile } from "@components/media/ElmFile";
import { ElmImage } from "@components/media/ElmImage";
import { ElmCodeBlock } from "@components/code/ElmCodeBlock";
import { ElmTable } from "@components/table/ElmTable";
import { ElmTableHeader } from "@components/table/ElmTableHeader";
import { ElmTableBody } from "@components/table/ElmTableBody";
import { ElmTableRow } from "@components/table/ElmTableRow";
import { ElmTableCell } from "@components/table/ElmTableCell";
import { ElmUnsupportedBlock } from "@components/fallback/ElmUnsupportedBlock";
import { ElmBlockFallback } from "@components/fallback/ElmBlockFallback";

const ElmMermaid = lazy(() =>
  import("@components/code/ElmMermaid").then((m) => ({
    default: m.ElmMermaid,
  })),
);

export interface ElmJarkupProps {
  style?: React.CSSProperties;

  /**
   * JSON component tree to render.
   */
  jsonComponents: Component[];

  /**
   * If true, Unsupported components and unknown types are silently skipped.
   */
  skipUnsupportedComponentWarning?: boolean;
}

const convertInlineComponentsToPlainText = (
  inlineComponents: InlineComponent[],
): string => {
  return inlineComponents
    .map((component) => {
      if (component.type === "Text") {
        return component.props.text;
      }
      return "";
    })
    .join("");
};

export const ElmJarkup = ({
  jsonComponents,
  skipUnsupportedComponentWarning = false,
  style,
}: ElmJarkupProps) => {
  const render = (components: Component[]): React.ReactNode[] => {
    return components.map((component, index) => {
      const key = (component as { id?: string }).id ?? index;

      switch (component.type) {
        case "Text": {
          const { props: p } = component;
          if (p.katex) {
            return <ElmKatex key={key} expression={p.text} block={false} />;
          }
          return (
            <ElmInlineText
              key={key}
              color={p.color}
              backgroundColor={p.backgroundColor}
              bold={p.bold}
              italic={p.italic}
              underline={p.underline}
              strikethrough={p.strikethrough}
              code={p.code}
              ruby={p.ruby}
              href={p.href}
              favicon={p.favicon}
            >
              {p.text}
            </ElmInlineText>
          );
        }

        case "Icon":
          return (
            <ElmInlineIcon
              key={key}
              src={component.props.src}
              alt={component.props.alt}
            />
          );

        case "Fragment":
          return <React.Fragment key={key}>{render(component.slots.default)}</React.Fragment>;

        case "Heading":
          return (
            <ElmHeading
              key={key}
              level={component.props.level}
              id={kebabCase(
                convertInlineComponentsToPlainText(component.slots.default),
              )}
            >
              {render(component.slots.default)}
            </ElmHeading>
          );

        case "Paragraph":
          return (
            <ElmParagraph
              key={key}
              backgroundColor={component.props?.backgroundColor}
            >
              {render(component.slots.default)}
            </ElmParagraph>
          );

        case "ListItem":
          return <li key={key}>{render(component.slots.default)}</li>;

        case "List":
          return (
            <ElmList
              key={key}
              listStyle={
                component.props?.listStyle === "unordered"
                  ? "unordered"
                  : "ordered"
              }
            >
              {render(component.slots.default)}
            </ElmList>
          );

        case "BlockQuote":
          return (
            <ElmBlockQuote key={key} cite={component.props?.cite}>
              {render(component.slots.default)}
            </ElmBlockQuote>
          );

        case "Callout":
          return (
            <ElmCallout key={key} type={component.props?.type}>
              {render(component.slots.default)}
            </ElmCallout>
          );

        case "Divider":
          return <ElmDivider key={key} />;

        case "Toggle":
          return (
            <ElmToggle key={key} summaryContent={render(component.slots.summary)}>
              {render(component.slots.default)}
            </ElmToggle>
          );

        case "Bookmark":
          return (
            <ElmBookmark
              key={key}
              url={component.props.url}
              title={component.props.title}
              description={component.props.description}
              image={component.props.image}
            />
          );

        case "File":
          return (
            <ElmFile
              key={key}
              src={component.props.src}
              name={component.props.name}
            />
          );

        case "Image":
          return (
            <ElmImage
              key={key}
              src={component.props.src}
              alt={component.props.alt}
              width={component.props.width}
              height={component.props.height}
              block={true}
              enableModal={true}
            />
          );

        case "CodeBlock":
          return (
            <ElmCodeBlock
              key={key}
              code={component.props.code}
              language={component.props.language}
            />
          );

        case "Katex":
          return (
            <ElmKatex
              key={key}
              expression={component.props.expression}
              block={true}
            />
          );

        case "Mermaid":
          return (
            <Suspense key={key} fallback={<ElmBlockFallback />}>
              <ElmMermaid code={component.props.code} />
            </Suspense>
          );

        case "Tabs": {
          const labels: React.ReactNode[] = [];
          const contents: React.ReactNode[] = [];
          for (const tab of component.slots.default) {
            labels.push(<span>{render(tab.slots.labels)}</span>);
            contents.push(<div>{render(tab.slots.contents)}</div>);
          }
          return (
            <ElmTabs key={key} tabLabels={labels} tabContents={contents} />
          );
        }

        case "Table":
          return (
            <ElmTable
              key={key}
              caption={component.props?.caption}
              hasRowHeader={component.props?.hasRowHeader}
              header={
                component.slots.header ? (
                  <ElmTableHeader>
                    {render(component.slots.header)}
                  </ElmTableHeader>
                ) : undefined
              }
              body={
                <ElmTableBody>{render(component.slots.body)}</ElmTableBody>
              }
            />
          );

        case "TableRow":
          return (
            <ElmTableRow key={key}>
              {render(component.slots.default)}
            </ElmTableRow>
          );

        case "TableCell":
          return (
            <ElmTableCell key={key}>
              {render(component.slots.default)}
            </ElmTableCell>
          );

        case "ColumnList":
          return (
            <div key={key} className={styles["column-list"]}>
              {render(component.slots.default)}
            </div>
          );

        case "Column":
          return (
            <div
              key={key}
              className={styles.column}
              style={{
                "--width-ratio": component.props?.widthRatio ?? 1,
                width: component.props?.widthRatio
                  ? `${component.props.widthRatio * 100}%`
                  : undefined,
              } as React.CSSProperties}
            >
              {render(component.slots.default)}
            </div>
          );

        case "Unsupported": {
          if (skipUnsupportedComponentWarning) return null;
          return (
            <ElmUnsupportedBlock
              key={key}
              details={component.props?.details ?? `Unsupported component type: ${component.type}`}
            />
          );
        }

        default: {
          if (skipUnsupportedComponentWarning) return null;
          return (
            <ElmUnsupportedBlock
              key={key}
              details={`Unsupported component type: ${(component as { type: string }).type}`}
            />
          );
        }
      }
    });
  };

  return (
    <div className={styles["jarkup-body"]} style={style}>
      {render(jsonComponents)}
    </div>
  );
};

// packages/qwik/src/components/others/elm-jarkup.tsx
import { component$, CSSProperties, type JSXOutput } from "@builder.io/qwik";
import type { Component, InlineComponent } from "jarkup-ts";
import { kebabCase } from "lodash-es";

import styles from "./elm-jarkup.module.scss";

import { ElmInlineText } from "../typography/elm-inline-text";
import { ElmKatex } from "../code/elm-katex";
import { ElmInlineIcon } from "../icon/elm-inline-icon";
import { ElmHeading } from "../typography/elm-heading";
import { ElmParagraph } from "../typography/elm-paragraph";
import { ElmList } from "../typography/elm-list";
import { ElmBlockQuote } from "../typography/elm-block-quote";
import { ElmCallout } from "../typography/elm-callout";
import { ElmDivider } from "../typography/elm-divider";
import { ElmToggle } from "../containments/elm-toggle";
import { ElmBookmark } from "../navigation/elm-bookmark";
import { ElmFile } from "../media/elm-file";
import { ElmBlockImage } from "../media/elm-block-image";
import { ElmCodeBlock } from "../code/elm-code-block";
import {
  ElmTable,
  ElmTableHeader,
  ElmTableBody,
  ElmTableRow,
  ElmTableCell,
} from "../table";
import { ElmTabs } from "../containments/elm-tabs";
import { ElmUnsupportedBlock } from "../fallback/elm-unsupported-block";

export interface ElmJarkupProps {
  jsonComponents: Component[];

  skipUnsupportedComponentWarning?: boolean;

  style?: CSSProperties;
}

const convertInlineComponentsToPlainText = (
  inlineComponents: InlineComponent[],
): string => {
  return inlineComponents
    .map((component) => {
      if (component.type === "Text") {
        return component.props.text;
      } else {
        return "";
      }
    })
    .join("");
};

export const ElmJarkup = component$<ElmJarkupProps>((props) => {
  const render = (jsonComponents: Component[]): JSXOutput[] => {
    return jsonComponents.map((component, index) => {
      const key = component.id || index;

      switch (component.type) {
        case "Text": {
          const { props: p } = component;
          if (p.katex) {
            return <ElmKatex key={key} expression={p.text} block={false} />;
          }
          return (
            <ElmInlineText
              key={key}
              text={p.text}
              color={p.color}
              backgroundColor={p.backgroundColor}
              bold={p.bold}
              italic={p.italic}
              underline={p.underline}
              strikethrough={p.strikethrough}
              code={p.code}
              ruby={p.ruby}
              href={p.href}
              favicon={p.favicon}
            />
          );
        }

        case "Icon":
          return (
            <ElmInlineIcon
              key={key}
              src={component.props.src}
              alt={component.props.alt}
            />
          );

        case "Fragment": {
          return <>{render(component.slots.default)}</>;
        }

        case "Heading":
          return (
            <ElmHeading
              key={key}
              level={component.props.level}
              id={kebabCase(
                convertInlineComponentsToPlainText(component.slots.default),
              )}
            >
              {render(component.slots.default)}
            </ElmHeading>
          );

        case "Paragraph":
          return (
            <ElmParagraph
              key={key}
              color={component.props?.color}
              backgroundColor={component.props?.backgroundColor}
            >
              {render(component.slots.default)}
            </ElmParagraph>
          );

        case "ListItem":
          return <li key={key}>{render(component.slots.default)}</li>;

        case "List":
          return (
            <ElmList
              key={key}
              listStyle={
                component.props?.listStyle === "unordered"
                  ? "unordered"
                  : "ordered"
              }
            >
              {render(component.slots.default)}
            </ElmList>
          );

        case "BlockQuote":
          return (
            <ElmBlockQuote key={key} cite={component.props?.cite}>
              {render(component.slots.default)}
            </ElmBlockQuote>
          );

        case "Callout":
          return (
            <ElmCallout key={key} type={component.props?.type}>
              {render(component.slots.default)}
            </ElmCallout>
          );

        case "Divider":
          return <ElmDivider key={key} />;

        case "Toggle":
          return (
            <ElmToggle key={key}>
              <div q:slot="summary">{render(component.slots.summary)}</div>
              {render(component.slots.default)}
            </ElmToggle>
          );

        case "Bookmark":
          return (
            <ElmBookmark
              key={key}
              url={component.props.url}
              title={component.props.title}
              description={component.props.description}
              image={component.props.image}
            />
          );

        case "File":
          return (
            <ElmFile
              key={key}
              src={component.props.src}
              name={component.props.name}
            />
          );

        case "Image":
          return (
            <ElmBlockImage
              key={key}
              src={component.props.src}
              alt={component.props.alt}
              width={component.props.width}
              height={component.props.height}
              enableModal={true}
            />
          );

        case "CodeBlock":
          return (
            <ElmCodeBlock
              key={key}
              code={component.props.code}
              language={component.props.language}
            >
              {component.slots?.default && render(component.slots.default)}
            </ElmCodeBlock>
          );

        case "Katex":
          return (
            <ElmKatex
              key={key}
              expression={component.props.expression}
              block={true}
            />
          );

        case "Tabs": {
          const labels: InlineComponent[][] = [];
          const contents: Component[][] = [];
          for (const tab of component.slots.default) {
            labels.push(tab.slots.labels);
            contents.push(tab.slots.contents);
          }

          // Render synchronously OUTSIDE the $ boundary
          const renderedLabels = labels.map((label, index) => (
            <span key={index}>{render(label)}</span>
          ));
          const renderedContents = contents.map((content, index) => (
            <div key={index}>{render(content)}</div>
          ));

          return (
            <ElmTabs
              tabLabels={renderedLabels}
              tabContents={renderedContents}
            />
          );
        }

        case "Table":
          return (
            <ElmTable
              key={key}
              caption={component.props?.caption}
              hasRowHeader={component.props?.hasRowHeader}
            >
              {component.slots.header && (
                <ElmTableHeader>
                  {render(component.slots.header)}
                </ElmTableHeader>
              )}
              <ElmTableBody>{render(component.slots.body)}</ElmTableBody>
            </ElmTable>
          );

        case "TableRow":
          return (
            <ElmTableRow key={key}>
              {render(component.slots.default)}
            </ElmTableRow>
          );

        case "TableCell":
          return (
            <ElmTableCell key={key}>
              {render(component.slots.default)}
            </ElmTableCell>
          );

        case "ColumnList":
          return (
            <div key={key} class={styles["column-list"]}>
              {render(component.slots.default)}
            </div>
          );

        case "Column":
          return (
            <div
              key={key}
              class={styles.column}
              style={{
                "--width-ratio": component.props?.widthRatio || 1,
                width: component.props?.widthRatio
                  ? `${component.props.widthRatio * 100}%`
                  : undefined,
              }}
            >
              {render(component.slots.default)}
            </div>
          );

        case "Unsupported": {
          if (props.skipUnsupportedComponentWarning) return null;

          return (
            <ElmUnsupportedBlock
              key={key}
              details={`Unsupported component type: ${component.props?.details || component.type}`}
            />
          );
        }

        default:
          if (props.skipUnsupportedComponentWarning) return null;

          return (
            <ElmUnsupportedBlock
              key={key}
              details={`Unsupported component type: ${component.type}`}
            />
          );
      }
    });
  };

  return (
    <div style={{ "--margin-block": "3rem", ...props.style }}>
      {render(props.jsonComponents)}
    </div>
  );
});
