// packages/core/src/components/others/ElmColorSample.vue
<template>
  <div :style="{ '--color': color }">
    <ElmTooltip>
      <template #original>
        <div
          :class="$style['color-bg']"
          :style="{
            '--background-color': color
          }"
          @click="copy(hex)"
        >
          <transition>
            <Icon
              icon="mdi:check"
              v-if="copied"
              :style="{ width: '16px', color: 'white' }"
            />
          </transition>
        </div>
        <div :class="$style.text" @click="copy(hex)">{{ hex }}</div>
      </template>
      <template #tooltip>
        <div :class="$style.text" @click="copy(hex)">{{ hex }}</div>
        <div :class="$style.text" @click="copy(rgb)">{{ rgb }}</div>
        <div :class="$style.text" @click="copy(hsl)">{{ hsl }}</div>
      </template>
    </ElmTooltip>
  </div>
</template>

<script setup lang="ts">
import { parseToHsl, parseToRgb, rgbToColorString } from 'polished'
import ElmTooltip from '../containments/ElmTooltip.vue'
import { useClipboard } from '@vueuse/core'
import { Icon } from '@iconify/vue/dist/iconify.js'

export interface ElmColorSampleProps {
  /**
   * The color to display.
   */
  color: string
}

const props = withDefaults(defineProps<ElmColorSampleProps>(), {})

const { blue, green, red } = parseToRgb(props.color)
const { hue, saturation, lightness } = parseToHsl(props.color)

const hex = rgbToColorString(parseToRgb(props.color))
const rgb = `rgb(${red}, ${green}, ${blue})`
const hsl = `hsl(${Math.floor(hue)}, ${Math.floor(saturation * 100)}%, ${Math.floor(lightness * 100)}%)`

const { copy, copied } = useClipboard()
</script>

<style module lang="scss">
.color-bg {
  width: 5rem;
  height: 2rem;
  border-radius: 0.25rem;
  background-color: var(--background-color);
  cursor: pointer;

  transition: opacity 100ms;

  &:active {
    opacity: 0.5;
  }
}

.text {
  margin-block: 0.125rem;
  padding: 0.125rem;
  border-radius: 0.125rem;
  transition:
    color 100ms,
    background-color 100ms,
    opacity 100ms;
  color: var(--color);
  cursor: pointer;

  &:hover {
    color: white;
    background-color: var(--color);
  }

  &:active {
    opacity: 0.5;
  }

  &::selection {
    color: white;
    background-color: var(--color);
  }
}
</style>

<style scoped lang="scss">
.v-enter-to,
.v-leave-from {
  opacity: 1;
}

.v-enter-active,
.v-leave-active {
  transition: opacity 300ms;
}

.v-enter-from,
.v-leave-to {
  opacity: 0;
}
</style>

// packages/qwik/src/components/others/elm-color-sample.tsx
import { $, component$, PropsOf, useSignal } from "@qwik.dev/core";
import { parseToHsl, parseToRgb, rgbToColorString } from "polished";
import { mdiCheck } from "@mdi/js";

import { ElmTooltip } from "../containments/elm-tooltip";
import { ElmMdiIcon } from "../icon/elm-mdi-icon";

import styles from "./elm-color-sample.module.css";

export interface ElmColorSampleProps extends PropsOf<"div"> {
  /**
   * The color to display.
   */
  color: string;
}

export const ElmColorSample = component$<ElmColorSampleProps>(({ color, class: className, ...props }) => {
  const { red, green, blue } = parseToRgb(color);
  const { hue, saturation, lightness } = parseToHsl(color);

  const hex = rgbToColorString({ red, green, blue });
  const rgb = `rgb(${red}, ${green}, ${blue})`;
  const hsl = `hsl(${Math.floor(hue)}, ${Math.floor(saturation * 100)}%, ${Math.floor(lightness * 100)}%)`;

  const copied = useSignal(false);

  const copyText = $(async (text: string) => {
    await window.navigator.clipboard.writeText(text);
    copied.value = true;
    window.setTimeout(() => {
      copied.value = false;
    }, 1500);
  });

  return (
    <div
      class={className}
      style={{ "--color": color } as Record<string, string>}
      {...props}
    >
      <ElmTooltip>
        <div q:slot="original">
          <div
            class={styles["color-bg"]}
            style={{ "--background-color": color } as Record<string, string>}
            onClick$={() => copyText(hex)}
          >
            {copied.value && (
              <ElmMdiIcon d={mdiCheck} size="1em" color="white" />
            )}
          </div>
          <div class={styles.text} onClick$={() => copyText(hex)}>
            {hex}
          </div>
        </div>
        <div q:slot="tooltip">
          <div class={styles.text} onClick$={() => copyText(hex)}>
            {hex}
          </div>
          <div class={styles.text} onClick$={() => copyText(rgb)}>
            {rgb}
          </div>
          <div class={styles.text} onClick$={() => copyText(hsl)}>
            {hsl}
          </div>
        </div>
      </ElmTooltip>
    </div>
  );
});
