// packages/react/src/components/form/ElmTextField.tsx
import React, { useCallback, useId, useRef, useState } from "react";

import "@styles/global.css";
import styles from "./ElmTextField.module.css";

import { ElmMdiIcon } from "@components/icon/ElmMdiIcon";
import {
  mdiEyeOutline,
  mdiEyeOffOutline,
  mdiBackspaceOutline,
  mdiText,
  mdiPen,
  mdiEmail,
  mdiAccount,
  mdiLock,
  mdiKey,
  mdiEarth,
  mdiTag,
  mdiArchive,
  mdiLinkVariant,
  mdiMagnify,
} from "@mdi/js";

export type ElmTextFieldIcon =
  | "text"
  | "pen"
  | "email"
  | "user"
  | "lock"
  | "key"
  | "earth"
  | "tag"
  | "archive"
  | "link"
  | "search";

const iconMap: Record<ElmTextFieldIcon, string> = {
  text: mdiText,
  pen: mdiPen,
  email: mdiEmail,
  user: mdiAccount,
  lock: mdiLock,
  key: mdiKey,
  earth: mdiEarth,
  tag: mdiTag,
  archive: mdiArchive,
  link: mdiLinkVariant,
  search: mdiMagnify,
};

export interface ElmTextFieldCSSVariables {
  "--highlight-color"?: string;
}

export interface ElmTextFieldProps {
  style?: React.CSSProperties & ElmTextFieldCSSVariables;

  /** Label for the text field. */
  label: string;

  /** Maximum character length. */
  maxLength?: number;

  /** Suffix text. */
  suffix?: string;

  /** Placeholder text. */
  placeholder?: string;

  /** Whether the text field is disabled. */
  disabled?: boolean;

  /** Whether the text field is in loading state. */
  loading?: boolean;

  /** Icon to display on the left. */
  icon?: ElmTextFieldIcon;

  /** Whether the text field is a password field. */
  isPassword?: boolean;

  /** Whether the field is required. */
  required?: boolean;

  /** Current value. */
  value?: string;

  /** Called when the value changes. */
  onChange?: (value: string) => void;
}

export const ElmTextField = ({
  disabled = false,
  loading = false,
  isPassword = false,
  required = false,
  value = "",
  ...props
}: ElmTextFieldProps) => {
  const id = useId();
  const inputRef = useRef<HTMLInputElement>(null);
  const [isFocused, setIsFocused] = useState(false);
  const [type, setType] = useState(isPassword ? "password" : "text");

  const handleDelete = useCallback(() => {
    if (!loading && !disabled && props.onChange) {
      props.onChange("");
    }
  }, [loading, disabled, props.onChange]);

  const handleVisibleSwitch = useCallback(() => {
    if (!loading && !disabled) {
      setType((prev) => (prev === "text" ? "password" : "text"));
    }
  }, [loading, disabled]);

  const wrapperClass = [styles.wrapper, isFocused ? styles.active : ""]
    .filter(Boolean)
    .join(" ");

  return (
    <div
      className={wrapperClass}
      style={{
        backgroundColor:
          disabled || loading ? "rgba(0,0,0,0.15)" : undefined,
        "--highlight-color": isFocused ? "#bfa056" : undefined,
        ...props.style,
      } as React.CSSProperties}
    >
      <div className={styles.header}>
        <label htmlFor={id} className={styles.label}>
          <span>{props.label}</span>
          {required && <span className={styles.required}>*</span>}
        </label>
        {props.maxLength != null && (
          <span
            className={[
              styles.counter,
              value.length > props.maxLength ? styles["counter-over"] : "",
            ]
              .filter(Boolean)
              .join(" ")}
          >
            {value.length} / {props.maxLength}
          </span>
        )}
      </div>
      <div className={styles.body}>
        {props.icon && (
          <ElmMdiIcon d={iconMap[props.icon]} size="1.5rem" color="gray" />
        )}

        <input
          id={id}
          ref={inputRef}
          type={type}
          className={styles.input}
          placeholder={props.placeholder}
          value={value}
          onChange={(e) => props.onChange?.(e.target.value)}
          onFocus={() => setIsFocused(true)}
          onBlur={() => setIsFocused(false)}
          disabled={disabled || loading}
          style={{
            cursor: disabled ? "not-allowed" : loading ? "progress" : "auto",
          }}
          aria-required={required}
        />

        <div className={styles["icon-box"]}>
          {props.suffix != null && (
            <span className={styles.suffix}>{props.suffix}</span>
          )}

          <div
            className={styles.icon}
            onClick={handleVisibleSwitch}
            role="button"
            tabIndex={0}
          >
            <ElmMdiIcon
              d={type === "text" ? mdiEyeOutline : mdiEyeOffOutline}
              size="1.75em"
              color="gray"
            />
          </div>

          <div
            className={styles.icon}
            onClick={handleDelete}
            role="button"
            tabIndex={0}
          >
            <ElmMdiIcon d={mdiBackspaceOutline} size="1.75em" color="gray" />
          </div>
        </div>
      </div>

      <div
        className={styles.loading}
        style={{ opacity: loading ? 0.2 : 0 }}
      ></div>
    </div>
  );
};

// packages/core/src/components/form/ElmTextField.vue
<template>
  <div
    :class="[$style.wrapper, { [$style.active]: isFocused }]"
    :style="{
      backgroundColor: disabled || loading ? 'rgba(0,0,0,0.15)' : undefined,
      '--highlight-color': isFocused ? '#bfa056' : undefined,
    }"
  >
    <div :class="$style.header">
      <label :for="id" :class="$style.label">
        <span>{{ label }}</span>
        <span v-if="required" :class="$style.requierd">*</span>
      </label>
      <ElmInlineText
        v-if="maxLength != null"
        :text="`${input.length} / ${maxLength}`"
        :color="input.length > maxLength ? '#c56565' : 'gray'"
        size="0.75rem"
      />
    </div>
    <div :class="$style.body">
      <ElmMdiIcon v-if="icon" :d="iconMap[icon]" size="1.5rem" color="gray" />

      <input
        :id="id"
        v-model="input"
        :type="type"
        :class="$style.input"
        :placeholder="placeholder"
        @focus="isFocused = true"
        @blur="isFocused = false"
        :disabled="disabled || loading"
        :style="{
          cursor: disabled ? 'not-allowed' : loading ? 'progress' : 'auto',
        }"
        :aria-required="required"
      />

      <div :class="$style['icon-box']">
        <span :class="$style.suffix">
          <ElmInlineText v-if="suffix != null" :text="suffix" />
        </span>

        <ElmMdiIcon
          :d="type === 'text' ? mdiEyeOutline : mdiEyeOffOutline"
          size="1.75em"
          color="gray"
          :class="$style.icon"
          @click="handleVisibleSwitch"
        />

        <ElmMdiIcon
          :d="mdiBackspaceOutline"
          size="1.75em"
          color="gray"
          :class="$style.icon"
          @click="handleDelete"
        />
      </div>
    </div>

    <div
      :class="$style.loading"
      :style="{
        opacity: loading ? 0.2 : 0,
      }"
    ></div>
  </div>
</template>

<script setup lang="ts">
import ElmInlineText from "../typography/ElmInlineText.vue";
import { ref } from "vue";
import { nanoid } from "nanoid";

import ElmMdiIcon from "../icon/ElmMdiIcon.vue";
import {
  mdiEyeOutline,
  mdiEyeOffOutline,
  mdiBackspaceOutline,
  mdiText,
  mdiPen,
  mdiEmail,
  mdiAccount,
  mdiLock,
  mdiKey,
  mdiEarth,
  mdiTag,
  mdiArchive,
  mdiLinkVariant,
  mdiMagnify,
} from "@mdi/js";

const id = nanoid();

const isFocused = ref<boolean>(false);

export interface ElmTextFieldProps {
  label: string;
  maxLength?: number;
  suffix?: string;
  placeholder?: string;
  disabled?: boolean;
  loading?: boolean;
  icon?:
    | "text"
    | "pen"
    | "email"
    | "user"
    | "lock"
    | "key"
    | "earth"
    | "tag"
    | "archive"
    | "link"
    | "search";
  isPassword?: boolean;
  required?: boolean;
}

const props = withDefaults(defineProps<ElmTextFieldProps>(), {
  disabled: false,
  loading: false,
  isPassword: false,
  required: false,
});

const input = defineModel({ default: "" });

const type = ref(props.isPassword ? "password" : "text");

const handleDelete = () => {
  if (!props.loading && !props.disabled) input.value = "";
};

const handleVisibleSwitch = () => {
  if (!props.loading && !props.disabled)
    type.value = type.value === "text" ? "password" : "text";
};

const iconMap: Record<NonNullable<ElmTextFieldProps["icon"]>, string> = {
  text: mdiText,
  pen: mdiPen,
  email: mdiEmail,
  user: mdiAccount,
  lock: mdiLock,
  key: mdiKey,
  earth: mdiEarth,
  tag: mdiTag,
  archive: mdiArchive,
  link: mdiLinkVariant,
  search: mdiMagnify,
};
</script>

<style module lang="scss">
@keyframes loading {
  0% {
    transform-origin: 0%;
    transform: scaleX(0);
  }

  40% {
    transform-origin: 0%;
    transform: scaleX(1);
  }

  60% {
    transform-origin: 100%;
    transform: scaleX(1);
  }

  100% {
    transform-origin: 100%;
    transform: scaleX(0);
  }
}

.loading {
  position: absolute;
  width: 100%;
  height: 100%;
  top: 0;
  left: 0;
  background-color: #6987b8;
  transition: opacity 200ms;
  pointer-events: none;

  animation-name: loading;
  animation-iteration-count: infinite;
  animation-duration: 1600ms;
}

.wrapper {
  overflow: hidden;
  position: relative;
  box-sizing: border-box;
  width: 100%;
  padding: 0.25rem;
  border-radius: 0.25rem;
  display: flex;
  flex-direction: column;
  justify-content: space-between;

  transition:
    border-color 200ms,
    background-color 200ms;

  border-style: solid;
  border-width: 1px;
  border-color: transparent;

  background-color: rgba(white, 0.8);
  box-shadow: 0 0 0.125rem rgba(black, 0.15);

  [data-theme="dark"] & {
    background-color: rgba(white, 0.15);
    box-shadow: 0 0 0.125rem rgba(black, 0.75);
  }
}

.active {
  border-color: var(--highlight-color);
}

.header {
  box-sizing: border-box;
  height: 0.75rem;
  padding: 0 0.25rem;
  display: flex;
  justify-content: space-between;
}

.label {
  display: inline;
  margin: 0;
  padding: 0;
  font-size: 0.75rem;
  line-height: 0.75rem;
  height: 0.75rem;
  vertical-align: top;
  transition: color 200ms;

  color: var(--highlight-color, rgba(black, 0.65));

  [data-theme="dark"] & {
    color: var(--highlight-color, rgba(white, 0.65));
  }
}

.requierd {
  padding-inline: 0.25rem;
  color: #c56565;
  font-weight: bold;
}

.body {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding-right: 0.25rem;
  padding-left: 0.25rem;
}

.left-icon {
  margin: auto 0.25rem;
  width: 24px;
  height: 24px;
  display: flex;
  justify-content: center;
  align-items: center;
  opacity: 0.7;

  [data-theme="dark"] & {
    filter: invert(1);
  }
}

.input {
  all: unset;
  box-sizing: border-box;
  padding: 0.5rem;
  width: 100%;
  color: rgba(black, 0.7);
  caret-color: rgba(black, 0.7);

  &::placeholder {
    opacity: 0.5;

    [data-theme="dark"] & {
      opacity: 0.7;
    }
  }

  &::selection {
    background-color: rgba(black, 0.7);
    color: rgba(white, 0.7);
  }

  [data-theme="dark"] & {
    color: rgba(white, 0.7);
    caret-color: rgba(white, 0.7);

    &::selection {
      background-color: rgba(white, 0.7);
      color: rgba(black, 0.7);
    }
  }
}

.icon-box {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.icon {
  box-sizing: border-box;
  border-radius: 0.125em;
  padding: 0.25rem;
  transition: background-color 200ms;
  cursor: pointer;

  &:hover {
    background-color: rgba(gray, 0.2);
  }
}

.suffix {
  opacity: 0.6;
  padding: 0 0.5rem;
  user-select: none;
  transition: color 200ms;

  color: rgba(black, 0.65);

  [data-theme="dark"] & {
    color: rgba(white, 0.65);
  }
}
</style>
