// packages/react/src/styles/variables.ts
export type ElmethisCSSVariables = {
  "--elmethis-color-primary"?: React.CSSProperties["color"];

  "--elmethis-text-color-light"?: React.CSSProperties["color"];
  "--elmethis-text-color-dark"?: React.CSSProperties["color"];
  "--elmethis-text-background-color-light"?: React.CSSProperties["backgroundColor"];
  "--elmethis-text-background-color-dark"?: React.CSSProperties["backgroundColor"];

  "--elmethis-margin-block"?: React.CSSProperties["marginBlock"];
  "--elmethis-margin-block-start"?: React.CSSProperties["marginBlockStart"];
  "--elmethis-margin-block-end"?: React.CSSProperties["marginBlockEnd"];
};

// packages/qwik/src/styles/variables.ts
import type { CSSProperties } from "@qwik.dev/core";

export type ElmethisCSSVariables = {
  "--elmethis-margin-block-start"?: CSSProperties["marginBlockStart"];

  "--elmethis-color-primary"?: CSSProperties["color"];
  "--elmethis-color-text"?: CSSProperties["color"];
  "--elmethis-color-text-background"?: CSSProperties["backgroundColor"];
  "--elmethis-color-accent-muted"?: CSSProperties["color"];

  "--elmethis-scoped-collapse-transition-duration"?: CSSProperties["transitionDuration"];
  "--elmethis-scoped-transition-timing-function"?: CSSProperties["transitionTimingFunction"];
};
