// packages/react/src/components/typography/elm-divider.tsx
import type { ComponentPropsWithoutRef } from "react";
import { clsx } from "clsx";

import styles from "./elm-divider.module.css";

export type ElmDividerProps = ComponentPropsWithoutRef<"hr">;

export const ElmDivider = ({ className, ...props }: ElmDividerProps) => {
  return <hr className={clsx(styles["elm-divider"], className)} {...props} />;
};

// packages/solid/src/components/typography/elm-divider.tsx
import { splitProps, type JSX } from "solid-js";
import { clsx } from "clsx";

import styles from "./elm-divider.module.css";

export type ElmDividerProps = JSX.HTMLAttributes<HTMLHRElement>;

export const ElmDivider = (props: ElmDividerProps) => {
  const [local, rest] = splitProps(props, ["class"]);

  return <hr class={clsx(styles["elm-divider"], local.class)} {...rest} />;
};
