// packages/vue/src/components/typography/elm-divider.tsx
import { defineComponent, type HTMLAttributes } from "vue";
import { clsx } from "clsx";

import styles from "./elm-divider.module.css";

export type ElmDividerProps = HTMLAttributes;

export const ElmDivider = defineComponent({
  name: "ElmDivider",
  // Take full control of attribute inheritance so a consumer-supplied `class`
  // is merged with the component's own root class instead of duplicated.
  inheritAttrs: false,
  setup(_, { attrs }) {
    return () => {
      const { class: className, ...rest } = attrs as Record<string, unknown>;
      return (
        <hr
          class={clsx(styles["elm-divider"], className as string | undefined)}
          {...rest}
        />
      );
    };
  },
});

// packages/solid/src/components/typography/elm-divider.tsx
import { splitProps, type JSX } from "solid-js";
import { clsx } from "clsx";

import styles from "./elm-divider.module.css";

export type ElmDividerProps = JSX.HTMLAttributes<HTMLHRElement>;

export const ElmDivider = (props: ElmDividerProps) => {
  const [local, rest] = splitProps(props, ["class"]);

  return <hr class={clsx(styles["elm-divider"], local.class)} {...rest} />;
};
