// packages/react/src/components/typography/elm-block-quote.tsx
import type { ComponentPropsWithoutRef } from "react";
import { clsx } from "clsx";
import { mdiFormatQuoteClose, mdiFormatQuoteOpen } from "@mdi/js";

import styles from "./elm-block-quote.module.css";
import textStyles from "../../styles/text.module.css";
import { ElmMdiIcon } from "../icon/elm-mdi-icon";

export interface ElmBlockQuoteProps extends ComponentPropsWithoutRef<"blockquote"> {}

export const ElmBlockQuote = ({
  className,
  children,
  ...props
}: ElmBlockQuoteProps) => {
  return (
    <blockquote
      className={clsx(styles["elm-block-quote"], textStyles.text, className)}
      {...props}
    >
      <div className={clsx(styles.icon, styles["icon-top-left"])}>
        <ElmMdiIcon path={mdiFormatQuoteOpen} />
      </div>

      <div className={styles.body}>{children}</div>

      <div className={clsx(styles.icon, styles["icon-bottom-right"])}>
        <ElmMdiIcon path={mdiFormatQuoteClose} />
      </div>
    </blockquote>
  );
};

// packages/solid/src/components/typography/elm-block-quote.tsx
import { splitProps, type JSX } from "solid-js";
import { clsx } from "clsx";

import styles from "./elm-block-quote.module.css";
import textStyles from "../../styles/text.module.css";
import { ElmMdiIcon } from "../icon/elm-mdi-icon";

const FORMAT_QUOTE_OPEN =
  "M10,7L8,11H11V17H5V11L7,7H10M18,7L16,11H19V17H13V11L15,7H18Z";
const FORMAT_QUOTE_CLOSE =
  "M14,17H17L19,13V7H13V13H16M6,17H9L11,13V7H5V13H8L6,17Z";

export interface ElmBlockQuoteProps extends JSX.BlockquoteHTMLAttributes<HTMLQuoteElement> {}

export const ElmBlockQuote = (props: ElmBlockQuoteProps) => {
  const [local, rest] = splitProps(props, ["class", "children"]);

  return (
    <blockquote
      {...rest}
      class={clsx(styles["elm-block-quote"], textStyles.text, local.class)}
    >
      <div class={clsx(styles.icon, styles["icon-top-left"])}>
        <ElmMdiIcon path={FORMAT_QUOTE_OPEN} />
      </div>

      <div class={styles.body}>{local.children}</div>

      <div class={clsx(styles.icon, styles["icon-bottom-right"])}>
        <ElmMdiIcon path={FORMAT_QUOTE_CLOSE} />
      </div>
    </blockquote>
  );
};
