// packages/react/src/components/table/ElmTableCell.tsx
import React, { useContext } from "react";

import "@styles/global.css";
import styles from "./ElmTableCell.module.css";

import { HasHeaderContext } from "./TableContext";

export interface ElmTableCellProps extends React.PropsWithChildren {
  style?: React.CSSProperties;

  /**
   * Whether the cell is a header cell.
   */
  hasHeader?: boolean;

  /**
   * The text content of the cell.
   * If not provided, the cell will render its children as content.
   */
  text?: string;
}

export const ElmTableCell = ({
  children,
  style,
  hasHeader = false,
  text,
}: ElmTableCellProps) => {
  const hasHeaderInjected = useContext(HasHeaderContext);
  const isHeader = hasHeader || hasHeaderInjected;
  const Tag = isHeader ? "th" : "td";

  return (
    <Tag
      className={`${styles.common} ${isHeader ? styles.th : styles.td}`}
      style={style}
    >
      {text != null ? text : children}
    </Tag>
  );
};

// packages/qwik/src/components/table/elm-table-cell.tsx
import {
  component$,
  Slot,
  useContext,
  type CSSProperties,
} from "@qwik.dev/core";
import styles from "./elm-table-cell.module.css";
import { HasHeaderContext } from "./elm-table-header";

export interface ElmTableCellProps {
  class?: string;

  style?: CSSProperties;

  /**
   * Whether the cell is a header cell.
   */
  hasHeader?: boolean;

  /**
   * The text content of the cell.
   * If not provided, the cell will render its children as content.
   */
  text?: string;
}

export const ElmTableCell = component$<ElmTableCellProps>((props) => {
  const { class: className, style, hasHeader = false, text } = props;
  const hasHeaderInjected = useContext(HasHeaderContext, false);

  const isHeader = hasHeader || (hasHeaderInjected as boolean | undefined);

  return (
    <>
      {isHeader ? (
        <th class={[styles.common, styles.th, className]} style={style}>
          {text ? text : <Slot />}
        </th>
      ) : (
        <td class={[styles.common, styles.td, className]} style={style}>
          {text ? text : <Slot />}
        </td>
      )}
    </>
  );
});
