// packages/react/src/components/table/elm-table-row.tsx
import type { ComponentPropsWithoutRef } from "react";
import { clsx } from "clsx";

import styles from "./elm-table-row.module.css";

export type ElmTableRowProps = ComponentPropsWithoutRef<"tr">;

export const ElmTableRow = ({
  className,
  children,
  ...props
}: ElmTableRowProps) => {
  return (
    <tr className={clsx(styles["elm-table-row"], className)} {...props}>
      {children}
    </tr>
  );
};

// packages/qwik/src/components/table/elm-table-row.tsx
import { component$, PropsOf, Slot } from "@qwik.dev/core";
import styles from "./elm-table-row.module.css";

export type ElmTableRowProps = PropsOf<"tr">;

export const ElmTableRow = component$<PropsOf<"tr">>(
  ({ class: className, ...props }) => {
    return (
      <tr class={[styles["elm-table-row"], className]} {...props}>
        <Slot />
      </tr>
    );
  },
);
