// packages/react/src/components/table/elm-table-header.tsx
import type { ComponentPropsWithoutRef } from "react";
import { clsx } from "clsx";

import styles from "./elm-table-header.module.css";
import { TableSectionContext } from "./table-context";

export type ElmTableHeaderProps = ComponentPropsWithoutRef<"thead">;

export const ElmTableHeader = ({
  className,
  children,
  ...props
}: ElmTableHeaderProps) => {
  return (
    <TableSectionContext.Provider value="head">
      <thead className={clsx(styles["elm-table-header"], className)} {...props}>
        {children}
      </thead>
    </TableSectionContext.Provider>
  );
};

// packages/qwik/src/components/table/elm-table-header.tsx
import { component$, PropsOf, Slot, useContextProvider } from "@qwik.dev/core";
import styles from "./elm-table-header.module.css";
import { TableSectionContext } from "./table-context";

export type ElmTableHeaderProps = PropsOf<"thead">;

export const ElmTableHeader = component$<PropsOf<"thead">>(
  ({ class: className, ...props }) => {
    useContextProvider(TableSectionContext, "head");

    return (
      <thead class={[styles["elm-table-header"], className]} {...props}>
        <Slot />
      </thead>
    );
  },
);
