// packages/react/src/components/form/ElmValidation.tsx
import React from "react";

import "@styles/global.css";
import styles from "./ElmValidation.module.css";

import { ElmMdiIcon } from "@components/icon/ElmMdiIcon";
import { mdiCheckCircle, mdiCheckCircleOutline } from "@mdi/js";

export interface ElmValidationCSSVariables {
  "--opacity"?: number;
}

export interface ElmValidationProps {
  style?: React.CSSProperties & ElmValidationCSSVariables;

  /** The validation message text. */
  text: string;

  /** The color when valid. */
  validColor?: string;

  /** Whether the validation is satisfied. */
  isValid: boolean;
}

export const ElmValidation = ({
  validColor = "#449763",
  ...props
}: ElmValidationProps) => {
  return (
    <div
      className={styles.validation}
      style={
        {
          "--opacity": props.isValid ? 1 : 0.5,
          ...props.style,
        } as React.CSSProperties
      }
    >
      <ElmMdiIcon
        d={props.isValid ? mdiCheckCircle : mdiCheckCircleOutline}
        color={props.isValid ? validColor : undefined}
      />
      <span style={{ color: props.isValid ? validColor : undefined }}>
        {props.text}
      </span>
    </div>
  );
};

// packages/qwik/src/components/form/elm-validation.tsx
import { component$, PropsOf, type CSSProperties } from "@qwik.dev/core";
import { mdiCheckCircle, mdiCheckCircleOutline } from "@mdi/js";

import { ElmMdiIcon } from "../icon/elm-mdi-icon";
import { ElmInlineText } from "../typography/elm-inline-text";

import styles from "./elm-validation.module.css";

export interface ElmValidationProps extends PropsOf<"div"> {
  text: string;
  validColor?: string;
  isValid: boolean;
}

export const ElmValidation = component$<ElmValidationProps>(
  ({ class: className, style, text, validColor = "#449763", isValid, ...props }) => {
    return (
      <div
        class={[styles.validation, className]}
        style={{
          "--opacity": isValid ? 1 : 0.5,
          ...(style as CSSProperties),
        } as CSSProperties}
        {...props}
      >
        <ElmMdiIcon
          d={isValid ? mdiCheckCircle : mdiCheckCircleOutline}
          color={isValid ? validColor : undefined}
        />
        <ElmInlineText color={isValid ? validColor : undefined}>
          {text}
        </ElmInlineText>
      </div>
    );
  },
);
