// packages/react/src/components/form/elm-text-area.tsx
import {
  useState,
  type ComponentPropsWithoutRef,
  type FocusEvent,
  type ReactNode,
} from "react";
import { clsx } from "clsx";
import { mdiTextLong } from "@mdi/js";

import { ElmMdiIcon } from "../icon/elm-mdi-icon";
import { ElmInlineText } from "../typography/elm-inline-text";

import styles from "./elm-text-area.module.css";

// Display/form dual-use component: intentionally does NOT adopt
// `useControllableState`. The display case (read-only or upstream-driven
// text) has no "uncontrolled with default" semantic to model, so a
// direct native `value` / `defaultValue` passthrough is preferred over the
// controlled/uncontrolled split.
export interface ElmTextAreaProps extends ComponentPropsWithoutRef<"textarea"> {
  label: string;

  /**
   * Custom icon rendered in the header. Defaults to a text-long glyph.
   */
  icon?: ReactNode;

  isLoading?: boolean;

  /**
   * Visible rows on initial render. The textarea is vertically
   * resizable by default, so this is a starting height, not a cap.
   */
  rows?: number;
}

export const ElmTextArea = ({
  className,
  style,
  label,
  icon,
  maxLength,
  placeholder,
  disabled,
  isLoading,
  required,
  value,
  defaultValue,
  rows = 3,
  onInput,
  onFocus,
  onBlur,
  ...rest
}: ElmTextAreaProps) => {
  const [isFocused, setIsFocused] = useState(false);

  // The counter reflects the live textarea length. When the parent controls
  // `value`, that drives the display directly; otherwise we track the latest
  // input locally, seeded from `defaultValue`.
  const hasTrackedValue = value != null || defaultValue != null;
  const [internalLength, setInternalLength] = useState(
    () => String(defaultValue ?? "").length,
  );
  const length = value != null ? String(value).length : internalLength;

  const handleInput: NonNullable<ElmTextAreaProps["onInput"]> = (event) => {
    setInternalLength(event.currentTarget.value.length);
    onInput?.(event);
  };

  const handleFocus = (event: FocusEvent<HTMLTextAreaElement>) => {
    setIsFocused(true);
    onFocus?.(event);
  };

  const handleBlur = (event: FocusEvent<HTMLTextAreaElement>) => {
    setIsFocused(false);
    onBlur?.(event);
  };

  return (
    <label
      className={clsx(
        styles["elm-text-area"],
        isFocused && styles.active,
        (disabled || isLoading) && styles.disabled,
        className,
      )}
      style={style}
    >
      <span
        className={clsx(styles.header, isFocused && styles["label-active"])}
      >
        {icon ?? <ElmMdiIcon path={mdiTextLong} size="0.75rem" />}
        <span>
          {label}
          {required && <span className={styles.requierd}>*</span>}
        </span>
        {hasTrackedValue && (
          <ElmInlineText
            color={
              maxLength != null && length > maxLength
                ? "var(--elmethis-color-accent-error)"
                : "gray"
            }
            size="0.75rem"
          >
            {maxLength != null ? `${length} / ${maxLength}` : `${length}`}
          </ElmInlineText>
        )}
      </span>

      <div className={styles.body}>
        <textarea
          value={value}
          defaultValue={defaultValue}
          rows={rows}
          maxLength={maxLength}
          className={styles.textarea}
          placeholder={placeholder}
          onFocus={handleFocus}
          onBlur={handleBlur}
          disabled={disabled || isLoading}
          style={{
            cursor: disabled ? "not-allowed" : isLoading ? "progress" : "auto",
          }}
          aria-required={required}
          onInput={handleInput}
          {...rest}
        />
      </div>

      <div
        className={styles.loading}
        style={{
          opacity: isLoading ? 1 : 0,
        }}
      ></div>
    </label>
  );
};

// packages/qwik/src/components/form/elm-text-area.tsx
import {
  $,
  component$,
  PropsOf,
  Slot,
  useSignal,
  type Signal,
} from "@qwik.dev/core";
import { mdiTextLong } from "@mdi/js";

import { ElmMdiIcon } from "../icon/elm-mdi-icon";
import { ElmInlineText } from "../typography/elm-inline-text";

import styles from "./elm-text-area.module.css";

// Display/form dual-use component: intentionally does NOT adopt
// `useBindableSignal`. The display case (read-only or upstream-driven
// text) has no "uncontrolled with default" semantic to model, so a
// direct `value: Signal<string>` binding is preferred over the
// controlled/uncontrolled split.
export interface ElmTextAreaProps extends Omit<PropsOf<"label">, "onInput$"> {
  label: string;
  maxLength?: number;
  placeholder?: string;
  disabled?: boolean;
  isLoading?: boolean;
  required?: boolean;

  /**
   * Controlled value. When provided the parent owns the state.
   */
  value?: Signal<string>;

  /**
   * Visible rows on initial render. The textarea is vertically
   * resizable by default, so this is a starting height, not a cap.
   */
  rows?: number;
}

export const ElmTextArea = component$<ElmTextAreaProps>((props) => {
  const {
    class: className,
    style,
    label,
    maxLength,
    placeholder,
    disabled,
    isLoading,
    required,
    value,
    rows = 3,
    ...rest
  } = props;

  const isFocused = useSignal(false);

  return (
    <label
      class={[
        styles["elm-text-area"],
        isFocused.value && styles.active,
        className,
        {
          [styles.disabled]: disabled || isLoading,
        },
      ]}
      style={style}
      {...rest}
    >
      <span
        class={[styles.header, { [styles["label-active"]]: isFocused.value }]}
      >
        <Slot name="icon">
          <ElmMdiIcon path={mdiTextLong} size="0.75rem" />
        </Slot>
        <span>
          {label}
          {required && <span class={styles.requierd}>*</span>}
        </span>
        {value != null && (
          <ElmInlineText
            color={
              maxLength != null && value.value.length > maxLength
                ? "var(--elmethis-color-accent-error)"
                : "gray"
            }
            size="0.75rem"
          >
            {maxLength != null
              ? `${value.value.length} / ${maxLength}`
              : `${value.value.length}`}
          </ElmInlineText>
        )}
      </span>

      <div class={styles.body}>
        <textarea
          value={value?.value}
          rows={rows}
          class={styles.textarea}
          placeholder={placeholder}
          onFocus$={() => (isFocused.value = true)}
          onBlur$={() => (isFocused.value = false)}
          disabled={disabled || isLoading}
          style={{
            cursor: disabled ? "not-allowed" : isLoading ? "progress" : "auto",
          }}
          aria-required={required}
          onInput$={$((_, el: HTMLTextAreaElement) => {
            if (value) value.value = el.value;
          })}
        />
      </div>

      <div
        class={styles.loading}
        style={{
          opacity: isLoading ? 1 : 0,
        }}
      ></div>
    </label>
  );
});
