// packages/react/src/components/form/elm-text-field.tsx
import {
  useRef,
  useState,
  type ComponentPropsWithoutRef,
  type CSSProperties,
  type ReactNode,
} from "react";
import { clsx } from "clsx";
import {
  mdiEyeOffOutline,
  mdiEyeOutline,
  mdiText,
  mdiTrashCanOutline,
} from "@mdi/js";

import { ElmMdiIcon } from "../icon/elm-mdi-icon";
import { ElmInlineText } from "../typography/elm-inline-text";

import styles from "./elm-text-field.module.css";

export interface ElmTextFieldProps extends Omit<
  ComponentPropsWithoutRef<"input">,
  "prefix"
> {
  label: string;
  maxLength?: number;
  prefix?: string;
  suffix?: string;
  placeholder?: string;
  disabled?: boolean;
  isLoading?: boolean;

  /**
   * The leading icon slot. Defaults to an `mdiText` icon.
   */
  icon?: ReactNode;

  isPassword?: boolean;
  required?: boolean;
}

export const ElmTextField = ({
  className,
  style,
  label,
  maxLength,
  prefix,
  suffix,
  placeholder,
  disabled,
  isLoading,
  icon,
  value,
  isPassword,
  required,
  onFocus,
  onBlur,
  ...rest
}: ElmTextFieldProps) => {
  const inputRef = useRef<HTMLInputElement>(null);

  const [isFocused, setIsFocused] = useState(false);
  const [inputType, setInputType] = useState(isPassword ? "password" : "text");

  // Mirrors the qwik twin's clear/toggle imperative writes: dispatch a native
  // input event so a parent listening on `onChange`/`onInput` is notified.
  const setNativeValue = (next: string) => {
    const el = inputRef.current;
    if (!el) return;
    const setter = Object.getOwnPropertyDescriptor(
      window.HTMLInputElement.prototype,
      "value",
    )?.set;
    setter?.call(el, next);
    el.dispatchEvent(new Event("input", { bubbles: true }));
  };

  const valueLength = value != null ? String(value).length : 0;

  return (
    <label
      className={clsx(
        styles["elm-text-field"],
        isFocused && styles.active,
        (disabled || isLoading) && styles.disabled,
        className,
      )}
      style={style}
    >
      <span
        className={clsx(styles.header, isFocused && styles["label-active"])}
      >
        {icon ?? <ElmMdiIcon d={mdiText} size="0.75rem" />}
        <span>
          {label}
          {required && <span className={styles.requierd}>*</span>}
        </span>
        {value != null && (
          <ElmInlineText
            color={
              maxLength != null && valueLength > maxLength
                ? "var(--elmethis-color-accent-error)"
                : "gray"
            }
            size="0.75rem"
          >
            {maxLength != null
              ? `${valueLength} / ${maxLength}`
              : `${valueLength}`}
          </ElmInlineText>
        )}
      </span>

      <div className={styles.body}>
        {prefix && <span className={styles["prefix-suffix"]}>{prefix}</span>}
        <input
          {...rest}
          ref={inputRef}
          value={value}
          type={inputType}
          className={styles.input}
          placeholder={placeholder}
          onFocus={(event) => {
            setIsFocused(true);
            onFocus?.(event);
          }}
          onBlur={(event) => {
            setIsFocused(false);
            onBlur?.(event);
          }}
          disabled={disabled || isLoading}
          style={{
            cursor: disabled ? "not-allowed" : isLoading ? "progress" : "auto",
          }}
          aria-required={required}
        />

        <div className={styles["right-icon-box"]}>
          <span className={styles["prefix-suffix"]}>
            {suffix != null && <ElmInlineText>{suffix}</ElmInlineText>}
          </span>

          <div
            className={styles["clickable-icon"]}
            onClick={() => {
              if (!isLoading && !disabled) {
                setInputType((prev) => (prev === "text" ? "password" : "text"));
              }
            }}
          >
            <ElmMdiIcon
              d={inputType === "text" ? mdiEyeOutline : mdiEyeOffOutline}
              size="1.25rem"
              color="gray"
            />
          </div>

          <div
            className={styles["clickable-icon"]}
            onClick={() => {
              if (!isLoading && !disabled) {
                setNativeValue("");
              }
            }}
          >
            <ElmMdiIcon d={mdiTrashCanOutline} size="1.25rem" color="gray" />
          </div>
        </div>
      </div>

      <div
        className={styles.loading}
        style={{ opacity: isLoading ? 1 : 0 } as CSSProperties}
      ></div>
    </label>
  );
};

// packages/qwik/src/components/form/elm-text-field.tsx
import {
  $,
  component$,
  PropsOf,
  useSignal,
  type CSSProperties,
  type JSXOutput,
  type Signal,
} from "@builder.io/qwik";
import {
  mdiEyeOffOutline,
  mdiEyeOutline,
  mdiText,
  mdiTrashCanOutline,
} from "@mdi/js";

import { ElmMdiIcon } from "../icon/elm-mdi-icon";
import { ElmInlineText } from "../typography/elm-inline-text";

import styles from "./elm-text-field.module.css";

export interface ElmTextFieldProps extends Omit<PropsOf<"label">, "onInput$"> {
  label: string;
  maxLength?: number;
  prefix?: string;
  suffix?: string;
  placeholder?: string;
  disabled?: boolean;
  loading?: boolean;

  /**
   * Controlled value. When provided the parent owns the state.
   */
  value?: Signal<string>;

  /**
   * Icon displayed on the left side of the input.
   *
   * @example <ElmTextField icon={<ElmInlineIcon src={url} />} label="..." />
   */
  icon?: JSXOutput;
  isPassword?: boolean;
  required?: boolean;
}

export const ElmTextField = component$<ElmTextFieldProps>((props) => {
  const {
    class: className,
    style,
    label,
    maxLength,
    prefix,
    suffix,
    placeholder,
    disabled,
    loading,
    value,
    icon,
    isPassword,
    required,
    ...rest
  } = props;

  const isFocused = useSignal(false);
  const inputType = useSignal(isPassword ? "password" : "text");

  return (
    <label
      class={[styles.wrapper, isFocused.value && styles.active, className]}
      style={
        {
          backgroundColor: disabled || loading ? "rgba(0,0,0,0.15)" : undefined,
          ...(style as CSSProperties),
        } as CSSProperties
      }
      {...rest}
    >
      <span
        class={[styles.header, { [styles["label-active"]]: isFocused.value }]}
      >
        {icon ? (
          <div class={styles.icon}>{icon}</div>
        ) : (
          <ElmMdiIcon d={mdiText} size="0.75rem" />
        )}
        <span>
          {label}
          {required && <span class={styles.requierd}>*</span>}
        </span>
        {maxLength != null && (
          <ElmInlineText
            text={`${value?.value.length} / ${maxLength}`}
            color={(value?.value.length ?? -1) > maxLength ? "#c56565" : "gray"}
            size="0.75rem"
          />
        )}
      </span>

      <div class={styles.body}>
        {prefix && <span class={styles["prefix-suffix"]}>{prefix}</span>}
        <input
          value={value?.value}
          type={inputType.value}
          class={styles.input}
          placeholder={placeholder}
          onFocus$={() => (isFocused.value = true)}
          onBlur$={() => (isFocused.value = false)}
          disabled={disabled || loading}
          style={{
            cursor: disabled ? "not-allowed" : loading ? "progress" : "auto",
          }}
          aria-required={required}
          onInput$={$((_, el: HTMLInputElement) => {
            if (value) value.value = el.value;
          })}
        />

        <div class={styles["right-icon-box"]}>
          <span class={styles["prefix-suffix"]}>
            {suffix != null && <ElmInlineText text={suffix} />}
          </span>

          <div
            class={styles["clickable-icon"]}
            onClick$={$(() => {
              if (!props.loading && !props.disabled) {
                inputType.value =
                  inputType.value === "text" ? "password" : "text";
              }
            })}
          >
            <ElmMdiIcon
              d={inputType.value === "text" ? mdiEyeOutline : mdiEyeOffOutline}
              size="1.25rem"
              color="gray"
            />
          </div>

          <div
            class={styles["clickable-icon"]}
            onClick$={$(() => {
              if (!props.loading && !props.disabled && value) {
                value.value = "";
              }
            })}
          >
            <ElmMdiIcon d={mdiTrashCanOutline} size="1.25rem" color="gray" />
          </div>
        </div>
      </div>

      <div
        class={styles.loading}
        style={{
          opacity: loading ? 0.2 : 0,
        }}
      ></div>
    </label>
  );
});
