// packages/react/src/components/table/elm-table.tsx
import type { ComponentPropsWithoutRef } from "react";
import { useEffect, useMemo, useRef, useState } from "react";
import { clsx } from "clsx";

import styles from "./elm-table.module.css";
import textStyles from "../../styles/text.module.css";
import { ElmInlineText } from "../typography/elm-inline-text";
import { HasRowHeaderContext } from "./table-context";

export interface ElmTableProps extends ComponentPropsWithoutRef<"table"> {
  caption?: string;

  hasRowHeader?: boolean;
}

/**
 * Tracks horizontal overflow of the scroll container so the table can react to
 * it: expose a keyboard-focusable, labeled scroll region only while it actually
 * overflows, and reveal edge shadows that hint at columns past the viewport.
 *
 * Server render reports "no overflow" (the effect never runs), so the scroll
 * affordances are pure progressive enhancement and never reach the SSR markup.
 */
const useScrollOverflow = () => {
  const ref = useRef<HTMLDivElement>(null);
  const [edges, setEdges] = useState({
    canScroll: false,
    atStart: true,
    atEnd: true,
  });

  useEffect(() => {
    const el = ref.current;
    if (el == null) return;

    const measure = () => {
      const max = el.scrollWidth - el.clientWidth;
      const next = {
        canScroll: max > 1,
        atStart: el.scrollLeft <= 1,
        atEnd: el.scrollLeft >= max - 1,
      };
      setEdges((prev) =>
        prev.canScroll === next.canScroll &&
        prev.atStart === next.atStart &&
        prev.atEnd === next.atEnd
          ? prev
          : next,
      );
    };

    measure();
    el.addEventListener("scroll", measure, { passive: true });
    const observer = new ResizeObserver(measure);
    observer.observe(el);
    return () => {
      el.removeEventListener("scroll", measure);
      observer.disconnect();
    };
  }, []);

  return { ref, ...edges };
};

export const ElmTable = ({
  className,
  caption,
  hasRowHeader = false,
  children,
  ...rest
}: ElmTableProps) => {
  const hasRowHeaderValue = useMemo(
    () => ({ value: hasRowHeader }),
    [hasRowHeader],
  );

  const { ref, canScroll, atStart, atEnd } = useScrollOverflow();

  return (
    <HasRowHeaderContext.Provider value={hasRowHeaderValue}>
      <div
        className={styles["elm-table-frame"]}
        data-overflow-start={canScroll && !atStart ? "" : undefined}
        data-overflow-end={canScroll && !atEnd ? "" : undefined}
      >
        <div
          ref={ref}
          className={styles["elm-table-scroll"]}
          tabIndex={canScroll ? 0 : undefined}
          role={canScroll && caption != null ? "region" : undefined}
          aria-label={canScroll && caption != null ? caption : undefined}
        >
          <table
            className={clsx(
              styles["elm-table"],
              textStyles.text,
              hasRowHeader && styles["sticky-row-header"],
              className,
            )}
            {...rest}
          >
            {caption && (
              <caption>
                <span className={styles.caption}>
                  <span className={styles.spacing}></span>

                  <span className={styles["caption-inner"]}>
                    <ElmInlineText>{caption}</ElmInlineText>
                  </span>

                  <span className={styles.spacing}></span>
                </span>
              </caption>
            )}
            {children}
          </table>
        </div>
      </div>
    </HasRowHeaderContext.Provider>
  );
};

// packages/vue/src/components/table/elm-table.tsx
import {
  computed,
  defineComponent,
  onBeforeUnmount,
  onMounted,
  provide,
  ref,
  type HTMLAttributes,
} from "vue";
import { clsx } from "clsx";

import styles from "./elm-table.module.css";
import textStyles from "../../styles/text.module.css";
import { ElmInlineText } from "../typography/elm-inline-text";
import { HasRowHeaderContext } from "./table-context";

export interface ElmTableProps extends HTMLAttributes {
  caption?: string;

  hasRowHeader?: boolean;
}

export const ElmTable = defineComponent({
  name: "ElmTable",
  // Wrappers now sit above <table>, so attr fallthrough is disabled and the
  // native attrs (class, id, style, listeners…) are forwarded onto <table>
  // manually below — matching where they landed before the wrappers existed.
  inheritAttrs: false,
  props: {
    caption: { type: String, default: undefined },
    hasRowHeader: { type: Boolean, default: false },
  },
  setup(props, { attrs, slots }) {
    provide(
      HasRowHeaderContext,
      computed(() => props.hasRowHeader),
    );

    // Horizontal-overflow state, mirrored from the scroll container so the
    // table can expose a keyboard-focusable, labeled scroll region only while
    // it overflows and reveal edge shadows that hint at columns past the
    // viewport. Stays false during SSR, so the scroll affordances are pure
    // progressive enhancement and never reach the server markup.
    const scrollRef = ref<HTMLDivElement | null>(null);
    const canScroll = ref(false);
    const atStart = ref(true);
    const atEnd = ref(true);

    const measure = () => {
      const el = scrollRef.value;
      if (el == null) {
        return;
      }
      const max = el.scrollWidth - el.clientWidth;
      canScroll.value = max > 1;
      atStart.value = el.scrollLeft <= 1;
      atEnd.value = el.scrollLeft >= max - 1;
    };

    let observer: ResizeObserver | null = null;
    onMounted(() => {
      const el = scrollRef.value;
      if (el == null) {
        return;
      }
      measure();
      el.addEventListener("scroll", measure, { passive: true });
      // Guarded for the jsdom test env, which lacks ResizeObserver.
      if (typeof ResizeObserver !== "undefined") {
        observer = new ResizeObserver(measure);
        observer.observe(el);
      }
    });
    onBeforeUnmount(() => {
      scrollRef.value?.removeEventListener("scroll", measure);
      observer?.disconnect();
    });

    return () => {
      const { class: className, ...restAttrs } = attrs as Record<
        string,
        unknown
      >;

      return (
        <div
          class={styles["elm-table-frame"]}
          data-overflow-start={
            canScroll.value && !atStart.value ? "" : undefined
          }
          data-overflow-end={canScroll.value && !atEnd.value ? "" : undefined}
        >
          <div
            ref={scrollRef}
            class={styles["elm-table-scroll"]}
            tabindex={canScroll.value ? 0 : undefined}
            role={
              canScroll.value && props.caption != null ? "region" : undefined
            }
            aria-label={
              canScroll.value && props.caption != null
                ? props.caption
                : undefined
            }
          >
            <table
              class={clsx(
                styles["elm-table"],
                textStyles.text,
                props.hasRowHeader && styles["sticky-row-header"],
                className as string | undefined,
              )}
              {...restAttrs}
            >
              {props.caption && (
                <caption>
                  <span class={styles.caption}>
                    <span class={styles.spacing}></span>

                    <span class={styles["caption-inner"]}>
                      <ElmInlineText>{props.caption}</ElmInlineText>
                    </span>

                    <span class={styles.spacing}></span>
                  </span>
                </caption>
              )}
              {slots.default?.()}
            </table>
          </div>
        </div>
      );
    };
  },
});
