// packages/react/src/components/table/elm-table-row.tsx
import type { ComponentPropsWithoutRef } from "react";
import { clsx } from "clsx";

import styles from "./elm-table-row.module.css";

export type ElmTableRowProps = ComponentPropsWithoutRef<"tr">;

export const ElmTableRow = ({
  className,
  children,
  ...props
}: ElmTableRowProps) => {
  return (
    <tr className={clsx(styles["elm-table-row"], className)} {...props}>
      {children}
    </tr>
  );
};

// packages/vue/src/components/table/elm-table-row.tsx
import { defineComponent, type HTMLAttributes } from "vue";
import { clsx } from "clsx";

import styles from "./elm-table-row.module.css";

export type ElmTableRowProps = HTMLAttributes;

export const ElmTableRow = defineComponent({
  name: "ElmTableRow",
  setup(_, { slots }) {
    // Fallthrough class merges with the binding below.
    return () => (
      <tr class={clsx(styles["elm-table-row"])}>{slots.default?.()}</tr>
    );
  },
});
