// packages/react/src/components/fallback/elm-block-fallback.tsx
import type { ComponentPropsWithoutRef, CSSProperties } from "react";
import { clsx } from "clsx";

import styles from "./elm-block-fallback.module.css";
import { ElmDotLoadingIcon } from "../icon/elm-dot-loading-icon";
import { ElmRectangleWave } from "./elm-rectangle-wave";

export interface ElmBlockFallbackProps extends ComponentPropsWithoutRef<"div"> {
  height?: CSSProperties["height"];
}

export const ElmBlockFallback = ({
  className,
  style,
  height = "16rem",
  ...props
}: ElmBlockFallbackProps) => {
  return (
    <div
      className={clsx(styles["elm-block-fallback"], className)}
      style={
        {
          "--elmethis-scoped-height": height,
          ...style,
        } as CSSProperties
      }
      {...props}
    >
      <ElmDotLoadingIcon />
      <ElmRectangleWave />
    </div>
  );
};

// packages/qwik/src/components/fallback/elm-block-fallback.tsx
import { component$, PropsOf, type CSSProperties } from "@qwik.dev/core";

import styles from "./elm-block-fallback.module.css";
import { ElmDotLoadingIcon } from "../icon/elm-dot-loading-icon";
import { ElmRectangleWave } from "./elm-rectangle-wave";

export interface ElmBlockFallbackProps extends PropsOf<"div"> {
  height?: CSSProperties["height"];
}

export const ElmBlockFallback = component$<ElmBlockFallbackProps>(
  ({ class: className, style, height = "16rem", ...props }) => {
    return (
      <div
        class={[styles["block-fallback"], className]}
        style={
          { "--elmethis-scoped-height": height, ...(style as CSSProperties) } as CSSProperties
        }
        {...props}
      >
        <ElmDotLoadingIcon />
        <ElmRectangleWave />
      </div>
    );
  },
);
