// packages/react/src/components/containments/ElmParallax.tsx
import React, { useEffect, useState } from "react";

import "@styles/global.css";
import styles from "./ElmParallax.module.css";

export interface ElmParallaxCSSVariables {}

export interface ElmParallaxProps {
  style?: React.CSSProperties & ElmParallaxCSSVariables;

  /** First background image URL. */
  imageUrl1: string;

  /** Second background image URL. */
  imageUrl2: string;
}

export const ElmParallax = (props: ElmParallaxProps) => {
  const [scrollY, setScrollY] = useState(0);

  useEffect(() => {
    let rafId: number | null = null;

    const handleScroll = () => {
      if (rafId != null) return;
      rafId = requestAnimationFrame(() => {
        setScrollY(window.scrollY);
        rafId = null;
      });
    };

    window.addEventListener("scroll", handleScroll, { passive: true });
    return () => {
      window.removeEventListener("scroll", handleScroll);
      if (rafId != null) cancelAnimationFrame(rafId);
    };
  }, []);

  return (
    <>
      <div
        className={styles.parallax}
        style={{
          backgroundImage: `url(${props.imageUrl1})`,
          transform: `scale(1.2) translateY(${scrollY / 400}%)`,
          transformOrigin: "bottom",
          ...props.style,
        }}
      ></div>
      <div
        className={styles.parallax}
        style={{
          backgroundImage: `url(${props.imageUrl2})`,
          transform: `scale(1.2) translateY(${scrollY / 900}%)`,
          transformOrigin: "bottom",
        }}
      ></div>
    </>
  );
};

// packages/solid/src/components/containments/elm-parallax.tsx
import {
  createSignal,
  For,
  onCleanup,
  onMount,
  splitProps,
  type JSX,
} from "solid-js";

import styles from "./elm-parallax.module.css";

export interface ElmParallaxProps extends JSX.HTMLAttributes<HTMLDivElement> {
  images: string[];
}

export const ElmParallax = (props: ElmParallaxProps) => {
  const [local, rest] = splitProps(props, ["class", "images"]);
  const [scrollY, setScrollY] = createSignal(0);

  onMount(() => {
    const handleScroll = () => setScrollY(window.scrollY);

    window.addEventListener("scroll", handleScroll, { passive: true });
    onCleanup(() => window.removeEventListener("scroll", handleScroll));
  });

  return (
    <div class={local.class} {...rest}>
      <div class={styles["parallax-watcher"]} />
      <For each={local.images}>
        {(image, index) => (
          <div
            aria-hidden="true"
            class={styles.parallax}
            style={{
              "background-image": `url(${image})`,
              transform: `scale(1.2) translateY(${scrollY() / (1000 * (index() + 1))}%)`,
              "transform-origin": "bottom",
            }}
          />
        )}
      </For>
    </div>
  );
};
