// packages/react/src/components/media/elm-file.tsx
import type { ComponentPropsWithoutRef } from "react";
import { clsx } from "clsx";
import { mdiDownload, mdiFile } from "@mdi/js";

import styles from "./elm-file.module.css";
import { ElmMdiIcon } from "../icon/elm-mdi-icon";
import { ElmInlineText } from "../typography/elm-inline-text";

export interface ElmFileProps extends ComponentPropsWithoutRef<"div"> {
  /**
   * The name of the file.
   */
  name?: string;

  /**
   * The source of the file.
   */
  src: string;

  /**
   * The size of the file in bytes.
   */
  filesize?: string;
}

function getLastPathSegmentWithoutQueryOrHash(
  urlString: string,
): string | null {
  const cleanedUrl = urlString.split(/[?#]/)[0];
  const pathSegments = cleanedUrl.split("/").filter(Boolean);
  return pathSegments.length > 0 ? pathSegments[pathSegments.length - 1] : null;
}

export const ElmFile = ({
  className,
  name,
  src,
  filesize,
  ...props
}: ElmFileProps) => {
  const downloadFile = async () => {
    let link: HTMLAnchorElement | undefined;
    try {
      const response = await fetch(src);
      if (!response.ok) {
        throw new Error("Failed to download file");
      }

      const blob = await response.blob();

      link = document.createElement("a");
      link.href = URL.createObjectURL(blob);
      link.download =
        name ?? getLastPathSegmentWithoutQueryOrHash(src) ?? "file";
      link.click();
    } catch (error) {
      console.error("ERROR:", error);
    } finally {
      if (link) {
        URL.revokeObjectURL(link.href);
      }
    }
  };

  return (
    <div className={clsx(styles["elm-file"], className)} {...props}>
      <div>
        <ElmMdiIcon path={mdiFile} size="1.25rem" />
      </div>

      <div>
        <ElmInlineText>
          {name ?? getLastPathSegmentWithoutQueryOrHash(src)}
        </ElmInlineText>
      </div>

      <div className={styles["file-size"]}>
        <ElmInlineText>{filesize}</ElmInlineText>
      </div>

      <div
        className={styles["download-icon"]}
        onClick={() => {
          void downloadFile();
        }}
      >
        <ElmMdiIcon path={mdiDownload} size="1.25rem" />
      </div>
    </div>
  );
};

// packages/vue/src/components/media/elm-file.tsx
import { defineComponent, type HTMLAttributes } from "vue";
import { clsx } from "clsx";
import { mdiDownload, mdiFile } from "@mdi/js";

import styles from "./elm-file.module.css";
import { ElmMdiIcon } from "../icon/elm-mdi-icon";
import { ElmInlineText } from "../typography/elm-inline-text";

export interface ElmFileProps extends HTMLAttributes {
  /**
   * The name of the file.
   */
  name?: string;

  /**
   * The source of the file.
   */
  src: string;

  /**
   * The size of the file in bytes.
   */
  filesize?: string;
}

function getLastPathSegmentWithoutQueryOrHash(
  urlString: string,
): string | null {
  const cleanedUrl = urlString.split(/[?#]/)[0];
  const pathSegments = cleanedUrl.split("/").filter(Boolean);
  return pathSegments.length > 0 ? pathSegments[pathSegments.length - 1] : null;
}

export const ElmFile = defineComponent({
  name: "ElmFile",
  props: {
    name: { type: String, default: undefined },
    src: { type: String, required: true },
    filesize: { type: String, default: undefined },
  },
  setup(props) {
    const downloadFile = async (): Promise<void> => {
      let link: HTMLAnchorElement | undefined;
      try {
        const response = await fetch(props.src);
        if (!response.ok) throw new Error("Failed to download file");

        const blob = await response.blob();

        link = document.createElement("a");
        link.href = URL.createObjectURL(blob);
        link.download =
          props.name ??
          getLastPathSegmentWithoutQueryOrHash(props.src) ??
          "file";
        link.click();
      } catch (error) {
        console.error("ERROR:", error);
      } finally {
        if (link) URL.revokeObjectURL(link.href);
      }
    };

    // inheritAttrs default: passthrough class/style merge onto the root.
    return () => (
      <div class={clsx(styles["elm-file"])}>
        <div>
          <ElmMdiIcon path={mdiFile} size="1.25rem" />
        </div>

        <div>
          <ElmInlineText>
            {props.name ?? getLastPathSegmentWithoutQueryOrHash(props.src)}
          </ElmInlineText>
        </div>

        <div class={styles["file-size"]}>
          <ElmInlineText>{props.filesize}</ElmInlineText>
        </div>

        <div class={styles["download-icon"]} onClick={downloadFile}>
          <ElmMdiIcon path={mdiDownload} size="1.25rem" />
        </div>
      </div>
    );
  },
});
