// packages/solid/src/components/ag-ui-client/components/elm-ag-ui-agent.tsx
import {
  createEffect,
  createSignal,
  For,
  Show,
  splitProps,
  type JSX,
} from "solid-js";
import { clsx } from "clsx";
import {
  mdiAlert,
  mdiClockOutline,
  mdiClose,
  mdiForumOutline,
  mdiRefresh,
} from "@mdi/js";
import type { InputContent } from "@ag-ui/client";

import type { AgentState } from "../hooks/use-agent";
import { ElmMdiIcon } from "../../icon/elm-mdi-icon";
import { ElmInlineText } from "../../typography/elm-inline-text";
import { mergeStyle } from "../../../styles/merge-style";
import { ElmAgUiInput } from "./elm-ag-ui-input";
import { ElmAgUiMessageRenderer } from "./elm-ag-ui-message-renderer";
import type { ElmAgUiPromptDescriptor } from "./elm-ag-ui-prompt-picker";
import styles from "./elm-ag-ui-agent.module.css";

export interface ElmAgUiAgentProps extends JSX.HTMLAttributes<HTMLDivElement> {
  state: AgentState;
  send: (content: InputContent[]) => Promise<void> | void;
  retry: () => Promise<void> | void;
  abort: () => void;
  dequeue: (id: string) => void;
  width?: JSX.CSSProperties["width"];
  enableAutoScroll?: boolean;
  enableToolCalls?: boolean;
  enableReasoning?: boolean;
  prompts?: ElmAgUiPromptDescriptor[];
  resolvePrompt?: (
    key: string,
    args: Record<string, string>,
  ) => Promise<InputContent[] | null>;
}

const queuePreview = (content: InputContent[]): string => {
  const textBlock = content.find(
    (block): block is { type: "text"; text: string } => block.type === "text",
  );
  return textBlock?.text ?? "Attachment";
};

export const ElmAgUiAgent = (props: ElmAgUiAgentProps) => {
  const [local, rest] = splitProps(props, [
    "class",
    "style",
    "children",
    "state",
    "send",
    "retry",
    "abort",
    "dequeue",
    "width",
    "enableAutoScroll",
    "enableToolCalls",
    "enableReasoning",
    "prompts",
    "resolvePrompt",
  ]);
  const [input, setInput] = createSignal("");
  let containerRef!: HTMLDivElement;
  let lastScrollTime = 0;

  createEffect(() => {
    if (local.state.messages.length === 0 || !local.enableAutoScroll) return;
    const now = Date.now();
    if (now - lastScrollTime < 500) return;
    lastScrollTime = now;
    containerRef?.scrollTo({
      behavior: "smooth",
      top: containerRef.scrollHeight,
    });
  });

  const submit = () => {
    if (!input().trim()) return;
    void local.send([{ type: "text", text: input() }]);
    setInput("");
  };

  return (
    <div
      {...rest}
      ref={(element) => {
        containerRef = element;
      }}
      class={clsx(styles["elm-ag-ui-agent"], local.class)}
      style={mergeStyle(local.style, {
        "--elmethis-scoped-agent-ui-width":
          local.width ?? "clamp(300px, 100%, 600px)",
      } as JSX.CSSProperties)}
    >
      <div class={styles["agent-container"]}>
        <div class={styles.messages}>
          <ElmAgUiMessageRenderer
            isRunning={local.state.isRunning}
            messages={local.state.messages}
            handleRetry={() => void local.retry()}
            enableToolCalls={local.enableToolCalls ?? true}
            enableReasoning={local.enableReasoning ?? true}
          />
          <Show when={local.state.error} keyed>
            {(error) => (
              <>
                <div class={styles.error}>
                  <ElmMdiIcon
                    d={mdiAlert}
                    color="var(--elmethis-color-accent-error)"
                    style={{ "flex-shrink": 0 }}
                  />
                  <ElmInlineText color="var(--elmethis-color-accent-error)">
                    {error}
                  </ElmInlineText>
                </div>
                <button
                  type="button"
                  class={styles["clickable-icon"]}
                  onClick={() => void local.retry()}
                  aria-label="Retry"
                >
                  <ElmMdiIcon d={mdiRefresh} size="1.25rem" />
                </button>
              </>
            )}
          </Show>
        </div>
      </div>

      <div class={styles["agent-input-container"]}>
        <div class={styles["agent-input"]}>
          <Show when={local.state.queue.length > 0}>
            <div class={styles["queue-container"]}>
              <For each={local.state.queue}>
                {(queued) => (
                  <div class={styles["queue-item"]}>
                    <ElmMdiIcon
                      class={styles["queue-item-icon"]}
                      d={mdiClockOutline}
                      size="1rem"
                    />
                    <span class={styles["queue-item-text"]}>
                      <ElmInlineText>
                        {queuePreview(queued.content)}
                      </ElmInlineText>
                    </span>
                    <button
                      type="button"
                      class={styles["queue-item-remove"]}
                      onClick={() => local.dequeue(queued.id)}
                      aria-label="Remove from queue"
                    >
                      <ElmMdiIcon d={mdiClose} size="0.875rem" />
                    </button>
                  </div>
                )}
              </For>
            </div>
          </Show>

          <Show when={!local.state.isRunning}>
            <div class={styles["prompt-template-container"]}>
              <For each={local.state.promptTemplates}>
                {(template) => (
                  <button
                    type="button"
                    class={styles["prompt-template-tip"]}
                    onClick={() =>
                      void local.send(
                        template.content.map(
                          (item) => ({ ...item }) as InputContent,
                        ),
                      )
                    }
                  >
                    <ElmMdiIcon
                      class={styles["prompt-template-tip-icon"]}
                      d={mdiForumOutline}
                    />
                    <ElmInlineText>{template.description}</ElmInlineText>
                  </button>
                )}
              </For>
            </div>
          </Show>

          <ElmAgUiInput
            onInputChange={(_event, element) => setInput(element.value)}
            onSubmit={submit}
            onAbort={local.abort}
            isRunning={local.state.isRunning}
            status={local.state.status}
            activity={local.state.activity}
            prompts={local.prompts}
            resolvePrompt={local.resolvePrompt}
          />
        </div>
      </div>
    </div>
  );
};

// packages/qwik/src/components/ag-ui-client/elm-ag-ui-agent.tsx
import {
  $,
  component$,
  QRL,
  useSignal,
  useVisibleTask$,
  type ClassList,
  type CSSProperties,
} from "@qwik.dev/core";
import {
  mdiAlert,
  mdiClockOutline,
  mdiForumOutline,
  mdiRefresh,
} from "@mdi/js";
import type { InputContent } from "@ag-ui/client";

import styles from "./elm-ag-ui-agent.module.css";

import { ElmAgUiMessageRenderer } from "./elm-ag-ui-message-renderer";
import { ElmAgUiStatus } from "./elm-ag-ui-status";
import { ElmAgUiInput } from "./elm-ag-ui-input";
import type { ElmAgUiPromptDescriptor } from "./elm-ag-ui-prompt-picker";
import { ElmInlineText } from "../typography/elm-inline-text";
import { ElmMdiIcon } from "../icon/elm-mdi-icon";
import type { AgentState } from "./use-agent";

export interface ElmAgUiAgentProps {
  state: AgentState;
  send$: QRL<(content: InputContent[]) => Promise<void> | void>;
  retry$: QRL<() => Promise<void> | void>;
  abort$: QRL<() => void>;
  /**
   * @default "clamp(300px, 100%, 600px)"
   */
  width?: CSSProperties["width"];
  enableAutoScroll?: boolean;
  class?: ClassList;
  style?: CSSProperties;
  /**
   * Prompts exposed via a "+" button at the left of the input. Pair
   * with `resolvePrompt$` to integrate MCP prompts or any other
   * prompt source.
   */
  prompts?: ElmAgUiPromptDescriptor[];
  /**
   * Resolve a picked prompt with the user-supplied argument values
   * into `InputContent[]`. The text blocks are inserted into the
   * textarea at the current cursor position so the user can edit
   * before submitting. Return `null` (or content with no text blocks)
   * to leave the textarea untouched.
   */
  resolvePrompt$?: QRL<
    (
      key: string,
      args: Record<string, string>,
    ) => Promise<InputContent[] | null>
  >;
}

/** One-line label for a queued message — its first text block, else a
 *  generic stand-in for attachment-only content. */
const queuePreview = (content: InputContent[]): string => {
  const textBlock = content.find(
    (block): block is { type: "text"; text: string } => block.type === "text",
  );
  return textBlock?.text ?? "Attachment";
};

export const ElmAgUiAgent = component$<ElmAgUiAgentProps>((props) => {
  const {
    state,
    send$,
    retry$,
    abort$,
    width = "clamp(300px, 100%, 600px)",
    class: className,
    style,
    prompts,
    resolvePrompt$,
  } = props;

  const input = useSignal("");
  const containerRef = useSignal<HTMLElement>();
  const lastScrollTime = useSignal(0);

  // eslint-disable-next-line qwik/no-use-visible-task
  useVisibleTask$(
    ({ track }) => {
      track(() => state.messages.length);
      // Read via `props.*` (not a destructured local) so Qwik can trace the
      // closure capture back to a reactive, serializable source.
      if (props.enableAutoScroll) {
        const now = Date.now();
        if (now - lastScrollTime.value < 500) return;
        lastScrollTime.value = now;
        containerRef.value?.scrollTo({
          behavior: "smooth",
          top: containerRef.value.scrollHeight,
        });
      }
    },
    { strategy: "document-ready" },
  );

  const onTemplateClick$ = $((_event: Event, element: Element) => {
    const idx = Number(element.getAttribute("data-template-index"));
    if (Number.isNaN(idx)) return;
    // Spread each item to create plain objects — HttpAgent calls
    // structuredClone() on messages before sending, which throws a
    // DataCloneError on Qwik reactive store proxies.
    send$(
      state.promptTemplates[idx].content.map(
        (item) => ({ ...item }) as InputContent,
      ),
    );
  });

  const onInput$ = $((_event: InputEvent, element: HTMLTextAreaElement) => {
    input.value = element.value;
  });

  const onSubmit$ = $((_event: Event, element: Element) => {
    if (input.value.trim() === "") return;
    send$([{ type: "text", text: input.value }]);
    input.value = "";
    const textarea = element.querySelector("textarea");
    if (textarea) textarea.value = "";
  });

  return (
    <div
      ref={containerRef}
      class={[styles["elm-ag-ui-agent"], className]}
      style={{
        "--agent-ui-width": width,
        ...style,
      }}
    >
      <div
        class={styles["agent-container"]}
        style={{ "--elmethis-margin-block-start": "0" }}
      >
        <div class={styles["messages"]}>
          <ElmAgUiMessageRenderer
            isRunning={state.isRunning}
            messages={state.messages}
            handleRetry$={retry$}
          />

          {state.error && (
            <>
              <div class={styles["error"]}>
                <ElmMdiIcon
                  d={mdiAlert}
                  color="var(--elmethis-color-accent-error)"
                  style={{ flexShrink: 0 }}
                />
                <ElmInlineText color="var(--elmethis-color-accent-error)">
                  {state.error}
                </ElmInlineText>
              </div>

              <span class={styles["clickable-icon"]} onClick$={retry$}>
                <ElmMdiIcon d={mdiRefresh} size="1.25rem" />
              </span>
            </>
          )}
        </div>
      </div>

      <div class={styles["agent-input-container"]}>
        <div class={styles["agent-input"]}>
          {(state.status === "running" ||
            state.status === "awaiting_input") && (
            <ElmAgUiStatus
              class={styles["status"]}
              status={state.status}
              activity={state.activity}
            />
          )}

          {state.queue.length > 0 && (
            <div class={styles["queue-container"]}>
              {state.queue.map((queued) => (
                <div key={queued.id} class={styles["queue-item"]}>
                  <ElmMdiIcon
                    class={styles["queue-item-icon"]}
                    d={mdiClockOutline}
                    size="1rem"
                  />
                  <span class={styles["queue-item-text"]}>
                    <ElmInlineText>
                      {queuePreview(queued.content)}
                    </ElmInlineText>
                  </span>
                </div>
              ))}
            </div>
          )}

          {!state.isRunning && (
            <div class={styles["prompt-template-container"]}>
              {state.promptTemplates.map((template, index) => (
                <span
                  key={index}
                  data-template-index={index}
                  class={styles["prompt-template-tip"]}
                  onClick$={onTemplateClick$}
                >
                  <ElmMdiIcon
                    class={styles["prompt-template-tip-icon"]}
                    d={mdiForumOutline}
                  />
                  <ElmInlineText>{template.description}</ElmInlineText>
                </span>
              ))}
            </div>
          )}

          <ElmAgUiInput
            onInput$={onInput$}
            onSubmit$={onSubmit$}
            onAbort$={abort$}
            isRunning={state.isRunning}
            prompts={prompts}
            resolvePrompt$={resolvePrompt$}
          />
        </div>
      </div>
    </div>
  );
});
