// packages/solid/src/components/ag-ui-client/hooks/use-agent.ts
/* eslint-disable solid/reactivity -- AG-UI requires identity-preserving mutable state. */
import { onCleanup, onMount, type Accessor } from "solid-js";
import { createMutable } from "solid-js/store";
import {
  type AbstractAgent,
  HttpAgent,
  type InputContent,
  type Message,
  type UserMessage,
} from "@ag-ui/client";
import type { Interrupt } from "@ag-ui/core";
import { v7 } from "uuid";

import {
  createAgentSubscriber,
  type AgentActivity,
  type AgentRunStatus,
} from "../internal/create-agent-subscriber";
import { normalizePromptTemplates } from "../internal/normalize-prompt-templates";
import {
  getToolDefinitions,
  type AnyToolDef,
  type ToolRegistry,
} from "../internal/tool-registry";

export interface AgentContext {
  value: string;
  description: string;
}

export interface UseAgentOptions {
  url: string;
  tools?: ToolRegistry | Accessor<ToolRegistry | undefined>;
  context?: AgentContext[];
  headers?: Record<string, string>;
  initialMessages?: Message[];
  agentFactory?: (options: {
    url: string;
    headers?: Record<string, string>;
  }) => AbstractAgent;
}

export interface QueuedMessage {
  id: string;
  content: InputContent[];
}

export interface AgentState {
  error: string | null;
  messages: Message[];
  context?: AgentContext[];
  isRunning: boolean;
  status: AgentRunStatus;
  activity: AgentActivity;
  pendingInterrupts: Interrupt[];
  promptTemplates: Array<{
    description: string;
    content: InputContent[];
  }>;
  queue: QueuedMessage[];
}

export interface UseAgentReturn {
  state: AgentState;
  send: (content: InputContent[]) => Promise<void>;
  retry: () => Promise<void>;
  abort: () => void;
  dequeue: (id: string) => void;
  addTool: (name: string, tool: AnyToolDef) => void;
  setContext: (context: AgentContext[]) => void;
  setPromptTemplates: (
    templates: Array<{
      description: string;
      content: string | InputContent[];
    }>,
  ) => void;
}

export function useAgent(options: UseAgentOptions): UseAgentReturn {
  const dynamicTools =
    typeof options.tools === "function" ? options.tools : undefined;
  let staticTools: ToolRegistry | undefined =
    typeof options.tools === "function" ? undefined : options.tools;
  let agent: AbstractAgent | undefined;
  const state = createMutable<AgentState>({
    error: null,
    messages: [...(options.initialMessages ?? [])],
    context: options.context,
    isRunning: false,
    status: "idle",
    activity: "idle",
    pendingInterrupts: [],
    promptTemplates: [],
    queue: [],
  });
  const getTools = () => dynamicTools?.() ?? staticTools ?? {};

  const executeRun = async (withContext: boolean) => {
    if (!agent) return;
    state.error = null;
    try {
      await agent.runAgent({
        tools: getToolDefinitions(getTools()),
        ...(withContext && {
          context: state.context?.map(({ value, description }) => ({
            value,
            description,
          })),
        }),
      });
    } catch {
      state.isRunning = false;
      if (state.status === "running") state.status = "error";
    }
  };

  onMount(() => {
    const factory = options.agentFactory ?? ((value) => new HttpAgent(value));
    agent = factory({ url: options.url, headers: options.headers });
    agent.messages = [...(options.initialMessages ?? [])];
    const subscription = agent.subscribe(
      createAgentSubscriber({
        state,
        getTools,
        onNeedsReRun: async (pending) => {
          if (!agent) return;
          agent.messages.push(...pending);
          await executeRun(false);
        },
        onIdle: async () => {
          if (!agent || state.status !== "success") return;
          const next = state.queue.shift();
          if (!next) return;
          const userMessage: UserMessage = {
            id: next.id,
            role: "user",
            content: next.content.map((item) => ({ ...item }) as InputContent),
          };
          agent.messages.push(userMessage);
          state.messages.push(userMessage);
          await executeRun(true);
        },
      }),
    );
    onCleanup(() => {
      subscription.unsubscribe();
      agent = undefined;
    });
  });

  const send = async (content: InputContent[]) => {
    if (!agent) return;
    if (state.isRunning) {
      state.queue.push({ id: v7(), content });
      return;
    }
    const userMessage: UserMessage = { id: v7(), role: "user", content };
    agent.messages.push(userMessage);
    state.messages.push(userMessage);
    await executeRun(true);
  };

  const retry = async () => {
    if (!agent) return;
    const lastUserMessageIndex = state.messages.findLastIndex(
      (message) => message.role === "user",
    );
    if (lastUserMessageIndex === -1) return;
    const messages = agent.messages.slice(0, lastUserMessageIndex + 1);
    agent.messages = [...messages];
    state.messages = [...messages];
    await executeRun(true);
  };

  return {
    state,
    send,
    retry,
    abort: () => {
      if (!agent) return;
      if (state.queue.length > 0) {
        state.queue.pop();
        return;
      }
      agent.abortRun();
      state.status = "aborted";
      state.isRunning = false;
      state.activity = "idle";
    },
    dequeue: (id) => {
      const index = state.queue.findIndex((queued) => queued.id === id);
      if (index !== -1) state.queue.splice(index, 1);
    },
    addTool: (name, tool) => {
      if (!dynamicTools) staticTools = { ...(staticTools ?? {}), [name]: tool };
    },
    setContext: (context) => {
      state.context = context;
    },
    setPromptTemplates: (templates) => {
      state.promptTemplates = normalizePromptTemplates(templates);
    },
  };
}

// packages/qwik/src/components/ag-ui-client/useAgent.tsx
import {
  $,
  component$,
  NoSerialize,
  noSerialize,
  useSignal,
  useStore,
  useVisibleTask$,
  type CSSProperties,
} from "@builder.io/qwik";

import styles from "./useAgent.module.css";

import { BaseEvent, HttpAgent, Message, UserMessage } from "@ag-ui/client";
import { compactEventsExtended } from "./compactEventsExtended";

import { z } from "zod";
import { zodToJsonSchema } from "zod-to-json-schema";
import { ElmAgUiMessageRenderer } from "./elm-ag-ui-message-renderer";
import { ElmAgUiInput } from "./elm-ag-ui-input";
import { ElmInlineText } from "../typography/elm-inline-text";
import { ElmMdiIcon } from "../icon/elm-mdi-icon";
import { mdiForumOutline } from "@mdi/js";

import { v7 } from "uuid";

// ---------------------------------------------------------------------------
// Tool registry
// ---------------------------------------------------------------------------

export interface ToolDef<T extends z.ZodObject<z.ZodRawShape>> {
  description: string;
  schema: T;
  execute: (args: z.infer<T>) => unknown;
}

export type AnyToolDef = ToolDef<z.ZodObject<z.ZodRawShape>>;
export type ToolRegistry = Record<string, AnyToolDef>;

export function getToolDefinitions(registry: ToolRegistry) {
  return Object.entries(registry).map(([name, { description, schema }]) => ({
    name,
    description,
    parameters: zodToJsonSchema(schema) as {
      type: "object";
      properties: Record<string, unknown>;
      required: string[];
    },
  }));
}

// ---------------------------------------------------------------------------
// Hook
// ---------------------------------------------------------------------------

export interface UseAgentOptions {
  url: string;
  tools?: ToolRegistry;
  context?: {
    value: string;
    description: string;
  }[];
  headers?: Record<string, string> | undefined;
  initialMessages?: Message[];
}

export function useAgent({
  url,
  tools,
  context,
  headers,
  initialMessages,
}: UseAgentOptions) {
  const httpAgent = useSignal<NoSerialize<HttpAgent> | null>(null);
  const toolsRef = useSignal<NoSerialize<ToolRegistry>>(noSerialize(tools));

  const agentStateStore = useStore<{
    messages: Message[];
    events: BaseEvent[];
    context?: {
      value: string;
      description: string;
    }[];
    isRunning: boolean;
    promptTemplates: { description: string; value: string }[];
  }>({
    messages: initialMessages ?? [],
    events: [],
    context,
    isRunning: false,
    promptTemplates: [],
  });

  const executeRun = $(async (withContext: boolean) => {
    if (!httpAgent.value) return;
    try {
      await httpAgent.value.runAgent({
        tools: getToolDefinitions(toolsRef.value ?? {}),
        ...(withContext && {
          context: agentStateStore.context?.map(({ value, description }) => ({
            value,
            description,
          })),
        }),
      });
    } catch {
      agentStateStore.isRunning = false;
    }
  });

  // eslint-disable-next-line qwik/no-use-visible-task
  useVisibleTask$(({ cleanup, track }) => {
    const trackedUrl = track(() => url);
    const trackedHeaders = track(() => (headers ? { ...headers } : undefined));

    httpAgent.value = noSerialize(
      new HttpAgent({ url: trackedUrl, headers: trackedHeaders }),
    );
    cleanup(() => {
      httpAgent.value = null;
    });

    const agent = httpAgent.value;
    if (!agent) return;

    let pendingToolMessages: Message[] = [];

    const subscription = agent.subscribe({
      onRunInitialized() {
        agentStateStore.isRunning = true;
      },
      onEvent({ messages: newMessages, event }) {
        if (agentStateStore.messages.length < newMessages.length) {
          agentStateStore.messages.push(
            ...newMessages.slice(agentStateStore.messages.length),
          );
        }
        agentStateStore.events = compactEventsExtended([
          ...agentStateStore.events,
          event,
        ]);
      },

      onTextMessageContentEvent({ event }) {
        const msg = agentStateStore.messages.findLast(
          (m) => m.role === "assistant",
        );
        if (msg) msg.content = (msg.content ?? "") + event.delta;
      },

      onReasoningMessageContentEvent({ event }) {
        const msg = agentStateStore.messages.findLast(
          (m) => m.role === "reasoning",
        );
        if (msg) msg.content = (msg.content ?? "") + event.delta;
      },

      onActivityDeltaEvent({ activityMessage }) {
        const msg = agentStateStore.messages.findLast(
          (m) => m.role === "activity",
        );
        if (msg && activityMessage) msg.content = activityMessage.content;
      },

      onToolCallArgsEvent({ event }) {
        const msg = agentStateStore.messages.findLast(
          (m) => m.role === "assistant",
        );
        const toolCall = msg?.toolCalls?.find(
          (tc) => tc.id === event.toolCallId,
        );
        if (toolCall) toolCall.function.arguments += event.delta;
      },
      async onToolCallEndEvent({ event, toolCallName }) {
        const registry: ToolRegistry = toolsRef.value ?? {};
        const tool = registry[toolCallName];
        if (!tool) return;
        const msg = agentStateStore.messages.findLast(
          (m) => m.role === "assistant",
        );
        const toolCall = msg?.toolCalls?.find(
          (tc) => tc.id === event.toolCallId,
        );
        const args = toolCall?.function.arguments
          ? JSON.parse(toolCall.function.arguments)
          : {};
        pendingToolMessages.push({
          id: v7(),
          role: "tool",
          content: JSON.stringify(await tool.execute(args)),
          toolCallId: event.toolCallId,
        } as Message);
      },
      async onRunFinalized() {
        if (import.meta.env.DEV)
          console.log({
            messages: agentStateStore.messages,
            events: agentStateStore.events,
          });

        if (pendingToolMessages.length === 0 || !httpAgent.value) {
          agentStateStore.isRunning = false;
          return;
        }
        httpAgent.value.messages.push(...pendingToolMessages);
        pendingToolMessages = [];
        await executeRun(false);
      },
    });

    cleanup(() => {
      subscription.unsubscribe();
    });
  });

  const send = $(async (content: string) => {
    if (!httpAgent.value) return;
    const userMessage: UserMessage = {
      id: v7(),
      role: "user",
      content,
    };
    httpAgent.value.messages.push(userMessage);
    agentStateStore.messages.push(userMessage);
    await executeRun(true);
  });

  const retry = $(async () => {
    if (!httpAgent.value) return;

    const lastUserMessageIndex = agentStateStore.messages.findLastIndex(
      (m) => m.role === "user",
    );
    if (lastUserMessageIndex === -1) return;

    // Remove all messages after the last user message
    const newMessages = httpAgent.value.messages.slice(
      0,
      lastUserMessageIndex + 1,
    );
    httpAgent.value.messages = [...newMessages];
    agentStateStore.messages = [...newMessages];
    await executeRun(true);
  });

  const addTool = $((name: string, tool: AnyToolDef) => {
    toolsRef.value = noSerialize({ ...(toolsRef.value ?? {}), [name]: tool });
  });

  const abort = $(() => {
    httpAgent.value?.abortRun();
  });

  const AgentUI = component$<{ class?: string; style?: CSSProperties }>(
    ({ class: className, style }) => {
      const input = useSignal("");

      const onInput$ = $((_event: InputEvent, element: HTMLTextAreaElement) => {
        input.value = element.value;
      });

      const onSubmit$ = $((_event: Event, element: Element) => {
        if (input.value.trim() === "") return;
        send(input.value);
        input.value = "";
        const textarea = element.querySelector("textarea");
        if (textarea) textarea.value = "";
      });

      return (
        <div class={[styles["use-agent"], className]} style={style}>
          <div class={styles["messages"]}>
            <ElmAgUiMessageRenderer
              isRunning={agentStateStore.isRunning}
              messages={agentStateStore.messages}
              handleRetry$={retry}
            />
          </div>

          <div class={styles["agent-input"]}>
            {!agentStateStore.isRunning && (
              <div class={styles["prompt-template-container"]}>
                {agentStateStore.promptTemplates.map((template, index) => (
                  <span
                    key={index}
                    class={styles["prompt-template-tip"]}
                    onClick$={() => send(template.value)}
                  >
                    <ElmMdiIcon d={mdiForumOutline} color="#cdb57b" />
                    <ElmInlineText>{template.description}</ElmInlineText>
                  </span>
                ))}
              </div>
            )}

            <ElmAgUiInput
              onInput$={onInput$}
              onSubmit$={onSubmit$}
              onAbort$={abort}
              isRunning={agentStateStore.isRunning}
            />
          </div>
        </div>
      );
    },
  );

  const setContext = $(
    (newContext: { value: string; description: string }[]) => {
      agentStateStore.context = newContext;
    },
  );

  const setPromptTemplates = $(
    (templates: { description: string; value: string }[]) => {
      agentStateStore.promptTemplates = templates;
    },
  );

  return {
    messages: agentStateStore.messages,
    events: agentStateStore.events,
    context: agentStateStore.context,
    setContext,
    promptTemplates: agentStateStore.promptTemplates,
    setPromptTemplates,
    send,
    addTool,
    abort,
    AgentUI,
  };
}
