// packages/react/src/components/form/elm-validation.tsx
import type { ComponentPropsWithoutRef, CSSProperties } from "react";
import { clsx } from "clsx";
import { mdiCheckCircle, mdiCheckCircleOutline } from "@mdi/js";

import { ElmMdiIcon } from "../icon/elm-mdi-icon";
import { ElmInlineText } from "../typography/elm-inline-text";

import styles from "./elm-validation.module.css";

export interface ElmValidationProps extends ComponentPropsWithoutRef<"div"> {
  text: string;
  validColor?: string;
  isValid: boolean;
}

export const ElmValidation = ({
  className,
  style,
  text,
  validColor = "var(--elmethis-color-accent-success)",
  isValid,
  ...props
}: ElmValidationProps) => {
  return (
    <div
      className={clsx(styles["elm-validation"], className)}
      style={
        {
          "--elmethis-scoped-opacity": isValid ? 1 : 0.5,
          ...style,
        } as CSSProperties
      }
      {...props}
    >
      <ElmMdiIcon
        path={isValid ? mdiCheckCircle : mdiCheckCircleOutline}
        color={isValid ? validColor : undefined}
      />
      <ElmInlineText color={isValid ? validColor : undefined}>
        {text}
      </ElmInlineText>
    </div>
  );
};

// packages/vue/src/components/form/elm-validation.tsx
import { defineComponent, type CSSProperties, type HTMLAttributes } from "vue";
import { clsx } from "clsx";
import { mdiCheckCircle, mdiCheckCircleOutline } from "@mdi/js";

import { ElmMdiIcon } from "../icon/elm-mdi-icon";
import { ElmInlineText } from "../typography/elm-inline-text";

import styles from "./elm-validation.module.css";

export interface ElmValidationProps extends HTMLAttributes {
  text: string;
  validColor?: string;
  isValid: boolean;
}

export const ElmValidation = defineComponent({
  name: "ElmValidation",
  props: {
    text: { type: String, required: true },
    validColor: {
      type: String,
      default: "var(--elmethis-color-accent-success)",
    },
    isValid: { type: Boolean, required: true },
  },
  setup(props) {
    // inheritAttrs default: passthrough class/style merge onto the root.
    return () => (
      <div
        class={clsx(styles["elm-validation"])}
        style={
          {
            "--elmethis-scoped-opacity": props.isValid ? 1 : 0.5,
          } as CSSProperties
        }
      >
        <ElmMdiIcon
          path={props.isValid ? mdiCheckCircle : mdiCheckCircleOutline}
          color={props.isValid ? props.validColor : undefined}
        />
        <ElmInlineText color={props.isValid ? props.validColor : undefined}>
          {props.text}
        </ElmInlineText>
      </div>
    );
  },
});
