// packages/react/src/components/a2ui/catalog/block-catalog.tsx
/**
 * Elmethis "block" catalog — typography, media, code, math, table, tabs, and a
 * fallback. Built on the **official** `@a2ui/react` generic binder: each entry
 * is a `createComponentImplementation(api, ReactFC)` mapping an `@elmethis/core`
 * component API onto the project's `Elm*` components. The official `basicCatalog`
 * (A2UI v0.9 Basic Catalog) is merged underneath so a single catalog serves
 * both the standard primitives and the richer block elements.
 *
 * Differences from the qwik reference (`defineRenderer`):
 *   - The binder pre-resolves bindings, so `props.text` is already a value —
 *     there is no per-renderer `resolve()`.
 *   - Children render through the host's `buildChild(id, basePath)`; the
 *     `renderChildList` / `childEntries` helpers mirror the package's internal
 *     `ChildList`.
 *   - The binder's render signature is `{ props, buildChild, context }` with no
 *     sibling `index`, so the qwik first-child-margin override and the
 *     `TableCell` `columnIndex` row-header promotion are not wired here.
 */
import { Fragment, type CSSProperties } from "react";
import {
  basicCatalog,
  createComponentImplementation,
  type ReactComponentImplementation,
} from "@a2ui/react/v0_9";
import { Catalog } from "@a2ui/web_core/v0_9";
import {
  AudioApi,
  BlockImageApi,
  BlockQuoteApi,
  BookmarkApi,
  CalloutApi,
  CodeBlockApi,
  ColumnApi,
  ColumnListApi,
  ContentTabApi,
  ContentTabsApi,
  DividerApi,
  FileApi,
  HeadingApi,
  HtmlApi,
  IconApi,
  KatexApi,
  LinkTextApi,
  ListApi,
  ListItemApi,
  MermaidApi,
  NotionCalloutApi,
  ParagraphApi,
  RichTextApi,
  TableApi,
  TableCellApi,
  TableRowApi,
  ToggleApi,
  UnsupportedApi,
  VideoApi,
} from "@elmethis/core";

import { ElmKatex } from "../../code/elm-katex";
import { ElmCodeBlock } from "../../code/elm-code-block";
import { ElmHtml } from "../../code/elm-html";
import { ElmInlineIcon } from "../../icon/elm-inline-icon";
import { ElmAudioPlayer } from "../../media/elm-audio-player";
import { ElmBlockImage } from "../../media/elm-block-image";
import { ElmFile } from "../../media/elm-file";
import { ElmBookmark } from "../../navigation/elm-bookmark";
import {
  ElmTab,
  ElmTabList,
  ElmTabPanel,
  ElmTabs,
} from "../../containments/elm-tabs";
import { ElmToggle } from "../../containments/elm-toggle";
import { ElmBlockQuote } from "../../typography/elm-block-quote";
import { ElmCallout } from "../../typography/elm-callout";
import { ElmNotionCallout } from "../../notion/elm-notion-callout";
import { ElmDivider } from "../../typography/elm-divider";
import { ElmHeading } from "../../typography/elm-heading";
import { ElmInlineText } from "../../typography/elm-inline-text";
import { ElmList } from "../../typography/elm-list";
import { ElmParagraph } from "../../typography/elm-paragraph";
import {
  ElmTable,
  ElmTableBody,
  ElmTableCell,
  ElmTableHeader,
  ElmTableRow,
} from "../../table";
import { ElmUnsupportedBlock } from "../../fallback/elm-unsupported-block";

import {
  alignItemsMap,
  childEntries,
  childListIds,
  justifyContentMap,
  renderChildList,
} from "./catalog-utils";

const BLOCK_CATALOG_ID =
  "https://a2ui.org/specification/v0_9/basic_catalog.json";

// Multi-column layout for the ColumnList block.
const columnListStyle: CSSProperties = {
  boxSizing: "content-box",
  paddingBlock: "0.25rem",
  width: "100%",
  display: "flex",
  flexDirection: "row",
  gap: "0.25rem",
  justifyContent: "space-around",
  overflowX: "auto",
};

/**
 * The Elm block component implementations. Each is typed by its
 * `@elmethis/core` API schema; the binder injects resolved `props`.
 */
// The binder's resolved prop types vary per schema and don't all expose the
// exact fields these renderers read; cast access where the inferred type is
// too narrow. Behavior is validated by the component specs.
/* eslint-disable @typescript-eslint/no-explicit-any */
const blockImplementations: ReactComponentImplementation[] = [
  // ----- Inline -----
  createComponentImplementation(RichTextApi, ({ props }: any) => {
    const decoration: string[] = props.decoration ?? [];
    if (decoration.includes("katex"))
      return <ElmKatex expression={props.text} block={false} />;
    return (
      <ElmInlineText
        bold={decoration.includes("bold")}
        italic={decoration.includes("italic")}
        underline={decoration.includes("underline")}
        strikethrough={decoration.includes("strikethrough")}
        code={decoration.includes("code")}
        color={props.color}
        ruby={props.ruby}
      >
        {props.text}
      </ElmInlineText>
    );
  }),

  createComponentImplementation(LinkTextApi, ({ props }: any) => (
    <ElmInlineText href={props.href} favicon={props.favicon}>
      {props.text}
    </ElmInlineText>
  )),

  createComponentImplementation(IconApi, ({ props }: any) => (
    <ElmInlineIcon src={props.src} alt={props.alt} />
  )),

  // ----- Layout (overrides basic Column with widthRatio support) -----
  createComponentImplementation(ColumnApi, ({ props, buildChild }: any) => (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        justifyContent: justifyContentMap[props.justify ?? "start"],
        alignItems: alignItemsMap[props.align ?? "stretch"],
        flex: props.widthRatio != null ? String(props.widthRatio) : undefined,
        boxSizing: "border-box",
        padding: "0.125rem",
        gap: "var(--elmethis-stack-gap)",
      }}
    >
      {renderChildList(props.children, buildChild)}
    </div>
  )),

  createComponentImplementation(ColumnListApi, ({ props, buildChild }: any) => (
    <div style={columnListStyle}>
      {renderChildList(props.children, buildChild)}
    </div>
  )),

  // ----- Block typography -----
  createComponentImplementation(HeadingApi, ({ props, buildChild }: any) => (
    <ElmHeading level={props.level}>
      {renderChildList(props.children, buildChild)}
    </ElmHeading>
  )),

  createComponentImplementation(ParagraphApi, ({ props, buildChild }: any) => (
    <ElmParagraph color={props.color} backgroundColor={props.backgroundColor}>
      {renderChildList(props.children, buildChild)}
    </ElmParagraph>
  )),

  createComponentImplementation(ListApi, ({ props, buildChild }: any) => (
    <ElmList listStyle={props.style ?? "unordered"}>
      {childEntries(props.children).map(({ id, basePath }, i) => (
        <li key={`${id}:${i}`}>{buildChild(id, basePath)}</li>
      ))}
    </ElmList>
  )),

  createComponentImplementation(ListItemApi, ({ props, buildChild }: any) => (
    <>{renderChildList(props.children, buildChild)}</>
  )),

  createComponentImplementation(BlockQuoteApi, ({ props, buildChild }: any) => (
    <ElmBlockQuote cite={props.cite}>
      {renderChildList(props.children, buildChild)}
    </ElmBlockQuote>
  )),

  createComponentImplementation(CalloutApi, ({ props, buildChild }: any) => (
    <ElmCallout type={props.type}>
      {renderChildList(props.children, buildChild)}
    </ElmCallout>
  )),

  createComponentImplementation(
    NotionCalloutApi,
    ({ props, buildChild }: any) => (
      <ElmNotionCallout
        icon={props.icon}
        color={props.color}
        variant={props.variant}
      >
        {renderChildList(props.children, buildChild)}
      </ElmNotionCallout>
    ),
  ),

  createComponentImplementation(DividerApi, () => <ElmDivider />),

  createComponentImplementation(ToggleApi, ({ props, buildChild }: any) => (
    <ElmToggle summary={renderChildList(props.summary, buildChild)}>
      {renderChildList(props.children, buildChild)}
    </ElmToggle>
  )),

  // ----- Media / embed -----
  createComponentImplementation(BookmarkApi, ({ props }: any) => (
    <ElmBookmark
      url={props.url}
      title={props.title}
      description={props.description}
      image={props.image}
    />
  )),

  createComponentImplementation(FileApi, ({ props }: any) => (
    <ElmFile src={props.src} name={props.name} />
  )),

  createComponentImplementation(AudioApi, ({ props }: any) => (
    <ElmAudioPlayer
      src={props.src}
      title={props.title}
      artist={props.artist}
      seekStep={props.seekStep}
      loop={props.loop}
      autoPlay={props.autoPlay}
    />
  )),

  createComponentImplementation(VideoApi, ({ props }: any) => (
    <figure style={{ margin: 0 }}>
      <video
        src={props.src}
        poster={props.poster}
        title={props.title}
        width={props.width}
        height={props.height}
        loop={props.loop}
        autoPlay={props.autoPlay}
        muted={props.muted}
        controls
        style={{ maxWidth: "100%", height: "auto" }}
      />
      {props.caption ? <figcaption>{props.caption}</figcaption> : null}
    </figure>
  )),

  createComponentImplementation(BlockImageApi, ({ props }: any) => (
    <ElmBlockImage
      src={props.src}
      alt={props.alt}
      width={props.width}
      height={props.height}
      srcSet={props.srcset}
      sizes={props.sizes}
      caption={props.caption}
      enableModal={true}
    />
  )),

  createComponentImplementation(HtmlApi, ({ props }: any) => (
    <ElmHtml
      html={props.html}
      src={props.src}
      autoHeight={props.autoHeight}
      allowScripts={props.allowScripts}
    />
  )),

  // ----- Code / math / diagram -----
  createComponentImplementation(CodeBlockApi, ({ props }: any) => (
    <ElmCodeBlock
      code={props.code}
      language={props.language}
      caption={props.caption}
    />
  )),

  createComponentImplementation(KatexApi, ({ props }: any) => (
    <ElmKatex expression={props.expression} block={true} />
  )),

  // Mermaid renders as a syntax-highlighted code block — no dedicated Mermaid
  // renderer in this package. The source is preserved for host post-processing.
  createComponentImplementation(MermaidApi, ({ props }: any) => (
    <ElmCodeBlock code={props.code} language="mermaid" />
  )),

  // ----- Tabs (ContentTab is data-only; ContentTabs walks the surface) -----
  createComponentImplementation(ContentTabApi, () => null),

  createComponentImplementation(
    ContentTabsApi,
    ({ props, buildChild, context }: any) => {
      const tabIds = childListIds(props.children);
      const tabs = tabIds.map((tabId) => {
        const tabModel = context.surfaceComponents.get(tabId);
        return {
          tabId,
          labelIds: childListIds(tabModel?.properties.label),
          contentIds: childListIds(tabModel?.properties.content),
        };
      });
      return (
        <ElmTabs defaultValue="0">
          <ElmTabList>
            {tabs.map(({ tabId, labelIds }, idx) => (
              <ElmTab key={tabId} value={String(idx)}>
                {labelIds.map((lid, i) => (
                  <Fragment key={`${lid}:${i}`}>
                    {buildChild(lid, "/")}
                  </Fragment>
                ))}
              </ElmTab>
            ))}
          </ElmTabList>
          {tabs.map(({ tabId, contentIds }, idx) => (
            <ElmTabPanel key={tabId} value={String(idx)}>
              {contentIds.map((cid, i) => (
                <Fragment key={`${cid}:${i}`}>{buildChild(cid, "/")}</Fragment>
              ))}
            </ElmTabPanel>
          ))}
        </ElmTabs>
      );
    },
  ),

  // ----- Table -----
  createComponentImplementation(TableApi, ({ props, buildChild }: any) => (
    <ElmTable
      caption={props.caption ? String(props.caption) : undefined}
      hasRowHeader={props.hasRowHeader}
    >
      {props.header && props.header.length > 0 && (
        <ElmTableHeader>
          {renderChildList(props.header, buildChild)}
        </ElmTableHeader>
      )}
      <ElmTableBody>{renderChildList(props.body, buildChild)}</ElmTableBody>
    </ElmTable>
  )),

  createComponentImplementation(TableRowApi, ({ props, buildChild }: any) => (
    <ElmTableRow>{renderChildList(props.children, buildChild)}</ElmTableRow>
  )),

  createComponentImplementation(TableCellApi, ({ props, buildChild }: any) => (
    <ElmTableCell isHeader={props.isHeader}>
      {renderChildList(props.children, buildChild)}
    </ElmTableCell>
  )),

  // ----- Fallback -----
  createComponentImplementation(UnsupportedApi, ({ props }: any) => (
    <ElmUnsupportedBlock
      details={
        props.details
          ? `Unsupported component type: ${String(props.details)}`
          : "Unsupported component type"
      }
    />
  )),
];
/* eslint-enable @typescript-eslint/no-explicit-any */

/**
 * The merged component list: the official A2UI basic catalog underneath, with
 * the Elm block implementations layered on top (later entries win by name, so
 * `Column` / `List` / `Divider` / `Icon` resolve to the Elm versions). This is
 * the unit `ElmA2ui` registers under each referenced catalog id.
 */
export const blockComponents: ReactComponentImplementation[] = [
  ...basicCatalog.components.values(),
  ...blockImplementations,
];

/** Shared catalog functions (from the official basic catalog). */
export const blockFunctions = Array.from(basicCatalog.functions.values());

/**
 * A ready-to-use `Catalog` of {@link blockComponents}, registered under the
 * basic-catalog id. `ElmA2ui` rebuilds equivalent catalogs per referenced id;
 * this export is for direct/standalone use.
 */
export const blockCatalog: Catalog<ReactComponentImplementation> = new Catalog(
  BLOCK_CATALOG_ID,
  blockComponents,
  blockFunctions,
);

// packages/qwik/src/components/a2ui/catalog/block-catalog.tsx
/**
 * "Block" catalog — typography, media, code, math, table, tabs, and a callout
 * fallback. Composes on top of the basic catalog: most layout primitives
 * (Row, Image, etc.) come from `basicCatalog`; this catalog adds richer block
 * elements that wrap project-specific Elm* components.
 */
import { Fragment, type CSSProperties } from "@qwik.dev/core";

import { ElmKatex } from "../../code/elm-katex";
import { ElmCodeBlock } from "../../code/elm-code-block";
import { ElmHtml } from "../../code/elm-html";
import { ElmInlineIcon } from "../../icon/elm-inline-icon";
import { ElmAudioPlayer } from "../../media/elm-audio-player";
import { ElmBlockImage } from "../../media/elm-block-image";
import { ElmFile } from "../../media/elm-file";
import { ElmBookmark } from "../../navigation/elm-bookmark";
import {
  ElmTab,
  ElmTabList,
  ElmTabPanel,
  ElmTabs,
} from "../../containments/elm-tabs";
import { ElmToggle } from "../../containments/elm-toggle";
import { ElmBlockQuote } from "../../typography/elm-block-quote";
import { ElmCallout } from "../../typography/elm-callout";
import { ElmNotionCallout } from "../../notion/elm-notion-callout";
import { ElmDivider } from "../../typography/elm-divider";
import { ElmHeading } from "../../typography/elm-heading";
import { ElmInlineText } from "../../typography/elm-inline-text";
import { ElmList } from "../../typography/elm-list";
import { ElmParagraph } from "../../typography/elm-paragraph";
import {
  ElmTable,
  ElmTableBody,
  ElmTableCell,
  ElmTableHeader,
  ElmTableRow,
} from "../../table";
import { ElmUnsupportedBlock } from "../../fallback/elm-unsupported-block";

import { CatalogRenderer, defineRenderer } from "./catalog";
import { alignItemsMap, justifyContentMap } from "./catalog-utils";
import { basicCatalog } from "./basic-catalog";
import {
  AudioApi,
  BlockImageApi,
  BlockQuoteApi,
  BookmarkApi,
  CalloutApi,
  CodeBlockApi,
  ColumnApi,
  ColumnListApi,
  ContentTabApi,
  ContentTabsApi,
  DividerApi,
  FileApi,
  HeadingApi,
  HtmlApi,
  IconApi,
  KatexApi,
  LinkTextApi,
  ListApi,
  ListItemApi,
  MermaidApi,
  NotionCalloutApi,
  ParagraphApi,
  RichTextApi,
  TableApi,
  TableCellApi,
  TableRowApi,
  ToggleApi,
  UnsupportedApi,
  VideoApi,
} from "@elmethis/core";

/**
 * A `ChildList` is either a static array of component ids or a template
 * `{ componentId, path }`. The Tab renderer only renders the static form
 * today; bound templates resolve to no children until the data layer is
 * wired up. Returns the validated string ids.
 */
function extractChildIds(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  return value.filter((id): id is string => typeof id === "string");
}

// Multi-column layout for the ColumnList block.
const columnListStyle: CSSProperties = {
  boxSizing: "content-box",
  paddingBlock: "0.25rem",
  width: "100%",
  display: "flex",
  flexDirection: "row",
  gap: "0.25rem",
  justifyContent: "space-around",
  overflowX: "auto",
};

/**
 * The block catalog stands on top of the basic catalog. Use it directly
 * (`blockCatalog`) when you want both the basic primitives and the typography
 * block components.
 */
export const blockCatalog: CatalogRenderer = basicCatalog.extend(
  // -------------------------------------------------------------------------
  // Inline components
  // -------------------------------------------------------------------------

  defineRenderer(RichTextApi, ({ props, resolve }) => {
    const text = resolve(props.text);
    const decoration = props.decoration ?? [];
    if (decoration.includes("katex"))
      return <ElmKatex expression={text} block={false} />;
    return (
      <ElmInlineText
        bold={decoration.includes("bold")}
        italic={decoration.includes("italic")}
        underline={decoration.includes("underline")}
        strikethrough={decoration.includes("strikethrough")}
        code={decoration.includes("code")}
        color={props.color}
        ruby={props.ruby}
      >
        {text}
      </ElmInlineText>
    );
  }),

  defineRenderer(LinkTextApi, ({ props, resolve }) => (
    <ElmInlineText href={props.href} favicon={props.favicon}>
      {resolve(props.text)}
    </ElmInlineText>
  )),

  defineRenderer(IconApi, ({ props, resolve }) => (
    <ElmInlineIcon src={resolve(props.src)} alt={props.alt} />
  )),

  // -------------------------------------------------------------------------
  // Layout (overrides Column from basicCatalog with widthRatio support)
  // -------------------------------------------------------------------------

  defineRenderer(ColumnApi, ({ props, childRefs, renderChild }) => (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        justifyContent: justifyContentMap[props.justify ?? "start"],
        alignItems: alignItemsMap[props.align ?? "stretch"],
        flex: props.widthRatio != null ? String(props.widthRatio) : undefined,
        boxSizing: "border-box",
        padding: "0.125rem",
        gap: "var(--elmethis-stack-gap)",
      }}
    >
      {childRefs(props.children).map(({ id, path }, i) => (
        <span key={`${id}:${i}`}>{renderChild(id, path, i)}</span>
      ))}
    </div>
  )),

  defineRenderer(ColumnListApi, ({ props, childRefs, renderChild }) => (
    <div style={columnListStyle}>
      {childRefs(props.children).map(({ id, path }, i) => (
        <Fragment key={`${id}:${i}`}>{renderChild(id, path, i)}</Fragment>
      ))}
    </div>
  )),

  // -------------------------------------------------------------------------
  // Block typography
  // -------------------------------------------------------------------------

  defineRenderer(HeadingApi, ({ props, childRefs, renderChild }) => (
    <ElmHeading level={props.level}>
      {childRefs(props.children).map(({ id, path }, i) => (
        <Fragment key={`${id}:${i}`}>{renderChild(id, path, i)}</Fragment>
      ))}
    </ElmHeading>
  )),

  defineRenderer(ParagraphApi, ({ props, childRefs, renderChild }) => (
    <ElmParagraph color={props.color} backgroundColor={props.backgroundColor}>
      {childRefs(props.children).map(({ id, path }, i) => (
        <span key={`${id}:${i}`}>{renderChild(id, path, i)}</span>
      ))}
    </ElmParagraph>
  )),

  defineRenderer(ListApi, ({ props, childRefs, renderChild }) => (
    <ElmList listStyle={props.style ?? "unordered"}>
      {childRefs(props.children).map(({ id, path }, i) => (
        <li key={`${id}:${i}`}>{renderChild(id, path, i)}</li>
      ))}
    </ElmList>
  )),

  defineRenderer(ListItemApi, ({ props, childRefs, renderChild }) => (
    <>
      {childRefs(props.children).map(({ id, path }, i) => (
        <Fragment key={`${id}:${i}`}>{renderChild(id, path, i)}</Fragment>
      ))}
    </>
  )),

  defineRenderer(BlockQuoteApi, ({ props, childRefs, renderChild }) => (
    <ElmBlockQuote cite={props.cite}>
      {childRefs(props.children).map(({ id, path }, i) => (
        <Fragment key={`${id}:${i}`}>{renderChild(id, path, i)}</Fragment>
      ))}
    </ElmBlockQuote>
  )),

  defineRenderer(CalloutApi, ({ props, childRefs, renderChild }) => (
    <ElmCallout type={props.type}>
      {childRefs(props.children).map(({ id, path }, i) => (
        <Fragment key={`${id}:${i}`}>{renderChild(id, path, i)}</Fragment>
      ))}
    </ElmCallout>
  )),

  defineRenderer(NotionCalloutApi, ({ props, childRefs, renderChild }) => (
    <ElmNotionCallout
      icon={props.icon}
      color={props.color}
      variant={props.variant}
    >
      {childRefs(props.children).map(({ id, path }, i) => (
        <Fragment key={`${id}:${i}`}>{renderChild(id, path, i)}</Fragment>
      ))}
    </ElmNotionCallout>
  )),

  defineRenderer(DividerApi, () => <ElmDivider />),

  defineRenderer(ToggleApi, ({ props, childRefs, renderChild }) => (
    <ElmToggle>
      <div q:slot="summary">
        {childRefs(props.summary).map(({ id, path }, i) => (
          <span key={`${id}:${i}`}>{renderChild(id, path, i)}</span>
        ))}
      </div>
      {childRefs(props.children).map(({ id, path }, i) => (
        <Fragment key={`${id}:${i}`}>{renderChild(id, path, i)}</Fragment>
      ))}
    </ElmToggle>
  )),

  // -------------------------------------------------------------------------
  // Media / embed
  // -------------------------------------------------------------------------

  defineRenderer(BookmarkApi, ({ props, resolve }) => (
    <ElmBookmark
      url={resolve(props.url)}
      title={props.title ? resolve(props.title) : undefined}
      description={props.description ? resolve(props.description) : undefined}
      image={props.image ? resolve(props.image) : undefined}
    />
  )),

  defineRenderer(FileApi, ({ props, resolve }) => (
    <ElmFile
      src={resolve(props.src)}
      name={props.name ? resolve(props.name) : undefined}
    />
  )),

  defineRenderer(AudioApi, ({ props, resolve }) => (
    <ElmAudioPlayer
      src={resolve(props.src)}
      title={props.title ? resolve(props.title) : undefined}
      artist={props.artist ? resolve(props.artist) : undefined}
      seekStep={props.seekStep}
      loop={props.loop}
      autoPlay={props.autoPlay}
    />
  )),

  defineRenderer(VideoApi, ({ props, resolve }) => {
    const caption = props.caption ? resolve(props.caption) : undefined;
    return (
      <figure style={{ margin: 0 }}>
        <video
          src={resolve(props.src)}
          poster={props.poster ? resolve(props.poster) : undefined}
          title={props.title ? resolve(props.title) : undefined}
          width={props.width}
          height={props.height}
          loop={props.loop}
          autoplay={props.autoPlay}
          muted={props.muted}
          controls
          style={{ maxWidth: "100%", height: "auto" }}
        />
        {caption ? <figcaption>{caption}</figcaption> : null}
      </figure>
    );
  }),

  defineRenderer(BlockImageApi, ({ props, resolve }) => (
    <ElmBlockImage
      src={resolve(props.src)}
      alt={props.alt ? resolve(props.alt) : undefined}
      width={props.width}
      height={props.height}
      srcset={props.srcset ? resolve(props.srcset) : undefined}
      sizes={props.sizes ? resolve(props.sizes) : undefined}
      caption={props.caption ? resolve(props.caption) : undefined}
      enableModal={true}
    />
  )),

  defineRenderer(HtmlApi, ({ props, resolve }) => (
    <ElmHtml
      html={props.html ? resolve(props.html) : undefined}
      src={props.src ? resolve(props.src) : undefined}
      autoHeight={props.autoHeight}
      allowScripts={props.allowScripts}
    />
  )),

  // -------------------------------------------------------------------------
  // Code / math / diagram
  // -------------------------------------------------------------------------

  defineRenderer(CodeBlockApi, ({ props, resolve }) => (
    <ElmCodeBlock
      code={resolve(props.code)}
      language={props.language ? resolve(props.language) : undefined}
      caption={props.caption ? resolve(props.caption) : undefined}
    />
  )),

  defineRenderer(KatexApi, ({ props, resolve }) => (
    <ElmKatex expression={resolve(props.expression)} block={true} />
  )),

  // Mermaid is rendered as a syntax-highlighted code block — no dedicated
  // Mermaid renderer in this package. The diagram source is preserved so a
  // host application can post-process if needed.
  defineRenderer(MermaidApi, ({ props, resolve }) => (
    <ElmCodeBlock code={resolve(props.code)} language="mermaid" />
  )),

  // -------------------------------------------------------------------------
  // Tabs — ContentTab is data-only (its parent ContentTabs walks the surface
  // model to read each tab's label and content ChildList directly).
  // -------------------------------------------------------------------------

  defineRenderer(ContentTabApi, () => null),

  defineRenderer(ContentTabsApi, ({ props, surface, renderChild }) => {
    const tabIds = Array.isArray(props.children) ? props.children : [];
    const tabs = tabIds.map((tabId) => {
      const tabModel = surface.componentsModel.get(tabId);
      return {
        tabId,
        labelIds: extractChildIds(tabModel?.properties.label),
        contentIds: extractChildIds(tabModel?.properties.content),
      };
    });
    return (
      <ElmTabs defaultValue="0">
        <ElmTabList>
          {tabs.map(({ tabId, labelIds }, idx) => (
            <ElmTab key={tabId} value={String(idx)}>
              {labelIds.map((lid, i) => (
                <Fragment key={`${lid}:${i}`}>
                  {renderChild(lid, "/", i)}
                </Fragment>
              ))}
            </ElmTab>
          ))}
        </ElmTabList>
        {tabs.map(({ tabId, contentIds }, idx) => (
          <ElmTabPanel key={tabId} value={String(idx)}>
            {contentIds.map((cid, i) => (
              <Fragment key={`${cid}:${i}`}>
                {renderChild(cid, "/", i)}
              </Fragment>
            ))}
          </ElmTabPanel>
        ))}
      </ElmTabs>
    );
  }),

  // -------------------------------------------------------------------------
  // Table
  // -------------------------------------------------------------------------

  defineRenderer(TableApi, ({ props, childRefs, renderChild }) => (
    <ElmTable
      caption={props.caption ? String(props.caption) : undefined}
      hasRowHeader={props.hasRowHeader}
    >
      {props.header && props.header.length > 0 && (
        <ElmTableHeader>
          {childRefs(props.header).map(({ id, path }, i) => (
            <Fragment key={`${id}:${i}`}>{renderChild(id, path, i)}</Fragment>
          ))}
        </ElmTableHeader>
      )}
      <ElmTableBody>
        {childRefs(props.body).map(({ id, path }, i) => (
          <Fragment key={`${id}:${i}`}>{renderChild(id, path, i)}</Fragment>
        ))}
      </ElmTableBody>
    </ElmTable>
  )),

  defineRenderer(TableRowApi, ({ props, childRefs, renderChild }) => (
    <ElmTableRow>
      {childRefs(props.children).map(({ id, path }, i) => (
        <Fragment key={`${id}:${i}`}>{renderChild(id, path, i)}</Fragment>
      ))}
    </ElmTableRow>
  )),

  // `index` is threaded through as `columnIndex` here — unrelated to margin
  // spacing, drives row-header (<th scope="row">) promotion for the first
  // column when `hasRowHeader` is set. See elm-table-cell.tsx.
  defineRenderer(TableCellApi, ({ props, index, childRefs, renderChild }) => (
    <ElmTableCell isHeader={props.isHeader} columnIndex={index}>
      {childRefs(props.children).map(({ id, path }, i) => (
        <span key={`${id}:${i}`}>{renderChild(id, path, i)}</span>
      ))}
    </ElmTableCell>
  )),

  // -------------------------------------------------------------------------
  // Fallback
  // -------------------------------------------------------------------------

  defineRenderer(UnsupportedApi, ({ props }) => (
    <ElmUnsupportedBlock
      details={
        props.details
          ? `Unsupported component type: ${String(props.details)}`
          : "Unsupported component type"
      }
    />
  )),
);
