// packages/qwik/src/hooks/use-bindable-signal.ts
import { useSignal, type Signal } from "@qwik.dev/core";

/**
 * Optionally-bindable signal state.
 *
 * - **Bound:** parent passes their own `Signal<T>`. The hook returns that
 *   same signal — writes from the component go straight to the parent's
 *   signal, and writes from the parent are observed by the component.
 * - **Unbound:** parent omits the signal. The hook returns an
 *   internally-owned signal seeded with `defaultValue`.
 *
 * Use this when the controllable state is a single value. For multi-field /
 * nested-struct state, prefer `useBindableStore`.
 *
 * Note: the internal fallback signal is allocated and serialized for
 * resumption even when the parent supplies their own (hook rules require an
 * unconditional `useSignal` call). The cost is small but non-zero.
 *
 * @example
 *   const checked = useBindableSignal({
 *     signal: props.checked,
 *     defaultValue: props.defaultChecked ?? false,
 *   });
 *   // Use `checked.value` like any signal.
 */
export function useBindableSignal<T>({
  signal,
  defaultValue,
}: {
  /** Parent-owned signal. When omitted, the hook falls back to an internal one. */
  signal?: Signal<T>;
  /** Initial value for the internal signal when unbound. */
  defaultValue: T;
}): Signal<T> {
  // Always call useSignal so hook rules are obeyed; the internal signal is
  // unused (but still serialized) when the parent supplied their own.
  const internal = useSignal<T>(defaultValue);
  return signal ?? internal;
}

// packages/react/src/hooks/use-bindable-signal.ts
import { useControllableState } from "@radix-ui/react-use-controllable-state";
import type { Dispatch, SetStateAction } from "react";

/**
 * Optionally-controllable single-value state.
 *
 * The React API returns a `[value, setValue]` tuple and supports controlled and
 * uncontrolled state:
 *
 * - **Controlled:** parent passes their own `value`. The hook returns that
 *   value — calling `setValue` invokes the parent's `onChange` so the parent
 *   stays the source of truth.
 * - **Uncontrolled:** parent omits `value`. The hook owns internal state
 *   seeded with `defaultValue`.
 *
 * Use this when the controllable state is a single value. For multi-field /
 * nested-struct state, prefer `useBindableStore`.
 *
 * @example
 *   const [checked, setChecked] = useBindableSignal({
 *     value: props.checked,
 *     defaultValue: props.defaultChecked ?? false,
 *     onChange: props.onCheckedChange,
 *   });
 *   // Read `checked`; write with `setChecked(next)`.
 */
export function useBindableSignal<T>({
  value,
  defaultValue,
  onChange,
}: {
  /** Parent-owned value. When omitted, the hook falls back to internal state. */
  value?: T;
  /** Initial value for the internal state when uncontrolled. */
  defaultValue: T;
  /** Invoked whenever the value changes (so a controlling parent can react). */
  onChange?: (value: T) => void;
}): [T, Dispatch<SetStateAction<T>>] {
  return useControllableState<T>({
    prop: value,
    defaultProp: defaultValue,
    onChange,
    caller: "useBindableSignal",
  });
}
