// packages/vue/src/components/navigation/elm-breadcrumb.tsx
import { defineComponent, type HTMLAttributes, type PropType } from "vue";
import { clsx } from "clsx";

import styles from "./elm-breadcrumb.module.css";
import { ElmMdiIcon } from "../icon/elm-mdi-icon";
import {
  mdiApplicationOutline,
  mdiChevronRight,
  mdiFolderOpen,
  mdiHome,
} from "@mdi/js";

export interface ElmBreadcrumbLink {
  /**
   * The text to display.
   */
  text: string;

  /**
   * The action to perform when the link is clicked.
   */
  onClick?: (event: MouseEvent) => void;
}

export interface ElmBreadcrumbProps extends HTMLAttributes {
  links: ElmBreadcrumbLink[];
}

export const ElmBreadcrumb = defineComponent({
  name: "ElmBreadcrumb",
  props: {
    links: { type: Array as PropType<ElmBreadcrumbLink[]>, required: true },
  },
  setup(props) {
    // inheritAttrs default: passthrough class/style merge onto the root nav.
    return () => (
      <nav class={clsx(styles["elm-breadcrumb"])}>
        {props.links.map((link, index) => (
          <span key={index} style={{ display: "contents" }}>
            <span class={styles["link-container"]} onClick={link.onClick}>
              <ElmMdiIcon
                class={styles.icon}
                path={
                  index === 0
                    ? mdiHome
                    : index === props.links.length - 1
                      ? mdiApplicationOutline
                      : mdiFolderOpen
                }
                size="1rem"
              />

              <span class={styles.chunk}>{link.text}</span>
            </span>

            {props.links.length !== index + 1 && (
              <ElmMdiIcon
                class={styles.chevron}
                path={mdiChevronRight}
                size="1rem"
              />
            )}
          </span>
        ))}
      </nav>
    );
  },
});

// packages/react/src/components/navigation/elm-breadcrumb.tsx
import type { ComponentPropsWithoutRef, MouseEvent } from "react";
import { clsx } from "clsx";

import styles from "./elm-breadcrumb.module.css";
import { ElmMdiIcon } from "../icon/elm-mdi-icon";
import {
  mdiApplicationOutline,
  mdiChevronRight,
  mdiFolderOpen,
  mdiHome,
} from "@mdi/js";

export interface ElmBreadcrumbProps extends ComponentPropsWithoutRef<"nav"> {
  links: Array<{
    /**
     * The text to display.
     */
    text: string;

    /**
     * The action to perform when the link is clicked.
     */
    onClick?: (event: MouseEvent<HTMLSpanElement>) => void;
  }>;
}

export const ElmBreadcrumb = ({
  className,
  links,
  ...props
}: ElmBreadcrumbProps) => {
  return (
    <nav className={clsx(styles["elm-breadcrumb"], className)} {...props}>
      {links.map((link, index) => (
        <span key={index} style={{ display: "contents" }}>
          <span className={styles["link-container"]} onClick={link.onClick}>
            <ElmMdiIcon
              className={styles.icon}
              path={
                index === 0
                  ? mdiHome
                  : index === links.length - 1
                    ? mdiApplicationOutline
                    : mdiFolderOpen
              }
              size="1rem"
            />

            <span className={styles.chunk}>{link.text}</span>
          </span>

          {links.length !== index + 1 && (
            <ElmMdiIcon
              className={styles.chevron}
              path={mdiChevronRight}
              size="1rem"
            />
          )}
        </span>
      ))}
    </nav>
  );
};
