// packages/vue/src/components/navigation/elm-page-top.tsx
import {
  defineComponent,
  onBeforeUnmount,
  onMounted,
  ref,
  type CSSProperties,
  type HTMLAttributes,
} from "vue";
import { clsx } from "clsx";

import styles from "./elm-page-top.module.css";

export interface ElmPageTopProps extends HTMLAttributes {
  /**
   * Specifies the position of the button.
   */
  position?: "left" | "right";
}

export const ElmPageTop = defineComponent({
  name: "ElmPageTop",
  props: {
    position: {
      type: String as () => "left" | "right",
      default: "right",
    },
  },
  setup(props) {
    const isVisible = ref(false);

    const checkScroll = () => {
      isVisible.value = window.scrollY > 100;
    };

    onMounted(() => {
      window.addEventListener("scroll", checkScroll, { passive: true });
      checkScroll(); // Check initial state
    });
    onBeforeUnmount(() => window.removeEventListener("scroll", checkScroll));

    const toTop = () => {
      window.scrollTo({ top: 0, behavior: "smooth" });
    };

    // inheritAttrs default: passthrough class/style merge onto the root nav.
    return () => (
      <nav
        class={clsx(styles["elm-page-top"], isVisible.value && styles.visible)}
        style={
          {
            "--elmethis-scoped-size": `${64}px`,
            left: props.position === "left" ? "0" : "auto",
            right: props.position === "right" ? "0" : "auto",
          } as CSSProperties
        }
        onClick={toTop}
      >
        <div aria-hidden="true" class={styles.partial}></div>
        <div aria-hidden="true" class={styles.partial}></div>
        <div aria-hidden="true" class={styles.partial}></div>
        <span class={styles.text}>Back to Top</span>
      </nav>
    );
  },
});

// packages/react/src/components/navigation/ElmPageTop.tsx
import React, { useEffect, useState } from "react";

import "@styles/global.css";
import styles from "./ElmPageTop.module.css";

export interface ElmPageTopCSSVariables {}

export interface ElmPageTopProps {
  style?: React.CSSProperties & ElmPageTopCSSVariables;

  /**
   * Specifies the position of the button.
   */
  position?: "left" | "right";
}

export const ElmPageTop = ({ position = "right", style }: ElmPageTopProps) => {
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    const checkScroll = () => {
      setIsVisible(window.scrollY > 100);
    };

    window.addEventListener("scroll", checkScroll, { passive: true });
    checkScroll();

    return () => window.removeEventListener("scroll", checkScroll);
  }, []);

  const toTop = () => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  return (
    <nav
      className={`${styles.wrapper} ${isVisible ? styles["wrapper--visible"] : ""}`}
      style={
        {
          "--size": "64px",
          left: position === "left" ? "0" : "auto",
          right: position === "right" ? "0" : "auto",
          ...style,
        } as React.CSSProperties
      }
      onClick={toTop}
    >
      <div aria-hidden="true" className={styles.partial} />
      <div aria-hidden="true" className={styles.partial} />
      <div aria-hidden="true" className={styles.partial} />
      <span className={styles.text}>Back to Top</span>
    </nav>
  );
};
